/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snico-0.4.10-f4d0514d40cc9aeaa3f02e3654986ff28d1038ec@snico@sringbuffer.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snico-0.4.10-f4d0514d40cc9aeaa3f02e3654986ff28d1038ec@snico@sringbuffer.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg;
typedef struct tySequence__EwWnHvzGVmDuLlfmw6Igdg tySequence__EwWnHvzGVmDuLlfmw6Igdg;
typedef struct tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content;
typedef struct tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw;
typedef struct tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A;
typedef struct tySequence__4l0J2KoADAIc79csLV36IwA tySequence__4l0J2KoADAIc79csLV36IwA;
typedef struct tySequence__4l0J2KoADAIc79csLV36IwA_Content tySequence__4l0J2KoADAIc79csLV36IwA_Content;
typedef struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg;
typedef struct tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig;
struct tySequence__EwWnHvzGVmDuLlfmw6Igdg {
  NI len; tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content* p;
};
struct tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg {
	tySequence__EwWnHvzGVmDuLlfmw6Igdg data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
struct tySequence__4l0J2KoADAIc79csLV36IwA {
  NI len; tySequence__4l0J2KoADAIc79csLV36IwA_Content* p;
};
struct tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A {
	tySequence__4l0J2KoADAIc79csLV36IwA data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg {
	NI rc;
	NI rootIdx;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA {
	NimStringV2 name;
	tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig start;
	NI64 time;
	NI count;
	tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA* parent;
	tySequence__EwWnHvzGVmDuLlfmw6Igdg children;
};
struct tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content { NI cap; tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA data[SEQ_DECL_SIZE]; };
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__4l0J2KoADAIc79csLV36IwA_Content { NI cap; tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__EwWnHvzGVmDuLlfmw6Igdg, newSeq__pkgZnicoZbackendsZcommon_u1745)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1852)(tySequence__EwWnHvzGVmDuLlfmw6Igdg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u6077)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ, newSeq__pkgZnicoZbackendsZsdl2_u6375)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZnicoZbackendsZcommon_u1110)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw** dest_p0, tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* src_p1);
N_LIB_PRIVATE N_NIMCALL(NI, idx__pkgZnicoZbackendsZsdl2_u812)(tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A b_p0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(NI, floorMod__pkgZnicoZbackendsZsdl2_u817)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7574)(tySequence__4l0J2KoADAIc79csLV36IwA dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1125)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg, initRingBuffer__pkgZnicoZbackendsZcommon_u1725)(NI length_p0) {
	tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg result;
	tySequence__EwWnHvzGVmDuLlfmw6Igdg s;
	NI colontmpD_;
	tySequence__EwWnHvzGVmDuLlfmw6Igdg blitTmp;
	nimZeroMem((void*)(&result), sizeof(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg));
	s.len = 0; s.p = NIM_NIL;
	colontmpD_ = (NI)0;
	s = newSeq__pkgZnicoZbackendsZcommon_u1745((length_p0));
	blitTmp = s;
	result.data = blitTmp;
	result.head = ((NI)0);
	result.tail = ((NI)-1);
	result.size = ((NI)0);
	colontmpD_ = length_p0;
	result.length = colontmpD_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1921)(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pkgZnicoZbackendsZcommon_u1852((*dest_p0).data);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZsdl2_u6506)(tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg* dest_p0, tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg src_p1) {
	if ((*dest_p0).data.p != src_p1.data.p) {	eqdestroy___pkgZnicoZbackendsZsdl2_u6077((*dest_p0).data);
	}
(*dest_p0).data.len = src_p1.data.len; (*dest_p0).data.p = src_p1.data.p;
	(*dest_p0).head = src_p1.head;
	(*dest_p0).tail = src_p1.tail;
	(*dest_p0).size = src_p1.size;
	(*dest_p0).length = src_p1.length;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg, initRingBuffer__pkgZnicoZbackendsZsdl2_u6468)(NI length_p0) {
	tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg result;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ s;
	NI colontmpD_;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ blitTmp;
	nimZeroMem((void*)(&result), sizeof(tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg));
	s.len = 0; s.p = NIM_NIL;
	colontmpD_ = (NI)0;
	s = newSeq__pkgZnicoZbackendsZsdl2_u6375((length_p0));
	blitTmp = s;
	result.data = blitTmp;
	result.head = ((NI)0);
	result.tail = ((NI)-1);
	result.size = ((NI)0);
	colontmpD_ = length_p0;
	result.length = colontmpD_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u6497)(tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg* dest_p0) {
	eqdestroy___pkgZnicoZbackendsZsdl2_u6077((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, add__pkgZnicoZbackendsZsdl2_u6327)(tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg* b_p0, NF32 data_p1) {
	(*b_p0).tail = (NI)((NI)((*b_p0).tail + ((NI)1)) % (*b_p0).length);
	(*b_p0).data.p->data[(*b_p0).tail] = data_p1;
	(*b_p0).size = (((NI)((*b_p0).size + ((NI)1)) <= (*b_p0).length) ? (NI)((*b_p0).size + ((NI)1)) : (*b_p0).length);
	(*b_p0).head = (NI)((NI)((NI)((NI)((*b_p0).length + (*b_p0).tail) - (*b_p0).size) + ((NI)1)) % (*b_p0).length);
}
N_LIB_PRIVATE N_NIMCALL(NI, idx__pkgZnicoZbackendsZsdl2_u812)(tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A b_p0, NI i_p1) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	{
		if (!(i_p1 < ((NI)0))) goto LA3_;
		colontmpD_ = floorMod__pkgZnicoZbackendsZsdl2_u817((NI)(b_p0.tail + (NI)(i_p1 + ((NI)1))), b_p0.length);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = floorMod__pkgZnicoZbackendsZsdl2_u817((NI)(i_p1 + b_p0.head), b_p0.length);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw*, X5BX5D___pkgZnicoZbackendsZsdl2_u802)(tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A b_p0, NI i_p1) {
	tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = (NI)0;
	T1_ = idx__pkgZnicoZbackendsZsdl2_u812(b_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqcopy___pkgZnicoZbackendsZcommon_u1110(&result, b_p0.data.p->data[T1_]);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((NI32)((*cell).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7574)(tySequence__4l0J2KoADAIc79csLV36IwA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___pkgZnicoZbackendsZcommon_u1125(dest_p0.p->data[colontmp_]);
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)4));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7556)(tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A* dest_p0) {
	eqdestroy___pkgZnicoZbackendsZsdl2_u7574((*dest_p0).data);
}
