/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@sstd@sprivate@sospaths2.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@sstd@sprivate@sospaths2.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8268)(NimStringV2 s_p0, NI i_p1);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8320)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2441)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_u86)(NimStringV2 x_p0, NimStringV2* result_p1, NI* state_p2, NIM_CHAR dirSep_p3);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__stdZprivateZospaths2_u163)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizePath__pureZpathnorm_u150)(NimStringV2 path_p0, NIM_CHAR dirSep_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8826)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NI, searchExtPos__stdZprivateZospaths2_u242)(NimStringV2 path_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normExt__stdZprivateZospaths2_u239)(NimStringV2 ext_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_2 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_3 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_4 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_5 = {2, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_6 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_7 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_9 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_8};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_10 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
static N_INLINE(NIM_CHAR, X5BX5D___system_u8268)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	result = s_p0.p->data[(NI)(s_p0.len - i_p1)];
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2441(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8320)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	nimPrepareStrMutationV2((&(*s_p0)));
	result = (&(*s_p0).p->data[(NI)((*s_p0).len - i_p1)]);
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1) {
	NI i;
{	{
		if (!((*path_p0).len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	i = (*path_p0).len;
	{
		while (1) {
			if (!(((NI)1) <= i)) goto LA6;
			{
				if (!(((NU8)((*path_p0).p->data[(NI)(i - ((NI)1))])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(i - ((NI)1))])) == ((NU8)(47)))) goto LA9_;
				i -= ((NI)1);
			}
			goto LA7_;
LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				T13_ = ((NU8)((*path_p0).p->data[(NI)(i - ((NI)1))]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI)2) <= i);
LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				T12_ = (((NU8)((*path_p0).p->data[(NI)(i - ((NI)2))])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(i - ((NI)2))])) == ((NU8)(47)));
LA15_: ;
				if (!T12_) goto LA16_;
				i -= ((NI)1);
			}
			goto LA7_;
LA16_: ;
			{
				goto LA5;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	{
		if (!trailingSep_p1) goto LA21_;
		setLengthStrV2((&(*path_p0)), (i));
		nimAddCharV1((&(*path_p0)), 47);
	}
	goto LA19_;
LA21_: ;
	{
		if (!(((NI)0) < i)) goto LA24_;
		setLengthStrV2((&(*path_p0)), (i));
	}
	goto LA19_;
LA24_: ;
	{
		eqsink___system_u2696((&(*path_p0)), TM__O1zDbSYyG8zQytyoZAh0dg_3);
	}
LA19_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2) {
	NIM_BOOL trailingSep;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	T2_ = (((NI)0) < tail_p2.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_u8268(tail_p2, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (((NU8)(T4_)) == ((NU8)(47)) || ((NU8)(T4_)) == ((NU8)(47)));
LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	T6_ = (NIM_BOOL)0;
	T6_ = (tail_p2.len == ((NI)0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	T8_ = (((NI)0) < (*result_p0).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_u8320(result_p0, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (((NU8)((*T10_))) == ((NU8)(47)) || ((NU8)((*T10_))) == ((NU8)(47)));
LA9_: ;
	T6_ = T8_;
LA7_: ;
	T1_ = T6_;
LA5_: ;
	trailingSep = T1_;
	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addNormalizePath__pureZpathnorm_u86(tail_p2, result_p0, state_p1, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, trailingSep);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
	NI state;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = rawNewString(((NI)(head_p0.len + tail_p1.len)));
	state = ((NI)0);
	joinPathImpl__stdZprivateZospaths2_u49((&result), (&state), head_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	joinPathImpl__stdZprivateZospaths2_u49((&result), (&state), tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0) {
	NIM_BOOL result;
{	{
		if (!(path_p0.len == ((NI)0))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	result = ((NU8)(path_p0.p->data[((NI)0)]) == (NU8)(47));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__stdZprivateZospaths2_u163)(NimStringV2 path_p0) {
	NI result;
	NI q;
{	q = ((NI)1);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)1) <= path_p0.len);
		if (!(T3_)) goto LA4_;
		T3_ = (((NU8)(path_p0.p->data[(NI)(path_p0.len - ((NI)1))])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[(NI)(path_p0.len - ((NI)1))])) == ((NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		q = ((NI)2);
	}
LA5_: ;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(path_p0.len - q);
		res = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res)) goto LA9;
				i = ((NI) (res));
				{
					if (!(((NU8)(path_p0.p->data[i])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i])) == ((NU8)(47)))) goto LA12_;
					result = i;
					goto BeforeRet_;
				}
LA12_: ;
				res -= ((NI)1);
			} LA9: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringV2 path_p0) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = parentDirPos__stdZprivateZospaths2_u163(path_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (T1_ < ((NI)0));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = NIM_FALSE;
	alen = a_p0.len;
	blen = b_p1.len;
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0) {
	NimStringV2 result;
	NI sepPos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = normalizePath__pureZpathnorm_u150(path_p0, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	sepPos = parentDirPos__stdZprivateZospaths2_u163(result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 T5_;
		if (!(((NI)0) <= sepPos)) goto LA3_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = substr__system_u8826(result, ((NI)0), sepPos);
		eqsink___system_u2696((&result), T5_);
		normalizePathEnd__stdZprivateZospaths2_u20((&result), NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		NIM_BOOL T9_;
		NIM_CHAR* T13_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_BOOL)0;
		T9_ = eqStrings(result, TM__O1zDbSYyG8zQytyoZAh0dg_5);
		if (T9_) goto LA10_;
		T9_ = eqStrings(result, TM__O1zDbSYyG8zQytyoZAh0dg_7);
LA10_: ;
		T8_ = T9_;
		if (T8_) goto LA11_;
		T8_ = (result.len == ((NI)0));
LA11_: ;
		T7_ = T8_;
		if (T7_) goto LA12_;
		T13_ = (NIM_CHAR*)0;
		T13_ = X5BX5D___system_u8320((&result), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T7_ = (((NU8)((*T13_))) == ((NU8)(47)) || ((NU8)((*T13_))) == ((NU8)(47)));
LA12_: ;
		if (!T7_) goto LA14_;
		eqsink___system_u2696((&result), TM__O1zDbSYyG8zQytyoZAh0dg_9);
	}
	goto LA1_;
LA14_: ;
	{
		eqsink___system_u2696((&result), TM__O1zDbSYyG8zQytyoZAh0dg_10);
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZprivateZospaths2_u312)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0, tyTuple__UV3llMMYFckfui8YMBuUZA src_p1) {
	if ((*dest_p0).Field0.p != src_p1.Field0.p) {	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
	}
(*dest_p0).Field0.len = src_p1.Field0.len; (*dest_p0).Field0.p = src_p1.Field0.p;
	if ((*dest_p0).Field1.p != src_p1.Field1.p) {	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
	}
(*dest_p0).Field1.len = src_p1.Field1.len; (*dest_p0).Field1.p = src_p1.Field1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZospaths2_u303)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(NI, searchExtPos__stdZprivateZospaths2_u242)(NimStringV2 path_p0) {
	NI result;
	NI i;
{	result = ((NI)-1);
	i = (path_p0.len-1);
	{
		while (1) {
			if (!(((NI)1) <= i)) goto LA2;
			{
				if (!((NU8)(path_p0.p->data[i]) == (NU8)(46))) goto LA5_;
				goto LA1;
			}
			goto LA3_;
LA5_: ;
			{
				if (!(((NU8)(path_p0.p->data[i])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i])) == ((NU8)(47)))) goto LA8_;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA3_;
LA8_: ;
LA3_: ;
			i -= ((NI)1);
		} LA2: ;
	} LA1: ;
	{
		NI j;
		NI colontmp_;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(i - ((NI)1));
		res = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res)) goto LA12;
				j = ((NI) (res));
				{
					if (!(((NU8)(path_p0.p->data[j])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[j])) == ((NU8)(47)))) goto LA15_;
					result = ((NI)-1);
					goto BeforeRet_;
				}
				goto LA13_;
LA15_: ;
				{
					if (!!(((NU8)(path_p0.p->data[j]) == (NU8)(46)))) goto LA18_;
					result = i;
					goto LA10;
				}
				goto LA13_;
LA18_: ;
LA13_: ;
				res -= ((NI)1);
			} LA12: ;
		}
	} LA10: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(src_p1.len + ((NI)1))));
		(*dest_p0).len += src_p1.len;
	}
LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normExt__stdZprivateZospaths2_u239)(NimStringV2 ext_p0) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ext_p0.len == 0);
		if (T3_) goto LA4_;
		T3_ = ((NU8)(ext_p0.p->data[((NI)0)]) == (NU8)(46));
LA4_: ;
		if (!T3_) goto LA5_;
		eqcopy___system_u2690((&result), ext_p0);
	}
	goto LA1_;
LA5_: ;
	{
		NimStringV2 T8_;
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(ext_p0.len + 1);
appendChar((&T8_), 46);
appendString((&T8_), ext_p0);
		result = T8_;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosaddFileExt)(NimStringV2 filename_p0, NimStringV2 ext_p1) {
	NimStringV2 result;
	NI extPos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	extPos = searchExtPos__stdZprivateZospaths2_u242(filename_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 colontmpD_;
		NimStringV2 T5_;
		if (!(extPos < ((NI)0))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		T5_.len = 0; T5_.p = NIM_NIL;
		colontmpD_ = normExt__stdZprivateZospaths2_u239(ext_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T5_ = rawNewString(filename_p0.len + colontmpD_.len + 0);
appendString((&T5_), filename_p0);
appendString((&T5_), colontmpD_);
		result = T5_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	goto LA1_;
LA3_: ;
	{
		eqcopy___system_u2690((&result), filename_p0);
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
