/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@spure@sparsecfg.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@spure@sparsecfg.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_FileStreamObj__5DpayuUADAWFvqmaNzmWQQ tyObject_FileStreamObj__5DpayuUADAWFvqmaNzmWQQ;
typedef struct tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_HSlice__DO5p5S32LbatC4OszWRAIA tyObject_HSlice__DO5p5S32LbatC4OszWRAIA;
typedef struct tySequence__9cuxMvPTCY59apayZQ9aPRnuQ tySequence__9cuxMvPTCY59apayZQ9aPRnuQ;
typedef struct tySequence__9cuxMvPTCY59apayZQ9aPRnuQ_Content tySequence__9cuxMvPTCY59apayZQ9aPRnuQ_Content;
typedef struct tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw;
typedef struct tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg;
typedef struct tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw;
typedef struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg;
typedef struct tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ;
typedef struct tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw;
typedef struct tyTuple__KKQKvM3dsxdtYGn9cLuLUWA tyTuple__KKQKvM3dsxdtYGn9cLuLUWA;
typedef struct tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA;
typedef struct tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg;
typedef struct tySequence__dl1tcid0VwP1mpWNDzitYw tySequence__dl1tcid0VwP1mpWNDzitYw;
typedef struct tySequence__dl1tcid0VwP1mpWNDzitYw_Content tySequence__dl1tcid0VwP1mpWNDzitYw_Content;
typedef struct tyTuple__ktXV9bbcCUeU4L9amlAa5QkQ tyTuple__ktXV9bbcCUeU4L9amlAa5QkQ;
typedef struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__NOotkCEDdzClfG8nOJdANg;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__qFtPiArvTLs9aLHfBnp8Vyw) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__k9aIo4nr0k2Z1bpIS3anQ1g) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__IDMlkxgUZM2moxooT9ag01w) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__FzA1MTISmh9angjjA386gkA) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__8kgJV02C7W4rHNCint9aXIA) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__DO5p5S32LbatC4OszWRAIA slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__XAFAe7pn9cM54yXi0T9bDoJA) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__sS5pT015KHKoqdfoeXhrHQ) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__HfF9aKAAyZtQEiN7BWjhY9bQ) (tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA {
	RootObj Sup;
	tyProc__qFtPiArvTLs9aLHfBnp8Vyw closeImpl;
	tyProc__k9aIo4nr0k2Z1bpIS3anQ1g atEndImpl;
	tyProc__IDMlkxgUZM2moxooT9ag01w setPositionImpl;
	tyProc__FzA1MTISmh9angjjA386gkA getPositionImpl;
	tyProc__8kgJV02C7W4rHNCint9aXIA readDataStrImpl;
	tyProc__XAFAe7pn9cM54yXi0T9bDoJA readLineImpl;
	tyProc__sS5pT015KHKoqdfoeXhrHQ readDataImpl;
	tyProc__sS5pT015KHKoqdfoeXhrHQ peekDataImpl;
	tyProc__HfF9aKAAyZtQEiN7BWjhY9bQ writeDataImpl;
	tyProc__qFtPiArvTLs9aLHfBnp8Vyw flushImpl;
};
struct tyObject_FileStreamObj__5DpayuUADAWFvqmaNzmWQQ {
	tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA Sup;
	FILE* f;
};
struct tySequence__9cuxMvPTCY59apayZQ9aPRnuQ {
  NI len; tySequence__9cuxMvPTCY59apayZQ9aPRnuQ_Content* p;
};
struct tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g {
	tySequence__9cuxMvPTCY59apayZQ9aPRnuQ data;
	NI counter;
	NI first;
	NI last;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg {
	RootObj Sup;
	NI bufpos;
	NimStringV2 buf;
	tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww;
struct tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw {
	tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww kind;
	NimStringV2 literal;
};
struct tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw {
	tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg Sup;
	tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw tok;
	NimStringV2 filename;
};
struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw {
	NI len;
	NI cap;
	tyTuple__KKQKvM3dsxdtYGn9cLuLUWA* d;
};
struct tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ {
	tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg traceStack;
	tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
typedef NU8 tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw;
struct tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA {
	RootObj Sup;
	tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw kind;
union{
	struct {
	NimStringV2 section;
} _kind_2;
	struct {
	NimStringV2 key;
	NimStringV2 value;
} _kind_3;
	struct {
	NimStringV2 msg;
} _kind_4;
};
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tySequence__dl1tcid0VwP1mpWNDzitYw {
  NI len; tySequence__dl1tcid0VwP1mpWNDzitYw_Content* p;
};
struct tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg {
	tySequence__dl1tcid0VwP1mpWNDzitYw data;
	NI counter;
	NI first;
	NI last;
};
struct tyObject_HSlice__DO5p5S32LbatC4OszWRAIA {
	NI a;
	NI b;
};
struct tyTuple__ktXV9bbcCUeU4L9amlAa5QkQ {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* Field3;
};
struct tySequence__9cuxMvPTCY59apayZQ9aPRnuQ_Content { NI cap; tyTuple__ktXV9bbcCUeU4L9amlAa5QkQ data[SEQ_DECL_SIZE]; };
struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	NimStringV2 Field3;
};
struct tySequence__dl1tcid0VwP1mpWNDzitYw_Content { NI cap; tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u484)(NimStringV2 filename_p0, tyEnum_FileMode__NOotkCEDdzClfG8nOJdANg mode_p1, NI bufSize_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__5DpayuUADAWFvqmaNzmWQQ*, newFileStream__pureZstreams_u1185)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g*, loadConfig__pureZparsecfg_u950)(tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* stream_p0, NimStringV2 filename_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecfg_u8566)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u61)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3528)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecfg_u73)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3019)(tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg* s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g*, newOrderedTable__pureZparsecfg_u487)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* input_p1, NimStringV2 filename_p2, NI lineOffset_p3);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_u130)(tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg* L_p0, tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* input_p1, NI bufLen_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2687)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok__pureZparsecfg_u45)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsecfg_u279)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, handleCRLF__pureZparsecfg_u227)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_u83)(tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_u95)(tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, getSymbol__pureZparsecfg_u266)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8320)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2441)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, getString__pureZparsecfg_u231)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1, NIM_BOOL rawMode_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, getEscapedChar__pureZparsecfg_u147)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1);
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_u1)(NIM_CHAR c_p0, NI* x_p1);
N_LIB_PRIVATE N_NIMCALL(void, handleDecChars__pureZparsecfg_u129)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, NI* xi_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecfg_u8575)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u394)(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* Result);
N_LIB_PRIVATE N_NIMCALL(void, getKeyValPair__pureZparsecfg_u351)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw kind_p1, tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZparsecfg_u403)(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* dest_p0, tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, npcerrorStr)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, NimStringV2 msg_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(NI, npcgetLine)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, npcgetColumn)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_u145)(tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg*, newOrderedTable__pureZparsecfg_u1001)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZparsecfg_u1145)(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZparsecfg_u1089)(tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg** dest_p0, tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg**, X5BX5D___pureZparsecfg_u1533)(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_u1959)(tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* t_p0, NimStringV2 key_p1, NimStringV2 val_p2);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_u3500)(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* t_p0, NimStringV2 key_p1, tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* val_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZparsecfg_u1083)(tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u1086)(tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_u14)(tyObject_BaseLexer__NtiKWpszKgLWfoK9b0JkXOg* L_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZparsecfg_u925)(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u928)(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u57)(tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u1093)(tyObject_FileStreamObj__5DpayuUADAWFvqmaNzmWQQ* dest_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__RgEQOWxkmjjaWAmIB5Rndw_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4 = {0, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6 = {0, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9 = { 2 | NIM_STRLIT_FLAG, "--" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_10 = {2, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11 = {
0x00, 0x00, 0x00, 0x00, 0x01, 0xe0, 0xff, 0x03,
0xfe, 0xff, 0xff, 0x97, 0xfe, 0xff, 0xff, 0x07,
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}
;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_15 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_16 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_20 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21 = { 5 | NIM_STRLIT_FLAG, "[EOF]" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22 = {5, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21};
N_LIB_PRIVATE TNimTypeV2 NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_;
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24 = {0, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_25 = { 20 | NIM_STRLIT_FLAG, "$1($2, $3) Error: $4" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26 = {20, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_25};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27 = { 28 | NIM_STRLIT_FLAG, "symbol expected, but found: " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28 = {28, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_29 = {28, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_30 = {28, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31 = { 25 | NIM_STRLIT_FLAG, "\']\' expected, but found: " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_32 = {25, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_33 = { 15 | NIM_STRLIT_FLAG, "invalid token: " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34 = {15, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_33};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_35 = {2, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
static NIM_CONST NU32 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2[3] = {3701606400, 3632945664, 17840384};
N_LIB_PRIVATE TNimTypeV2 NTIv2__RgEQOWxkmjjaWAmIB5Rndw_ = {.destructor = (void*)rttiDestroy__pureZparsecfg_u8566, .size = sizeof(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw), .align = (NI16) NIM_ALIGNOF(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw), .depth = 2, .display = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2, .traceImpl = (void*)eqtrace___pureZparsecfg_u73, .flags = 0};
static NIM_CONST NU32 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23[2] = {3701606400, 32138240};
N_LIB_PRIVATE TNimTypeV2 NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_ = {.destructor = (void*)rttiDestroy__pureZparsecfg_u8575, .size = sizeof(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA), .align = (NI16) NIM_ALIGNOF(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA), .depth = 1, .display = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
		rememberCycle__system_u3528(result, cell, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u61)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* dest_p0) {
	if ((*dest_p0).Sup.buf.p && !((*dest_p0).Sup.buf.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.buf.p);
}
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.input);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.input);
	}
LA4_: ;
	if ((*dest_p0).tok.literal.p && !((*dest_p0).tok.literal.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).tok.literal.p);
}
	if ((*dest_p0).filename.p && !((*dest_p0).filename.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).filename.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecfg_u8566)(void* dest_p0) {
	eqdestroy___pureZparsecfg_u61(((tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*) (dest_p0)));
}
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u3019(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len += ((NI)1);
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p;
	p = ((void**) (q_p0));
	{
		tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		j = ((tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ*) (env_p1));
		add__system_u3011((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecfg_u73)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.input, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, handleCRLF__pureZparsecfg_u227)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, NI pos_p1) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	switch (((NU8)((*c_p0).Sup.buf.p->data[pos_p1]))) {
	case 13:
	{
		result = handleCR__pureZlexbase_u83(&c_p0->Sup, pos_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case 10:
	{
		result = handleLF__pureZlexbase_u95(&c_p0->Sup, pos_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		result = pos_p1;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsecfg_u279)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0) {
	NI pos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	pos = (*c_p0).Sup.bufpos;
	{
		while (1) {
			switch (((NU8)((*c_p0).Sup.buf.p->data[pos]))) {
			case 32:
			case 9:
			{
				pos += ((NI)1);
			}
			break;
			case 35:
			case 59:
			{
				{
					while (1) {
						if (!!((((NU8)((*c_p0).Sup.buf.p->data[pos])) == ((NU8)(13)) || ((NU8)((*c_p0).Sup.buf.p->data[pos])) == ((NU8)(10)) || ((NU8)((*c_p0).Sup.buf.p->data[pos])) == ((NU8)(0))))) goto LA6;
						pos += ((NI)1);
					} LA6: ;
				}
			}
			break;
			case 13:
			case 10:
			{
				pos = handleCRLF__pureZparsecfg_u227(c_p0, pos);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	(*c_p0).Sup.bufpos = pos;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2441(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8320)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	nimPrepareStrMutationV2((&(*s_p0)));
	result = (&(*s_p0).p->data[(NI)((*s_p0).len - i_p1)]);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getSymbol__pureZparsecfg_u266)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1) {
	NI pos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	pos = (*c_p0).Sup.bufpos;
	{
		while (1) {
			nimAddCharV1((&(*tok_p1).literal), (*c_p0).Sup.buf.p->data[pos]);
			pos += ((NI)1);
			{
				if (!!(((TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11[(NU)((((NU8)((*c_p0).Sup.buf.p->data[pos]))))>>3] &(1U<<((NU)((((NU8)((*c_p0).Sup.buf.p->data[pos]))))&7U)))!=0))) goto LA5_;
				goto LA1;
			}
LA5_: ;
		}
	} LA1: ;
	{
		while (1) {
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI)0) < (*tok_p1).literal.len);
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_u8320((&(*tok_p1).literal), ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T9_ = ((NU8)((*T11_)) == (NU8)(32));
LA10_: ;
			if (!T9_) goto LA8;
			setLengthStrV2((&(*tok_p1).literal), ((NI)((*tok_p1).literal.len - ((NI)1))));
		} LA8: ;
	}
	(*c_p0).Sup.bufpos = pos;
	(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)2);
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(src_p1.len + ((NI)1))));
		(*dest_p0).len += src_p1.len;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_u1)(NIM_CHAR c_p0, NI* x_p1) {
	NIM_BOOL result;
	result = NIM_TRUE;
	switch (((NU8)(c_p0))) {
	case 48 ... 57:
	{
		(*x_p1) = (NI)((NI)((NU32)((*x_p1)) << (NU32)(((NI)4))) | (NI)(((NU8)(c_p0)) - ((NI)48)));
	}
	break;
	case 97 ... 102:
	{
		(*x_p1) = (NI)((NI)((NU32)((*x_p1)) << (NU32)(((NI)4))) | (NI)((NI)(((NU8)(c_p0)) - ((NI)97)) + ((NI)10)));
	}
	break;
	case 65 ... 70:
	{
		(*x_p1) = (NI)((NI)((NU32)((*x_p1)) << (NU32)(((NI)4))) | (NI)((NI)(((NU8)(c_p0)) - ((NI)65)) + ((NI)10)));
	}
	break;
	default:
	{
		result = NIM_FALSE;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, handleDecChars__pureZparsecfg_u129)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, NI* xi_p1) {
	{
		while (1) {
			if (!(((NU8)((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos])) >= ((NU8)(48)) && ((NU8)((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos])) <= ((NU8)(57)))) goto LA2;
			(*xi_p1) = (NI)((NI)((*xi_p1) * ((NI)10)) + (NI)(((NU8)((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos])) - ((NI)48)));
			(*c_p0).Sup.bufpos += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, getEscapedChar__pureZparsecfg_u147)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	(*c_p0).Sup.bufpos += ((NI)1);
	switch (((NU8)((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos]))) {
	case 110:
	case 78:
	{
		prepareAdd((&(*tok_p1).literal), 1);
appendString((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_16);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 114:
	case 82:
	case 99:
	case 67:
	{
		nimAddCharV1((&(*tok_p1).literal), 13);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 108:
	case 76:
	{
		nimAddCharV1((&(*tok_p1).literal), 10);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 102:
	case 70:
	{
		nimAddCharV1((&(*tok_p1).literal), 12);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 101:
	case 69:
	{
		nimAddCharV1((&(*tok_p1).literal), 27);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 97:
	case 65:
	{
		nimAddCharV1((&(*tok_p1).literal), 7);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 98:
	case 66:
	{
		nimAddCharV1((&(*tok_p1).literal), 8);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 118:
	case 86:
	{
		nimAddCharV1((&(*tok_p1).literal), 11);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 116:
	case 84:
	{
		nimAddCharV1((&(*tok_p1).literal), 9);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 39:
	case 34:
	{
		nimAddCharV1((&(*tok_p1).literal), (*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos]);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 92:
	{
		nimAddCharV1((&(*tok_p1).literal), 92);
		(*c_p0).Sup.bufpos += ((NI)1);
	}
	break;
	case 120:
	case 88:
	{
		NI xi;
		(*c_p0).Sup.bufpos += ((NI)1);
		xi = ((NI)0);
		{
			NIM_BOOL T15_;
			T15_ = (NIM_BOOL)0;
			T15_ = handleHexChar__stdZprivateZdecode95helpers_u1((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos], (&xi));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T15_) goto LA16_;
			(*c_p0).Sup.bufpos += ((NI)1);
			{
				NIM_BOOL T20_;
				T20_ = (NIM_BOOL)0;
				T20_ = handleHexChar__stdZprivateZdecode95helpers_u1((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos], (&xi));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!T20_) goto LA21_;
				(*c_p0).Sup.bufpos += ((NI)1);
			}
LA21_: ;
		}
LA16_: ;
		nimAddCharV1((&(*tok_p1).literal), ((NIM_CHAR) ((xi))));
	}
	break;
	case 48 ... 57:
	{
		NI xi_2;
		xi_2 = ((NI)0);
		handleDecChars__pureZparsecfg_u129(c_p0, (&xi_2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(xi_2 <= ((NI)255))) goto LA26_;
			nimAddCharV1((&(*tok_p1).literal), ((NIM_CHAR) ((xi_2))));
		}
		goto LA24_;
LA26_: ;
		{
			(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0);
		}
LA24_: ;
	}
	break;
	default:
	{
		(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0);
	}
	break;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, getString__pureZparsecfg_u231)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1, NIM_BOOL rawMode_p2) {
	NI pos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	pos = (NI)((*c_p0).Sup.bufpos + ((NI)1));
	(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)2);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((NU8)((*c_p0).Sup.buf.p->data[pos]) == (NU8)(34));
		if (!(T3_)) goto LA4_;
		T3_ = ((NU8)((*c_p0).Sup.buf.p->data[(NI)(pos + ((NI)1))]) == (NU8)(34));
LA4_: ;
		if (!T3_) goto LA5_;
		pos += ((NI)2);
		pos = handleCRLF__pureZparsecfg_u227(c_p0, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			while (1) {
				switch (((NU8)((*c_p0).Sup.buf.p->data[pos]))) {
				case 34:
				{
					{
						NIM_BOOL T12_;
						T12_ = (NIM_BOOL)0;
						T12_ = ((NU8)((*c_p0).Sup.buf.p->data[(NI)(pos + ((NI)1))]) == (NU8)(34));
						if (!(T12_)) goto LA13_;
						T12_ = ((NU8)((*c_p0).Sup.buf.p->data[(NI)(pos + ((NI)2))]) == (NU8)(34));
LA13_: ;
						if (!T12_) goto LA14_;
						goto LA7;
					}
LA14_: ;
					nimAddCharV1((&(*tok_p1).literal), 34);
					pos += ((NI)1);
				}
				break;
				case 13:
				case 10:
				{
					pos = handleCRLF__pureZparsecfg_u227(c_p0, pos);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					prepareAdd((&(*tok_p1).literal), 1);
appendString((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_15);
				}
				break;
				case 0:
				{
					(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0);
					goto LA7;
				}
				break;
				default:
				{
					nimAddCharV1((&(*tok_p1).literal), (*c_p0).Sup.buf.p->data[pos]);
					pos += ((NI)1);
				}
				break;
				}
			}
		} LA7: ;
		(*c_p0).Sup.bufpos = (NI)(pos + ((NI)3));
	}
	goto LA1_;
LA5_: ;
	{
		{
			while (1) {
				NIM_CHAR ch;
				ch = (*c_p0).Sup.buf.p->data[pos];
				{
					if (!((NU8)(ch) == (NU8)(34))) goto LA24_;
					pos += ((NI)1);
					goto LA20;
				}
LA24_: ;
				{
					if (!(((NU8)(ch)) == ((NU8)(13)) || ((NU8)(ch)) == ((NU8)(10)) || ((NU8)(ch)) == ((NU8)(0)))) goto LA28_;
					(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0);
					goto LA20;
				}
LA28_: ;
				{
					NIM_BOOL T32_;
					T32_ = (NIM_BOOL)0;
					T32_ = ((NU8)(ch) == (NU8)(92));
					if (!(T32_)) goto LA33_;
					T32_ = !(rawMode_p2);
LA33_: ;
					if (!T32_) goto LA34_;
					(*c_p0).Sup.bufpos = pos;
					getEscapedChar__pureZparsecfg_u147(c_p0, tok_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					pos = (*c_p0).Sup.bufpos;
				}
				goto LA30_;
LA34_: ;
				{
					nimAddCharV1((&(*tok_p1).literal), ch);
					pos += ((NI)1);
				}
LA30_: ;
			}
		} LA20: ;
		(*c_p0).Sup.bufpos = pos;
	}
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok__pureZparsecfg_u45)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_Token__TxDXF3GRkEC1dmJzfTVJYw* tok_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0);
	setLengthStrV2((&(*tok_p1).literal), ((NI)0));
	skip__pureZparsecfg_u279(c_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	switch (((NU8)((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos]))) {
	case 61:
	{
		(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)3);
		(*c_p0).Sup.bufpos += ((NI)1);
		eqsink___system_u2696((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8);
	}
	break;
	case 45:
	{
		(*c_p0).Sup.bufpos += ((NI)1);
		{
			if (!((NU8)((*c_p0).Sup.buf.p->data[(*c_p0).Sup.bufpos]) == (NU8)(45))) goto LA5_;
			(*c_p0).Sup.bufpos += ((NI)1);
			(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)7);
			eqsink___system_u2696((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_10);
		}
		goto LA3_;
LA5_: ;
		{
			(*c_p0).Sup.bufpos -= ((NI)1);
			getSymbol__pureZparsecfg_u266(c_p0, tok_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA3_: ;
	}
	break;
	case 58:
	{
		(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)4);
		(*c_p0).Sup.bufpos += ((NI)1);
		eqsink___system_u2696((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13);
	}
	break;
	case 114:
	case 82:
	{
		{
			if (!((NU8)((*c_p0).Sup.buf.p->data[(NI)((*c_p0).Sup.bufpos + ((NI)1))]) == (NU8)(34))) goto LA12_;
			(*c_p0).Sup.bufpos += ((NI)1);
			getString__pureZparsecfg_u231(c_p0, tok_p1, NIM_TRUE);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA10_;
LA12_: ;
		{
			getSymbol__pureZparsecfg_u266(c_p0, tok_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA10_: ;
	}
	break;
	case 91:
	{
		(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)5);
		(*c_p0).Sup.bufpos += ((NI)1);
		eqsink___system_u2696((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18);
	}
	break;
	case 93:
	{
		(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)6);
		(*c_p0).Sup.bufpos += ((NI)1);
		eqsink___system_u2696((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_20);
	}
	break;
	case 34:
	{
		getString__pureZparsecfg_u231(c_p0, tok_p1, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case 0:
	{
		(*tok_p1).kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)1);
		eqsink___system_u2696((&(*tok_p1).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22);
	}
	break;
	default:
	{
		getSymbol__pureZparsecfg_u266(c_p0, tok_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* input_p1, NimStringV2 filename_p2, NI lineOffset_p3) {
	tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	open__pureZlexbase_u130(&c_p0->Sup, input_p1, ((NI)8192), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqsink___system_u2696((&(*c_p0).filename), filename_p2);
	eqwasMoved___system_u2687((&filename_p2));
	(*c_p0).tok.kind = ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0);
	eqsink___system_u2696((&(*c_p0).tok.literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6);
	(*c_p0).Sup.lineNumber += lineOffset_p3;
	T2_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
	T2_ = c_p0;
	rawGetTok__pureZparsecfg_u45(T2_, (&(*c_p0).tok));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (filename_p2.p && !(filename_p2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(filename_p2.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u394)(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)0):
	{
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)1):
	{
		if ((*dest_p0)._kind_2.section.p && !((*dest_p0)._kind_2.section.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_2.section.p);
}
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)2):
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)3):
	{
		if ((*dest_p0)._kind_3.key.p && !((*dest_p0)._kind_3.key.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_3.key.p);
}
		if ((*dest_p0)._kind_3.value.p && !((*dest_p0)._kind_3.value.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_3.value.p);
}
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4):
	{
		if ((*dest_p0)._kind_4.msg.p && !((*dest_p0)._kind_4.msg.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_4.msg.p);
}
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecfg_u8575)(void* dest_p0) {
	eqdestroy___pureZparsecfg_u394(((tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZparsecfg_u403)(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* dest_p0, tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* src_p1) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)0):
	{
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)1):
	{
		if ((*dest_p0)._kind_2.section.p && !((*dest_p0)._kind_2.section.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_2.section.p);
}
		(*dest_p0)._kind_2.section.len = 0; (*dest_p0)._kind_2.section.p = NIM_NIL;
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)2):
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)3):
	{
		if ((*dest_p0)._kind_3.key.p && !((*dest_p0)._kind_3.key.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_3.key.p);
}
		(*dest_p0)._kind_3.key.len = 0; (*dest_p0)._kind_3.key.p = NIM_NIL;
		if ((*dest_p0)._kind_3.value.p && !((*dest_p0)._kind_3.value.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_3.value.p);
}
		(*dest_p0)._kind_3.value.len = 0; (*dest_p0)._kind_3.value.p = NIM_NIL;
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4):
	{
		if ((*dest_p0)._kind_4.msg.p && !((*dest_p0)._kind_4.msg.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_4.msg.p);
}
		(*dest_p0)._kind_4.msg.len = 0; (*dest_p0)._kind_4.msg.p = NIM_NIL;
	}
	break;
	default: __builtin_unreachable();
	}
	(*dest_p0).kind = 0;
	(*dest_p0).kind = (*src_p1).kind;
	switch ((*dest_p0).kind) {
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)0):
	{
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)1):
	{
		(*dest_p0)._kind_2.section = (*src_p1)._kind_2.section;
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)2):
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)3):
	{
		(*dest_p0)._kind_3.key = (*src_p1)._kind_3.key;
		(*dest_p0)._kind_3.value = (*src_p1)._kind_3.value;
	}
	break;
	case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4):
	{
		(*dest_p0)._kind_4.msg = (*src_p1)._kind_4.msg;
	}
	break;
	default: __builtin_unreachable();
	}
	(*dest_p0).Sup.m_type = (*src_p1).Sup.m_type;
}
N_LIB_PRIVATE N_NIMCALL(NI, npcgetLine)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0) {
	NI result;
	result = (*c_p0).Sup.lineNumber;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npcgetColumn)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = getColNumber__pureZlexbase_u145((&(*c_p0).Sup), (*c_p0).Sup.bufpos);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, npcerrorStr)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, NimStringV2 msg_p1) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T2_;
	NI T3_;
	NI T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	T2_[0] = (*c_p0).filename;
	T3_ = (NI)0;
	T3_ = npcgetLine(c_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD_ = dollar___systemZdollars_u8(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1] = colontmpD_;
	T4_ = (NI)0;
	T4_ = npcgetColumn(c_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = dollar___systemZdollars_u8(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2] = colontmpD__2;
	T2_[3] = msg_p1;
	result = nsuFormatOpenArray(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26, T2_, 4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (msg_p1.p && !(msg_p1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg_p1.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, getKeyValPair__pureZparsecfg_u351)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw kind_p1, tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA));
	(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
	{
		tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T7_;
		if (!((*c_p0).tok.kind == ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)2))) goto LA3_;
		switch (kind_p1) {
		case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)3):
		case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)2):
		{
			tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw colontmpD_;
			colontmpD_ = (tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)0;
			(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
			colontmpD_ = kind_p1;
			(*Result).kind = colontmpD_;
			(*Result)._kind_3.key = (*c_p0).tok.literal;
			eqwasMoved___system_u2687((&(*c_p0).tok.literal));
			(*Result)._kind_3.value = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24;
		}
		break;
		default:
		{
			nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA));
			(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
		}
		break;
		}
		T7_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
		T7_ = c_p0;
		rawGetTok__pureZparsecfg_u45(T7_, (&(*c_p0).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T12_;
			tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T20_;
			if (!((*c_p0).tok.kind == ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)3) || (*c_p0).tok.kind == ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)4))) goto LA10_;
			T12_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
			T12_ = c_p0;
			rawGetTok__pureZparsecfg_u45(T12_, (&(*c_p0).tok));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				if (!((*c_p0).tok.kind == ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)2))) goto LA15_;
				eqcopy___system_u2690((&(*Result)._kind_3.value), (*c_p0).tok.literal);
			}
			goto LA13_;
LA15_: ;
			{
				tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA T18_;
				NimStringV2 T19_;
				T18_.Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
				T18_.Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
				T18_.kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4);
				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = rawNewString((*c_p0).tok.literal.len + 28);
appendString((&T19_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28);
appendString((&T19_), (*c_p0).tok.literal);
				T18_._kind_4.msg = npcerrorStr((&(*c_p0)), T19_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				eqsink___pureZparsecfg_u403(Result, (&T18_));
			}
LA13_: ;
			T20_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
			T20_ = c_p0;
			rawGetTok__pureZparsecfg_u45(T20_, (&(*c_p0).tok));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA10_: ;
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 T22_;
		NimStringV2 T23_;
		tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T24_;
		(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
		(*Result).kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4);
		T22_.len = 0; T22_.p = NIM_NIL;
		T22_ = rawNewString((*c_p0).tok.literal.len + 28);
appendString((&T22_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_29);
appendString((&T22_), (*c_p0).tok.literal);
		T23_.len = 0; T23_.p = NIM_NIL;
		T23_ = npcerrorStr((&(*c_p0)), T22_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T23_); goto BeforeRet_;}
		(*Result)._kind_4.msg = T23_;
		T24_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
		T24_ = c_p0;
		rawGetTok__pureZparsecfg_u45(T24_, (&(*c_p0).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0, tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA* Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA));
	(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
	switch ((*c_p0).tok.kind) {
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)1):
	{
		nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA));
		(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
		(*Result).kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)0);
	}
	break;
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)7):
	{
		tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T3_;
		T3_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
		T3_ = c_p0;
		rawGetTok__pureZparsecfg_u45(T3_, (&(*c_p0).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		getKeyValPair__pureZparsecfg_u351(c_p0, ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)3), Result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)2):
	{
		getKeyValPair__pureZparsecfg_u351(c_p0, ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)2), Result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)5):
	{
		tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T6_;
		tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T14_;
		T6_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
		T6_ = c_p0;
		rawGetTok__pureZparsecfg_u45(T6_, (&(*c_p0).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!((*c_p0).tok.kind == ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)2))) goto LA9_;
			(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
			(*Result).kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)1);
			(*Result)._kind_2.section = (*c_p0).tok.literal;
			eqwasMoved___system_u2687((&(*c_p0).tok.literal));
		}
		goto LA7_;
LA9_: ;
		{
			NimStringV2 T12_;
			NimStringV2 T13_;
			(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
			(*Result).kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4);
			T12_.len = 0; T12_.p = NIM_NIL;
			T12_ = rawNewString((*c_p0).tok.literal.len + 28);
appendString((&T12_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_30);
appendString((&T12_), (*c_p0).tok.literal);
			T13_.len = 0; T13_.p = NIM_NIL;
			T13_ = npcerrorStr((&(*c_p0)), T12_);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T13_); goto BeforeRet_;}
			(*Result)._kind_4.msg = T13_;
		}
LA7_: ;
		T14_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
		T14_ = c_p0;
		rawGetTok__pureZparsecfg_u45(T14_, (&(*c_p0).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T19_;
			if (!((*c_p0).tok.kind == ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)6))) goto LA17_;
			T19_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
			T19_ = c_p0;
			rawGetTok__pureZparsecfg_u45(T19_, (&(*c_p0).tok));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA15_;
LA17_: ;
		{
			tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA T21_;
			NimStringV2 T22_;
			T21_.Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
			T21_.Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
			T21_.kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4);
			T22_.len = 0; T22_.p = NIM_NIL;
			T22_ = rawNewString((*c_p0).tok.literal.len + 25);
appendString((&T22_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_32);
appendString((&T22_), (*c_p0).tok.literal);
			T21_._kind_4.msg = npcerrorStr((&(*c_p0)), T22_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqsink___pureZparsecfg_u403(Result, (&T21_));
		}
LA15_: ;
	}
	break;
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)0):
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)3):
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)4):
	case ((tyEnum_TokKind__K8R6a5CiSlgXUqpSbYrJww)6):
	{
		NimStringV2 T24_;
		NimStringV2 T25_;
		tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* T26_;
		(*Result).Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
		(*Result).kind = ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4);
		T24_.len = 0; T24_.p = NIM_NIL;
		T24_ = rawNewString((*c_p0).tok.literal.len + 15);
appendString((&T24_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34);
appendString((&T24_), (*c_p0).tok.literal);
		T25_.len = 0; T25_.p = NIM_NIL;
		T25_ = npcerrorStr((&(*c_p0)), T24_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T25_); goto BeforeRet_;}
		(*Result)._kind_4.msg = T25_;
		T26_ = (tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw*)0;
		T26_ = c_p0;
		rawGetTok__pureZparsecfg_u45(T26_, (&(*c_p0).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw* c_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	close__pureZlexbase_u14(&c_p0->Sup);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g*, loadConfig__pureZparsecfg_u950)(tyObject_StreamObj__bDd24In9b3VuDv2QPQULZmA* stream_p0, NimStringV2 filename_p1) {
	tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* result;
	tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* dict;
	NimStringV2 curSection;
	tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw p;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	dict = NIM_NIL;
	curSection.len = 0; curSection.p = NIM_NIL;
	nimZeroMem((void*)(&p), sizeof(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw));
	p.Sup.Sup.m_type = (&NTIv2__RgEQOWxkmjjaWAmIB5Rndw_);
	dict = newOrderedTable__pureZparsecfg_u487(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	curSection = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4;
	nimZeroMem((void*)(&p), sizeof(tyObject_CfgParser__RgEQOWxkmjjaWAmIB5Rndw));
	p.Sup.Sup.m_type = (&NTIv2__RgEQOWxkmjjaWAmIB5Rndw_);
	blitTmp = filename_p1;
	eqwasMoved___system_u2687((&filename_p1));
	npcopen((&p), stream_p0, blitTmp, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		while (1) {
			tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA e;
			nimZeroMem((void*)(&e), sizeof(tyObject_CfgEvent__5gHqZLMsbl9b9aqqV4YtopsA));
			e.Sup.m_type = (&NTIv2__5gHqZLMsbl9b9aqqV4YtopsA_);
			npcnext((&p), (&e));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			switch (e.kind) {
			case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)0):
			{
				eqdestroy___pureZparsecfg_u394((&e));
				goto LA2;
			}
			break;
			case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)1):
			{
				eqsink___system_u2696((&curSection), e._kind_2.section);
				eqwasMoved___system_u2687((&e._kind_2.section));
			}
			break;
			case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)2):
			{
				tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* t;
				NimStringV2 T15_;
				NimStringV2 blitTmp_2;
				tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* blitTmp_3;
				t = NIM_NIL;
				t = newOrderedTable__pureZparsecfg_u1001(((NI)32));
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				{
					NIM_BOOL T11_;
					tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg** T14_;
					T11_ = (NIM_BOOL)0;
					T11_ = hasKey__pureZparsecfg_u1145(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					if (!T11_) goto LA12_;
					T14_ = (tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg**)0;
					T14_ = X5BX5D___pureZparsecfg_u1533(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					eqcopy___pureZparsecfg_u1089(&t, (*T14_));
				}
LA12_: ;
				T15_.len = 0; T15_.p = NIM_NIL;
				T15_ = e._kind_3.key;
				blitTmp_2 = e._kind_3.value;
				eqwasMoved___system_u2687((&e._kind_3.value));
				X5BX5Deq___pureZparsecfg_u1959(t, T15_, blitTmp_2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				blitTmp_3 = t;
				eqwasMoved___pureZparsecfg_u1083(&t);
				X5BX5Deq___pureZparsecfg_u3500(dict, curSection, blitTmp_3);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				{
					LA8_:;
				}
				{
					eqdestroy___pureZparsecfg_u1086(t);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			}
			break;
			case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)3):
			{
				tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* c;
				NimStringV2 colontmpD_;
				NimStringV2 T26_;
				NimStringV2 T27_;
				NimStringV2 blitTmp_4;
				tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg* blitTmp_5;
				c = NIM_NIL;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				c = newOrderedTable__pureZparsecfg_u1001(((NI)32));
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				{
					NIM_BOOL T22_;
					tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg** T25_;
					T22_ = (NIM_BOOL)0;
					T22_ = hasKey__pureZparsecfg_u1145(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
					if (!T22_) goto LA23_;
					T25_ = (tyObject_OrderedTable__fs5g7dbjoREL69c4PiITlBg**)0;
					T25_ = X5BX5D___pureZparsecfg_u1533(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
					eqcopy___pureZparsecfg_u1089(&c, (*T25_));
				}
LA23_: ;
				T26_.len = 0; T26_.p = NIM_NIL;
				T26_ = rawNewString(e._kind_3.key.len + 2);
appendString((&T26_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_35);
appendString((&T26_), e._kind_3.key);
				colontmpD_ = T26_;
				T27_.len = 0; T27_.p = NIM_NIL;
				T27_ = colontmpD_;
				blitTmp_4 = e._kind_3.value;
				eqwasMoved___system_u2687((&e._kind_3.value));
				X5BX5Deq___pureZparsecfg_u1959(c, T27_, blitTmp_4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				blitTmp_5 = c;
				eqwasMoved___pureZparsecfg_u1083(&c);
				X5BX5Deq___pureZparsecfg_u3500(dict, curSection, blitTmp_5);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				{
					LA19_:;
				}
				{
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					eqdestroy___pureZparsecfg_u1086(c);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			}
			break;
			case ((tyEnum_CfgEventKind__9cv44ijdSAm50pnakLtqOOw)4):
			{
				eqdestroy___pureZparsecfg_u394((&e));
				goto LA2;
			}
			break;
			default: __builtin_unreachable();
			}
			{
				LA4_:;
			}
			{
				eqdestroy___pureZparsecfg_u394((&e));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA2: ;
	npcclose((&p));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = dict;
	eqwasMoved___pureZparsecfg_u925(&dict);
	{
		LA1_:;
	}
	{
		if (filename_p1.p && !(filename_p1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(filename_p1.p);
}
		eqdestroy___pureZparsecfg_u61((&p));
		if (curSection.p && !(curSection.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(curSection.p);
}
		eqdestroy___pureZparsecfg_u928(dict);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g*, loadConfig__pureZparsecfg_u4987)(NimStringV2 filename_p0) {
	tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* result;
	tyObject_FileStreamObj__5DpayuUADAWFvqmaNzmWQQ* fileStream;
	FILE* file;
	NimStringV2 blitTmp;
NIM_BOOL oldNimErrFin2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	fileStream = NIM_NIL;
	file = open__stdZsyncio_u484(filename_p0, ((tyEnum_FileMode__NOotkCEDdzClfG8nOJdANg)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	fileStream = newFileStream__pureZstreams_u1185(file);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	blitTmp = filename_p0;
	eqwasMoved___system_u2687((&filename_p0));
	result = loadConfig__pureZparsecfg_u950(&fileStream->Sup, blitTmp);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	{
		LA2_:;
	}
	{
		oldNimErrFin2_ = *nimErr_; *nimErr_ = NIM_FALSE;
		close__pureZstreams_u57(&fileStream->Sup);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		*nimErr_ = oldNimErrFin2_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (filename_p0.p && !(filename_p0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(filename_p0.p);
}
		eqdestroy___pureZstreams_u1093(fileStream);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g*, newConfig__pureZparsecfg_u467)(void) {
	tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = newOrderedTable__pureZparsecfg_u487(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
