/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@spure@smath.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@spure@smath.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u255)(NI x_p0) {
	NI result;
	result = (NI)(x_p0 - ((NI)1));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)16))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)8))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)4))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)2))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)1))));
	result += (NI)(((NI)1) + (x_p0 <= ((NI)0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, floorMod__pkgZnicoZbackendsZsdl2_u817)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)(x_p0 % y_p1);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (((NI)0) < result);
		if (!(T4_)) goto LA5_;
		T4_ = (y_p1 < ((NI)0));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = (result < ((NI)0));
		if (!(T7_)) goto LA8_;
		T7_ = (((NI)0) < y_p1);
LA8_: ;
		T3_ = T7_;
LA6_: ;
		if (!T3_) goto LA9_;
		result += y_p1;
	}
LA9_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, floorDiv__pureZtimes_u302)(NI64 x_p0, NI64 y_p1) {
	NI64 result;
	NI64 r;
	result = (NI64)(x_p0 / y_p1);
	r = (NI64)(x_p0 % y_p1);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (IL64(0) < r);
		if (!(T4_)) goto LA5_;
		T4_ = (y_p1 < IL64(0));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = (r < IL64(0));
		if (!(T7_)) goto LA8_;
		T7_ = (IL64(0) < y_p1);
LA8_: ;
		T3_ = T7_;
LA6_: ;
		if (!T3_) goto LA9_;
		result -= ((NI)1);
	}
LA9_: ;
	return result;
}
