/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snimPNG-0.3.6-35de54ccffac88f3bfae87faddce507bdebeaae1@snimPNG@snimz.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snimPNG-0.3.6-35de54ccffac88f3bfae87faddce507bdebeaae1@snimPNG@snimz.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw;
typedef struct tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA;
typedef struct tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug tySequence__PclZllI1Ry7MX4uStk4Jug;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content tySequence__PclZllI1Ry7MX4uStk4Jug_Content;
typedef struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg;
typedef struct tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ;
typedef struct tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw;
typedef struct tyTuple__KKQKvM3dsxdtYGn9cLuLUWA tyTuple__KKQKvM3dsxdtYGn9cLuLUWA;
typedef struct tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw;
struct tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw {
	NI bitpointer;
	NimStringV2 data;
	NI databitlen;
};
typedef NU8 tyEnum_nzStreamMode__ebRRaj8yuuWem9aynE7njsg;
struct tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA {
	tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw btype;
	NIM_BOOL use_lz77;
	NI windowsize;
	NI minmatch;
	NI nicematch;
	NIM_BOOL lazymatching;
	tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw bits;
	NimStringV2 data;
	tyEnum_nzStreamMode__ebRRaj8yuuWem9aynE7njsg mode;
	NIM_BOOL ignoreAdler32;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug {
  NI len; tySequence__PclZllI1Ry7MX4uStk4Jug_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__PclZllI1Ry7MX4uStk4Jug trace;
	Exception* up;
};
struct tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA {
	Exception Sup;
};
struct tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA {
	tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA Sup;
};
struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw {
	NI len;
	NI cap;
	tyTuple__KKQKvM3dsxdtYGn9cLuLUWA* d;
};
struct tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ {
	tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg traceStack;
	tyObject_CellSeq__tZ9b9bi79clGwcRTCbEE09bqYw toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA {
	tySequence__qwqHTkRvwhrRyENtudHQ7g tree2d;
	tySequence__qwqHTkRvwhrRyENtudHQ7g tree1d;
	tySequence__qwqHTkRvwhrRyENtudHQ7g lengths;
	NI maxbitlen;
	NI numcodes;
};
typedef NI tyArray__OwOytieXUe4SPSxAsbsyEA[288];
typedef NI tyArray__OYqzMMAeF9bf1yDDPNUyDgg[32];
typedef NI tyArray__Ntm7bvhzwbE9b2CkMppjB8A[19];
typedef NI tyArray__s9azk0bXjkHhm7i19ceN41rg[29];
typedef NI tyArray__q0oNe3lONaLAJQxP9c7FTZA[30];
struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content { NI cap; tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA*, nzInit__pkgZnim807871Znimz_u2422)(tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw mode_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZnim807871Znimz_u2697)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u137)(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3528)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u74)(tySequence__PclZllI1Ry7MX4uStk4Jug dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZnim807871Znimz_u149)(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3019)(tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, readByte__pkgZnim807871Znimz_u1121)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, readInt32__pkgZnim807871Znimz_u2623)(NimStringV2 input_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8826)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, nzInflate__pkgZnim807871Znimz_u1426)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0);
static N_INLINE(NI, readBitFromStream__pkgZnim807871Znimz_u79)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0);
static N_INLINE(NI, readBit__pkgZnim807871Znimz_u65)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw s_p0);
N_LIB_PRIVATE N_NIMCALL(void, inflateNoCompression__pkgZnim807871Znimz_u1139)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readInt16__pkgZnim807871Znimz_u1097)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, getBytePosition__pkgZnim807871Znimz_u1118)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2441)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, inflateHuffmanBlock__pkgZnim807871Znimz_u1368)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0, NI blockType_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateFixed__pkgZnim807871Znimz_u1163)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_ll_p0, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_d_p1);
N_LIB_PRIVATE N_NIMCALL(void, generateFixedLitLenTree__pkgZnim807871Znimz_u1001)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0);
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0, NI* bitlen_p1, NI bitlen_p1Len_0, NI maxbitlen_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZcommon_u3238)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, at___pkgZnim807871Znimz_u418)(NI* a_p0, NI a_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths2__pkgZnim807871Znimz_u305)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, newSeq__pureZosproc_u364)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3229)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_make2DTree__pkgZnim807871Znimz_u195)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, newSeqUninit__pkgZnim807871Znimz_u218)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZbackendsZcommon_u3226)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, generateFixedDistanceTree__pkgZnim807871Znimz_u1062)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0);
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateDynamic__pkgZnim807871Znimz_u1182)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_ll_p1, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_d_p2);
N_LIB_PRIVATE N_NIMCALL(NI, readBitsFromStream__pkgZnim807871Znimz_u87)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, NI nbits_p1);
N_LIB_PRIVATE N_NIMCALL(NI, huffmanDecodeSymbol__pkgZnim807871Znimz_u1166)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* codetree_p1, NI inbitlength_p2);
N_LIB_PRIVATE N_NIMCALL(NI, readBitsSafe__pkgZnim807871Znimz_u110)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, NI nbits_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u1326)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* dest_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, nzAdler32__pkgZnim807871Znimz_u2549)(NU32 adler_p0, NimStringV2 data_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nzGetResult__pkgZnim807871Znimz_u2541)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u2448)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_;
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_3 = { 27 | NIM_STRLIT_FLAG, "size of zlib data too small" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_4 = {27, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_3};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_5 = { 33 | NIM_STRLIT_FLAG, "bit pointer will jump past memory" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_6 = {33, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_5};
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_7 = { 37 | NIM_STRLIT_FLAG, " zlib header must be a multiple of 31" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_8 = {37, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_7};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_9 = { 17 | NIM_STRLIT_FLAG, "invalid blockType" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_10 = {17, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_9};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_11 = {33, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_5};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_12 = { 35 | NIM_STRLIT_FLAG, "NLEN is not one\'s complement of LEN" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_13 = {35, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_12};
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_14 = { 31 | NIM_STRLIT_FLAG, "reading outside of input buffer" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_15 = {31, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_14};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_16 = { 14 | NIM_STRLIT_FLAG, "oversubscribed" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_17 = {14, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_16};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_18 = { 45 | NIM_STRLIT_FLAG, "the bit pointer is or will go past the memory" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_19 = {45, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_18};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_20 = {45, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_18};
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_21 = { 31 | NIM_STRLIT_FLAG, "can\'t repeat previous if i is 0" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_22 = {31, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_21};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_23 = { 29 | NIM_STRLIT_FLAG, "bit pointer jumps past memory" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_24 = {29, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_23};
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_25 = { 36 | NIM_STRLIT_FLAG, "i is larger than the amount of codes" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_26 = {36, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_25};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_27 = {36, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_25};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_28 = {36, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_25};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_29 = { 10 | NIM_STRLIT_FLAG, "no endcode" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_30 = {10, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_29};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_31 = { 26 | NIM_STRLIT_FLAG, "wrong jump outside of tree" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_32 = {26, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_31};
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_33 = { 38 | NIM_STRLIT_FLAG, "unexisting code, this can never happen" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_34 = {38, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_33};
static const struct {
  NI cap; NIM_CHAR data[52+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_35 = { 52 | NIM_STRLIT_FLAG, "the length of the end code 256 must be larger than 0" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_36 = {52, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_35};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_37 = {10, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_29};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_38 = {26, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_31};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_39 = { 44 | NIM_STRLIT_FLAG, "invalid distance code (30-31 are never used)" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_40 = {44, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_39};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_41 = { 26 | NIM_STRLIT_FLAG, "too long backward distance" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_42 = {26, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_41};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_43 = {10, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_29};
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_44 = {26, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_31};
static const struct {
  NI cap; NIM_CHAR data[50+1];
} TM__n9cknNhkm8Fa9boCSB3rtZeA_45 = { 50 | NIM_STRLIT_FLAG, "adler checksum not correct, data must be corrupted" };
static const NimStringV2 TM__n9cknNhkm8Fa9boCSB3rtZeA_46 = {50, (NimStrPayload*)&TM__n9cknNhkm8Fa9boCSB3rtZeA_45};
N_LIB_PRIVATE NIM_CONST tyArray__Ntm7bvhzwbE9b2CkMppjB8A CLCL_ORDER__pkgZnim807871Znimz_u11 = {((NI)16),
((NI)17),
((NI)18),
((NI)0),
((NI)8),
((NI)7),
((NI)9),
((NI)6),
((NI)10),
((NI)5),
((NI)11),
((NI)4),
((NI)12),
((NI)3),
((NI)13),
((NI)2),
((NI)14),
((NI)1),
((NI)15)}
;
N_LIB_PRIVATE NIM_CONST tyArray__s9azk0bXjkHhm7i19ceN41rg LENGTHBASE__pkgZnim807871Znimz_u7 = {((NI)3),
((NI)4),
((NI)5),
((NI)6),
((NI)7),
((NI)8),
((NI)9),
((NI)10),
((NI)11),
((NI)13),
((NI)15),
((NI)17),
((NI)19),
((NI)23),
((NI)27),
((NI)31),
((NI)35),
((NI)43),
((NI)51),
((NI)59),
((NI)67),
((NI)83),
((NI)99),
((NI)115),
((NI)131),
((NI)163),
((NI)195),
((NI)227),
((NI)258)}
;
N_LIB_PRIVATE NIM_CONST tyArray__s9azk0bXjkHhm7i19ceN41rg LENGTHEXTRA__pkgZnim807871Znimz_u8 = {((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)1),
((NI)1),
((NI)1),
((NI)1),
((NI)2),
((NI)2),
((NI)2),
((NI)2),
((NI)3),
((NI)3),
((NI)3),
((NI)3),
((NI)4),
((NI)4),
((NI)4),
((NI)4),
((NI)5),
((NI)5),
((NI)5),
((NI)5),
((NI)0)}
;
N_LIB_PRIVATE NIM_CONST tyArray__q0oNe3lONaLAJQxP9c7FTZA DISTANCEBASE__pkgZnim807871Znimz_u9 = {((NI)1),
((NI)2),
((NI)3),
((NI)4),
((NI)5),
((NI)7),
((NI)9),
((NI)13),
((NI)17),
((NI)25),
((NI)33),
((NI)49),
((NI)65),
((NI)97),
((NI)129),
((NI)193),
((NI)257),
((NI)385),
((NI)513),
((NI)769),
((NI)1025),
((NI)1537),
((NI)2049),
((NI)3073),
((NI)4097),
((NI)6145),
((NI)8193),
((NI)12289),
((NI)16385),
((NI)24577)}
;
N_LIB_PRIVATE NIM_CONST tyArray__q0oNe3lONaLAJQxP9c7FTZA DISTANCEEXTRA__pkgZnim807871Znimz_u10 = {((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)1),
((NI)1),
((NI)2),
((NI)2),
((NI)3),
((NI)3),
((NI)4),
((NI)4),
((NI)5),
((NI)5),
((NI)6),
((NI)6),
((NI)7),
((NI)7),
((NI)8),
((NI)8),
((NI)9),
((NI)9),
((NI)10),
((NI)10),
((NI)11),
((NI)11),
((NI)12),
((NI)12),
((NI)13),
((NI)13)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
static NIM_CONST NU32 TM__n9cknNhkm8Fa9boCSB3rtZeA_2[4] = {3701606400, 1285336064, 3171897600, 1566719744};
N_LIB_PRIVATE TNimTypeV2 NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_ = {.destructor = (void*)rttiDestroy__pkgZnim807871Znimz_u2697, .size = sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), .align = (NI16) NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), .depth = 3, .display = TM__n9cknNhkm8Fa9boCSB3rtZeA_2, .traceImpl = (void*)eqtrace___pkgZnim807871Znimz_u149, .flags = 0};
N_LIB_PRIVATE N_NIMCALL(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA*, nzInit__pkgZnim807871Znimz_u2422)(tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw mode_p0) {
	tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* result;
	tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw colontmpD_;
	tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* T1_;
	colontmpD_ = (tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA*) nimNewObj(sizeof(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA), NIM_ALIGNOF(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA));
	colontmpD_ = mode_p0;
	(*T1_).btype = colontmpD_;
	(*T1_).use_lz77 = NIM_TRUE;
	(*T1_).windowsize = ((NI)2048);
	(*T1_).minmatch = ((NI)3);
	(*T1_).nicematch = ((NI)128);
	(*T1_).lazymatching = NIM_TRUE;
	(*T1_).ignoreAdler32 = NIM_FALSE;
	result = T1_;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA*, nzInflateInit__pkgZnim807871Znimz_u2535)(NimStringV2 input_p0) {
	tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* result;
	tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nz = NIM_NIL;
	nz = nzInit__pkgZnim807871Znimz_u2422(((tyEnum_nzCompMode__vVpPk3tf1OrM7SlVChO9cpw)2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(((NI)5242880));
	eqsink___system_u2696((&(*nz).data), T1_);
	eqcopy___system_u2690((&(*nz).bits.data), input_p0);
	(*nz).bits.bitpointer = ((NI)0);
	(*nz).bits.databitlen = (NI)(input_p0.len * ((NI)8));
	(*nz).mode = ((tyEnum_nzStreamMode__ebRRaj8yuuWem9aynE7njsg)1);
	result = nz;
	if (input_p0.p && !(input_p0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(input_p0.p);
}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
		rememberCycle__system_u3528(result, cell, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u137)(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZnim807871Znimz_u2697)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pkgZnim807871Znimz_u137(((tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__gJgGhndQf4jMmiPOrKMxRg* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u3019(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len += ((NI)1);
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p;
	p = ((void**) (q_p0));
	{
		tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		j = ((tyObject_GcEnv__ya2EvOe4TJjBgsQr2pyzfQ*) (env_p1));
		add__system_u3011((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZnim807871Znimz_u149)(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, readByte__pkgZnim807871Znimz_u1121)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0) {
	NI result;
	NI p;
{	result = (NI)0;
	{
		while (1) {
			if (!!(((NI)((*s_p0).bitpointer & ((NI)7)) == ((NI)0)))) goto LA2;
			(*s_p0).bitpointer += ((NI)1);
		} LA2: ;
	}
	p = (NI)((*s_p0).bitpointer / ((NI)8));
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T7_;
		if (!((*s_p0).data.len <= (NI)(p + ((NI)1)))) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T7_).Sup.Sup.name = "NZError";
		(*T7_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_6;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "NZError", "readByte", "nimz.nim", 427);
goto BeforeRet_;
	}
LA5_: ;
	result = ((NU8)((*s_p0).data.p->data[p]));
	(*s_p0).bitpointer += ((NI)8);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, readInt32__pkgZnim807871Znimz_u2623)(NimStringV2 input_p0) {
	NU32 result;
	result = (NU32)((NU32)(((NU32) (((NU8)(input_p0.p->data[((NI)0)]))))) << (NU32)(((NI)24)));
	result += (NU32)((NU32)(((NU32) (((NU8)(input_p0.p->data[((NI)1)]))))) << (NU32)(((NI)16)));
	result += (NU32)((NU32)(((NU32) (((NU8)(input_p0.p->data[((NI)2)]))))) << (NU32)(((NI)8)));
	result += ((NU32) (((NU8)(input_p0.p->data[((NI)3)]))));
	return result;
}
static N_INLINE(NI, readBit__pkgZnim807871Znimz_u65)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw s_p0) {
	NI result;
	result = (NI)((NI)((NI32)(((NU8)(s_p0.data.p->data[(NI)((NI32)(s_p0.bitpointer) >> (NU32)(((NI)3)))]))) >> (NU32)((NI)(s_p0.bitpointer & ((NI)7)))) & ((NI)1));
	return result;
}
static N_INLINE(NI, readBitFromStream__pkgZnim807871Znimz_u79)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = readBit__pkgZnim807871Znimz_u65((*s_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*s_p0).bitpointer += ((NI)1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readInt16__pkgZnim807871Znimz_u1097)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0) {
	NI result;
	NI p;
{	result = (NI)0;
	{
		while (1) {
			if (!!(((NI)((*s_p0).bitpointer & ((NI)7)) == ((NI)0)))) goto LA2;
			(*s_p0).bitpointer += ((NI)1);
		} LA2: ;
	}
	p = (NI)((*s_p0).bitpointer / ((NI)8));
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T7_;
		if (!((*s_p0).data.len < (NI)(p + ((NI)2)))) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T7_).Sup.Sup.name = "NZError";
		(*T7_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_11;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "NZError", "readInt16", "nimz.nim", 417);
goto BeforeRet_;
	}
LA5_: ;
	result = (NI)(((NU8)((*s_p0).data.p->data[p])) + (NI)(((NI)256) * ((NU8)((*s_p0).data.p->data[(NI)(p + ((NI)1))]))));
	(*s_p0).bitpointer += ((NI)16);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getBytePosition__pkgZnim807871Znimz_u1118)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0) {
	NI result;
	result = (NI)((*s_p0).bitpointer / ((NI)8));
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2441(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, inflateNoCompression__pkgZnim807871Znimz_u1139)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0) {
	NI inlength;
	NI LEN;
	NI NLEN;
	NI p;
	NI pos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	inlength = (*nz_p0).bits.data.len;
	LEN = readInt16__pkgZnim807871Znimz_u1097((&(*nz_p0).bits));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	NLEN = readInt16__pkgZnim807871Znimz_u1097((&(*nz_p0).bits));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T5_;
		if (!!(((NI)(LEN + NLEN) == ((NI)65535)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T5_).Sup.Sup.name = "NZError";
		(*T5_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_13;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "NZError", "inflateNoCompression", "nimz.nim", 440);
goto BeforeRet_;
	}
LA3_: ;
	p = getBytePosition__pkgZnim807871Znimz_u1118((&(*nz_p0).bits));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T10_;
		if (!(inlength < (NI)(p + LEN))) goto LA8_;
		T10_ = NIM_NIL;
		T10_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T10_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T10_).Sup.Sup.name = "NZError";
		(*T10_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_15;
		(*T10_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T10_, "NZError", "inflateNoCompression", "nimz.nim", 445);
goto BeforeRet_;
	}
LA8_: ;
	pos = (*nz_p0).data.len;
	setLengthStrV2((&(*nz_p0).data), ((NI)(pos + LEN)));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(LEN - ((NI)1));
		res = ((NI)0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA13;
				i = ((NI) (res));
				nimPrepareStrMutationV2((&(*nz_p0).data));
				(*nz_p0).data.p->data[pos] = (*nz_p0).bits.data.p->data[p];
				pos += ((NI)1);
				p += ((NI)1);
				res += ((NI)1);
			} LA13: ;
		}
	}
	(*nz_p0).bits.bitpointer = (NI)(p * ((NI)8));
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths2__pkgZnim807871Znimz_u305)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g blcount;
	tySequence__qwqHTkRvwhrRyENtudHQ7g nextcode;
	tySequence__qwqHTkRvwhrRyENtudHQ7g T1_;
	blcount.len = 0; blcount.p = NIM_NIL;
	nextcode.len = 0; nextcode.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = newSeq__pureZosproc_u364(((*tree_p0).numcodes));
	eqsink___pkgZnicoZbackendsZcommon_u3238((&(*tree_p0).tree1d), T1_);
	blcount = newSeq__pureZosproc_u364(((NI)((*tree_p0).maxbitlen + ((NI)1))));
	nextcode = newSeq__pureZosproc_u364(((NI)((*tree_p0).maxbitlen + ((NI)1))));
	{
		NI* len;
		NI i;
		NI L;
		NI T3_;
		len = (NI*)0;
		i = ((NI)0);
		T3_ = (*tree_p0).lengths.len;
		L = T3_;
		{
			while (1) {
				if (!(i < L)) goto LA5;
				len = (&(*tree_p0).lengths.p->data[i]);
				blcount.p->data[(*len)] += ((NI)1);
				i += ((NI)1);
			} LA5: ;
		}
	}
	{
		NI bits;
		NI res;
		bits = (NI)0;
		res = ((NI)1);
		{
			while (1) {
				if (!(res <= (*tree_p0).maxbitlen)) goto LA8;
				bits = ((NI) (res));
				nextcode.p->data[bits] = (NI)((NU32)((NI)(nextcode.p->data[(NI)(bits - ((NI)1))] + blcount.p->data[(NI)(bits - ((NI)1))])) << (NU32)(((NI)1)));
				res += ((NI)1);
			} LA8: ;
		}
	}
	{
		NI n;
		NI colontmp_;
		NI res_2;
		n = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((*tree_p0).numcodes - ((NI)1));
		res_2 = ((NI)0);
		{
			while (1) {
				NI len_2;
				if (!(res_2 <= colontmp_)) goto LA11;
				n = ((NI) (res_2));
				len_2 = (*tree_p0).lengths.p->data[n];
				{
					if (!!((len_2 == ((NI)0)))) goto LA14_;
					(*tree_p0).tree1d.p->data[n] = nextcode.p->data[len_2];
					nextcode.p->data[len_2] += ((NI)1);
				}
LA14_: ;
				res_2 += ((NI)1);
			} LA11: ;
		}
	}
	eqdestroy___pkgZnicoZbackendsZcommon_u3229(nextcode);
	eqdestroy___pkgZnicoZbackendsZcommon_u3229(blcount);
}
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_make2DTree__pkgZnim807871Znimz_u195)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g resultX60gensym3_;
	NI nodefilled;
	NI treepos;
	NI newLenX60gensym3_;
	tySequence__qwqHTkRvwhrRyENtudHQ7g T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	resultX60gensym3_.len = 0; resultX60gensym3_.p = NIM_NIL;
	nodefilled = ((NI)0);
	treepos = ((NI)0);
	newLenX60gensym3_ = (NI)((*tree_p0).numcodes * ((NI)2));
	resultX60gensym3_ = newSeqUninit__pkgZnim807871Znimz_u218((newLenX60gensym3_));
	{
		NI iX60gensym3_;
		NI i;
		iX60gensym3_ = (NI)0;
		i = ((NI)0);
		{
			while (1) {
				if (!(i < newLenX60gensym3_)) goto LA4;
				iX60gensym3_ = i;
				resultX60gensym3_.p->data[iX60gensym3_] = ((NI)32767);
				i += ((NI)1);
			} LA4: ;
		}
	}
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_ = resultX60gensym3_;
	eqwasMoved___pkgZnicoZbackendsZcommon_u3226((&resultX60gensym3_));
	eqsink___pkgZnicoZbackendsZcommon_u3238((&(*tree_p0).tree2d), T5_);
	{
		NI n;
		NI colontmp_;
		NI res;
		n = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((*tree_p0).numcodes - ((NI)1));
		res = ((NI)0);
		{
			while (1) {
				NI len;
				if (!(res <= colontmp_)) goto LA8;
				n = ((NI) (res));
				len = (*tree_p0).lengths.p->data[n];
				{
					NI i_2;
					NI colontmp__2;
					NI res_2;
					i_2 = (NI)0;
					colontmp__2 = (NI)0;
					colontmp__2 = (NI)(len - ((NI)1));
					res_2 = ((NI)0);
					{
						while (1) {
							if (!(res_2 <= colontmp__2)) goto LA11;
							i_2 = ((NI) (res_2));
							{
								NI bit;
								NI branch;
								bit = (NI)((NI)((NI32)((*tree_p0).tree1d.p->data[n]) >> (NU32)((NI)((NI)(len - i_2) - ((NI)1)))) & ((NI)1));
								branch = (NI)((NI)(((NI)2) * treepos) + bit);
								{
									NIM_BOOL T15_;
									tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T19_;
									T15_ = (NIM_BOOL)0;
									T15_ = (((NI)2147483647) < treepos);
									if (T15_) goto LA16_;
									T15_ = ((*tree_p0).numcodes < (NI)(treepos + ((NI)2)));
LA16_: ;
									if (!T15_) goto LA17_;
									T19_ = NIM_NIL;
									T19_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
									(*T19_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
									(*T19_).Sup.Sup.name = "NZError";
									(*T19_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_17;
									(*T19_).Sup.Sup.parent = ((Exception*) NIM_NIL);
									raiseExceptionEx((Exception*)T19_, "NZError", "HuffmanTree_make2DTree", "nimz.nim", 188);
goto LA1_;
								}
LA17_: ;
								{
									if (!!(((*tree_p0).tree2d.p->data[branch] == ((NI)32767)))) goto LA22_;
									treepos = (NI)((*tree_p0).tree2d.p->data[branch] - (*tree_p0).numcodes);
									goto LA12;
								}
LA22_: ;
								{
									if (!((NI)(i_2 + ((NI)1)) < len)) goto LA26_;
									nodefilled += ((NI)1);
									(*tree_p0).tree2d.p->data[branch] = (NI)(nodefilled + (*tree_p0).numcodes);
									treepos = nodefilled;
									goto LA12;
								}
LA26_: ;
								(*tree_p0).tree2d.p->data[branch] = n;
								treepos = ((NI)0);
							} LA12: ;
							res_2 += ((NI)1);
						} LA11: ;
					}
				}
				res += ((NI)1);
			} LA8: ;
		}
	}
	{
		NI iX60gensym9_;
		NI colontmp__3;
		NI T29_;
		NI res_3;
		iX60gensym9_ = (NI)0;
		colontmp__3 = (NI)0;
		T29_ = ((*tree_p0).tree2d.len-1);
		colontmp__3 = T29_;
		res_3 = ((NI)0);
		{
			while (1) {
				NI colontmpD_;
				NI colontmpD__2;
				NI it;
				if (!(res_3 <= colontmp__3)) goto LA31;
				colontmpD_ = (NI)0;
				colontmpD__2 = (NI)0;
				iX60gensym9_ = ((NI) (res_3));
				it = (*tree_p0).tree2d.p->data[iX60gensym9_];
				{
					if (!(it == ((NI)32767))) goto LA34_;
					colontmpD_ = ((NI)0);
					(*tree_p0).tree2d.p->data[iX60gensym9_] = colontmpD_;
				}
				goto LA32_;
LA34_: ;
				{
					colontmpD__2 = it;
					(*tree_p0).tree2d.p->data[iX60gensym9_] = colontmpD__2;
				}
LA32_: ;
				res_3 += ((NI)1);
			} LA31: ;
		}
	}
	{
		LA1_:;
	}
	{
		eqdestroy___pkgZnicoZbackendsZcommon_u3229(resultX60gensym3_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0, NI* bitlen_p1, NI bitlen_p1Len_0, NI maxbitlen_p2) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = at___pkgZnim807871Znimz_u418(bitlen_p1, bitlen_p1Len_0);
	eqsink___pkgZnicoZbackendsZcommon_u3238((&(*tree_p0).lengths), T1_);
	(*tree_p0).numcodes = bitlen_p1Len_0;
	(*tree_p0).maxbitlen = maxbitlen_p2;
	HuffmanTree_makeFromLengths2__pkgZnim807871Znimz_u305(tree_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	HuffmanTree_make2DTree__pkgZnim807871Znimz_u195(tree_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, generateFixedLitLenTree__pkgZnim807871Znimz_u1001)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0) {
	tyArray__OwOytieXUe4SPSxAsbsyEA bitlen;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)bitlen, sizeof(tyArray__OwOytieXUe4SPSxAsbsyEA));
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI)0);
		{
			while (1) {
				if (!(res <= ((NI)143))) goto LA3;
				i = ((NI) (res));
				bitlen[(i)- 0] = ((NI)8);
				res += ((NI)1);
			} LA3: ;
		}
	}
	{
		NI i_2;
		NI res_2;
		i_2 = (NI)0;
		res_2 = ((NI)144);
		{
			while (1) {
				if (!(res_2 <= ((NI)255))) goto LA6;
				i_2 = ((NI) (res_2));
				bitlen[(i_2)- 0] = ((NI)9);
				res_2 += ((NI)1);
			} LA6: ;
		}
	}
	{
		NI i_3;
		NI res_3;
		i_3 = (NI)0;
		res_3 = ((NI)256);
		{
			while (1) {
				if (!(res_3 <= ((NI)279))) goto LA9;
				i_3 = ((NI) (res_3));
				bitlen[(i_3)- 0] = ((NI)7);
				res_3 += ((NI)1);
			} LA9: ;
		}
	}
	{
		NI i_4;
		NI res_4;
		i_4 = (NI)0;
		res_4 = ((NI)280);
		{
			while (1) {
				if (!(res_4 <= ((NI)287))) goto LA12;
				i_4 = ((NI) (res_4));
				bitlen[(i_4)- 0] = ((NI)8);
				res_4 += ((NI)1);
			} LA12: ;
		}
	}
	HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414(tree_p0, bitlen, 288, ((NI)15));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, generateFixedDistanceTree__pkgZnim807871Znimz_u1062)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_p0) {
	tyArray__OYqzMMAeF9bf1yDDPNUyDgg bitlen;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)bitlen, sizeof(tyArray__OYqzMMAeF9bf1yDDPNUyDgg));
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI)0);
		{
			while (1) {
				if (!(res <= ((NI)31))) goto LA3;
				i = ((NI) (res));
				bitlen[(i)- 0] = ((NI)5);
				res += ((NI)1);
			} LA3: ;
		}
	}
	HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414(tree_p0, bitlen, 32, ((NI)15));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateFixed__pkgZnim807871Znimz_u1163)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_ll_p0, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_d_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	generateFixedLitLenTree__pkgZnim807871Znimz_u1001(tree_ll_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	generateFixedDistanceTree__pkgZnim807871Znimz_u1062(tree_d_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, readBitsFromStream__pkgZnim807871Znimz_u87)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, NI nbits_p1) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(nbits_p1 - ((NI)1));
		res = ((NI)0);
		{
			while (1) {
				NI T4_;
				if (!(res <= colontmp_)) goto LA3;
				i = ((NI) (res));
				T4_ = (NI)0;
				T4_ = readBit__pkgZnim807871Znimz_u65((*s_p0));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result += (NI)((NU32)(T4_) << (NU32)(i));
				(*s_p0).bitpointer += ((NI)1);
				res += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, huffmanDecodeSymbol__pkgZnim807871Znimz_u1166)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* codetree_p1, NI inbitlength_p2) {
	NI result;
	NI treepos;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	treepos = ((NI)0);
	{
		while (1) {
			NI ct;
			NI T7_;
			{
				if (!(inbitlength_p2 <= (*s_p0).bitpointer)) goto LA5_;
				result = ((NI)-1);
				goto BeforeRet_;
			}
LA5_: ;
			T7_ = (NI)0;
			T7_ = readBit__pkgZnim807871Znimz_u65((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			ct = (*codetree_p1).tree2d.p->data[(NI)((NI)((NU32)(treepos) << (NU32)(((NI)1))) + T7_)];
			(*s_p0).bitpointer += ((NI)1);
			{
				if (!(ct < (*codetree_p1).numcodes)) goto LA10_;
				result = ct;
				goto BeforeRet_;
			}
			goto LA8_;
LA10_: ;
			{
				treepos = (NI)(ct - (*codetree_p1).numcodes);
			}
LA8_: ;
			{
				if (!((*codetree_p1).numcodes <= treepos)) goto LA15_;
				result = ((NI)-1);
				goto BeforeRet_;
			}
LA15_: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readBitsSafe__pkgZnim807871Znimz_u110)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, NI nbits_p1) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T5_;
		if (!((*s_p0).databitlen < (NI)((*s_p0).bitpointer + nbits_p1))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T5_).Sup.Sup.name = "NZError";
		(*T5_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_24;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "NZError", "readBitsSafe", "nimz.nim", 158);
goto BeforeRet_;
	}
LA3_: ;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(nbits_p1 - ((NI)1));
		res = ((NI)0);
		{
			while (1) {
				NI T9_;
				if (!(res <= colontmp_)) goto LA8;
				i = ((NI) (res));
				T9_ = (NI)0;
				T9_ = readBit__pkgZnim807871Znimz_u65((*s_p0));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result += (NI)((NU32)(T9_) << (NU32)(i));
				(*s_p0).bitpointer += ((NI)1);
				res += ((NI)1);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u1326)(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* dest_p0) {
	eqdestroy___pkgZnicoZbackendsZcommon_u3229((*dest_p0).tree2d);
	eqdestroy___pkgZnicoZbackendsZcommon_u3229((*dest_p0).tree1d);
	eqdestroy___pkgZnicoZbackendsZcommon_u3229((*dest_p0).lengths);
}
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateDynamic__pkgZnim807871Znimz_u1182)(tyObject_BitStream__CeaJ3dkIKaVmiDy9bLK7YCw* s_p0, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_ll_p1, tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA* tree_d_p2) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g bitlen_ll;
	tySequence__qwqHTkRvwhrRyENtudHQ7g bitlen_d;
	tySequence__qwqHTkRvwhrRyENtudHQ7g bitlen_cl;
	tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA tree_cl;
	NI inlength;
	NI inbitlength;
	NI HLIT;
	NI T7_;
	NI HDIST;
	NI T8_;
	NI HCLEN;
	NI T9_;
	NI i_2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	bitlen_ll.len = 0; bitlen_ll.p = NIM_NIL;
	bitlen_d.len = 0; bitlen_d.p = NIM_NIL;
	bitlen_cl.len = 0; bitlen_cl.p = NIM_NIL;
	nimZeroMem((void*)(&tree_cl), sizeof(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA));
	inlength = (*s_p0).data.len;
	inbitlength = (NI)(inlength * ((NI)8));
	bitlen_ll = newSeq__pureZosproc_u364(((NI)288));
	bitlen_d = newSeq__pureZosproc_u364(((NI)32));
	bitlen_cl = newSeq__pureZosproc_u364(((NI)19));
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T6_;
		if (!(inbitlength < (NI)((*s_p0).bitpointer + ((NI)14)))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T6_).Sup.Sup.name = "NZError";
		(*T6_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_19;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "NZError", "getTreeInflateDynamic", "nimz.nim", 502);
goto LA1_;
	}
LA4_: ;
	T7_ = (NI)0;
	T7_ = readBitsFromStream__pkgZnim807871Znimz_u87(s_p0, ((NI)5));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	HLIT = (NI)(T7_ + ((NI)257));
	T8_ = (NI)0;
	T8_ = readBitsFromStream__pkgZnim807871Znimz_u87(s_p0, ((NI)5));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	HDIST = (NI)(T8_ + ((NI)1));
	T9_ = (NI)0;
	T9_ = readBitsFromStream__pkgZnim807871Znimz_u87(s_p0, ((NI)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	HCLEN = (NI)(T9_ + ((NI)4));
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T14_;
		if (!(inbitlength < (NI)((*s_p0).bitpointer + (NI)(HCLEN * ((NI)3))))) goto LA12_;
		T14_ = NIM_NIL;
		T14_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T14_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T14_).Sup.Sup.name = "NZError";
		(*T14_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_20;
		(*T14_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T14_, "NZError", "getTreeInflateDynamic", "nimz.nim", 516);
goto LA1_;
	}
LA12_: ;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI)0);
		{
			while (1) {
				if (!(res <= ((NI)18))) goto LA17;
				i = ((NI) (res));
				{
					NI T22_;
					if (!(i < HCLEN)) goto LA20_;
					T22_ = (NI)0;
					T22_ = readBitsFromStream__pkgZnim807871Znimz_u87(s_p0, ((NI)3));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					bitlen_cl.p->data[CLCL_ORDER__pkgZnim807871Znimz_u11[(i)- 0]] = T22_;
				}
				goto LA18_;
LA20_: ;
				{
					bitlen_cl.p->data[CLCL_ORDER__pkgZnim807871Znimz_u11[(i)- 0]] = ((NI)0);
				}
LA18_: ;
				res += ((NI)1);
			} LA17: ;
		}
	}
	HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414((&tree_cl), ((bitlen_cl).p) ? (bitlen_cl.p->data) : NIM_NIL, bitlen_cl.len, ((NI)7));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	i_2 = ((NI)0);
	{
		while (1) {
			NI code;
			if (!(i_2 < (NI)(HLIT + HDIST))) goto LA25;
			code = huffmanDecodeSymbol__pkgZnim807871Znimz_u1166(s_p0, (&tree_cl), inbitlength);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				if (!(code <= ((NI)15))) goto LA28_;
				{
					if (!(i_2 < HLIT)) goto LA32_;
					bitlen_ll.p->data[i_2] = code;
				}
				goto LA30_;
LA32_: ;
				{
					bitlen_d.p->data[(NI)(i_2 - HLIT)] = code;
				}
LA30_: ;
				i_2 += ((NI)1);
			}
			goto LA26_;
LA28_: ;
			{
				NI replength;
				NI value;
				NI T43_;
				if (!(code == ((NI)16))) goto LA36_;
				replength = ((NI)3);
				value = ((NI)0);
				{
					tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T42_;
					if (!(i_2 == ((NI)0))) goto LA40_;
					T42_ = NIM_NIL;
					T42_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
					(*T42_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
					(*T42_).Sup.Sup.name = "NZError";
					(*T42_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_22;
					(*T42_).Sup.Sup.parent = ((Exception*) NIM_NIL);
					raiseExceptionEx((Exception*)T42_, "NZError", "getTreeInflateDynamic", "nimz.nim", 540);
goto LA1_;
				}
LA40_: ;
				T43_ = (NI)0;
				T43_ = readBitsSafe__pkgZnim807871Znimz_u110(s_p0, ((NI)2));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				replength += T43_;
				{
					if (!(i_2 < (NI)(HLIT + ((NI)1)))) goto LA46_;
					value = bitlen_ll.p->data[(NI)(i_2 - ((NI)1))];
				}
				goto LA44_;
LA46_: ;
				{
					value = bitlen_d.p->data[(NI)((NI)(i_2 - HLIT) - ((NI)1))];
				}
LA44_: ;
				{
					NI n;
					NI colontmp_;
					NI res_2;
					n = (NI)0;
					colontmp_ = (NI)0;
					colontmp_ = (NI)(replength - ((NI)1));
					res_2 = ((NI)0);
					{
						while (1) {
							if (!(res_2 <= colontmp_)) goto LA51;
							n = ((NI) (res_2));
							{
								tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T56_;
								if (!((NI)(HLIT + HDIST) <= i_2)) goto LA54_;
								T56_ = NIM_NIL;
								T56_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
								(*T56_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
								(*T56_).Sup.Sup.name = "NZError";
								(*T56_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_26;
								(*T56_).Sup.Sup.parent = ((Exception*) NIM_NIL);
								raiseExceptionEx((Exception*)T56_, "NZError", "getTreeInflateDynamic", "nimz.nim", 548);
goto LA1_;
							}
LA54_: ;
							{
								if (!(i_2 < HLIT)) goto LA59_;
								bitlen_ll.p->data[i_2] = value;
							}
							goto LA57_;
LA59_: ;
							{
								bitlen_d.p->data[(NI)(i_2 - HLIT)] = value;
							}
LA57_: ;
							i_2 += ((NI)1);
							res_2 += ((NI)1);
						} LA51: ;
					}
				}
			}
			goto LA26_;
LA36_: ;
			{
				NI replength_2;
				NI T65_;
				if (!(code == ((NI)17))) goto LA63_;
				replength_2 = ((NI)3);
				T65_ = (NI)0;
				T65_ = readBitsSafe__pkgZnim807871Znimz_u110(s_p0, ((NI)3));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				replength_2 += T65_;
				{
					NI n_2;
					NI colontmp__2;
					NI res_3;
					n_2 = (NI)0;
					colontmp__2 = (NI)0;
					colontmp__2 = (NI)(replength_2 - ((NI)1));
					res_3 = ((NI)0);
					{
						while (1) {
							if (!(res_3 <= colontmp__2)) goto LA68;
							n_2 = ((NI) (res_3));
							{
								tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T73_;
								if (!((NI)(HLIT + HDIST) <= i_2)) goto LA71_;
								T73_ = NIM_NIL;
								T73_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
								(*T73_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
								(*T73_).Sup.Sup.name = "NZError";
								(*T73_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_27;
								(*T73_).Sup.Sup.parent = ((Exception*) NIM_NIL);
								raiseExceptionEx((Exception*)T73_, "NZError", "getTreeInflateDynamic", "nimz.nim", 558);
goto LA1_;
							}
LA71_: ;
							{
								if (!(i_2 < HLIT)) goto LA76_;
								bitlen_ll.p->data[i_2] = ((NI)0);
							}
							goto LA74_;
LA76_: ;
							{
								bitlen_d.p->data[(NI)(i_2 - HLIT)] = ((NI)0);
							}
LA74_: ;
							i_2 += ((NI)1);
							res_3 += ((NI)1);
						} LA68: ;
					}
				}
			}
			goto LA26_;
LA63_: ;
			{
				NI replength_3;
				NI T82_;
				if (!(code == ((NI)18))) goto LA80_;
				replength_3 = ((NI)11);
				T82_ = (NI)0;
				T82_ = readBitsSafe__pkgZnim807871Znimz_u110(s_p0, ((NI)7));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				replength_3 += T82_;
				{
					NI n_3;
					NI colontmp__3;
					NI res_4;
					n_3 = (NI)0;
					colontmp__3 = (NI)0;
					colontmp__3 = (NI)(replength_3 - ((NI)1));
					res_4 = ((NI)0);
					{
						while (1) {
							if (!(res_4 <= colontmp__3)) goto LA85;
							n_3 = ((NI) (res_4));
							{
								tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T90_;
								if (!((NI)(HLIT + HDIST) <= i_2)) goto LA88_;
								T90_ = NIM_NIL;
								T90_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
								(*T90_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
								(*T90_).Sup.Sup.name = "NZError";
								(*T90_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_28;
								(*T90_).Sup.Sup.parent = ((Exception*) NIM_NIL);
								raiseExceptionEx((Exception*)T90_, "NZError", "getTreeInflateDynamic", "nimz.nim", 568);
goto LA1_;
							}
LA88_: ;
							{
								if (!(i_2 < HLIT)) goto LA93_;
								bitlen_ll.p->data[i_2] = ((NI)0);
							}
							goto LA91_;
LA93_: ;
							{
								bitlen_d.p->data[(NI)(i_2 - HLIT)] = ((NI)0);
							}
LA91_: ;
							i_2 += ((NI)1);
							res_4 += ((NI)1);
						} LA85: ;
					}
				}
			}
			goto LA26_;
LA80_: ;
			{
				{
					if (!(code == ((NI)-1))) goto LA99_;
					{
						tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T105_;
						if (!(inbitlength < (*s_p0).bitpointer)) goto LA103_;
						T105_ = NIM_NIL;
						T105_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
						(*T105_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
						(*T105_).Sup.Sup.name = "NZError";
						(*T105_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_30;
						(*T105_).Sup.Sup.parent = ((Exception*) NIM_NIL);
						raiseExceptionEx((Exception*)T105_, "NZError", "getTreeInflateDynamic", "nimz.nim", 576);
goto LA1_;
					}
					goto LA101_;
LA103_: ;
					{
						tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T107_;
						T107_ = NIM_NIL;
						T107_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
						(*T107_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
						(*T107_).Sup.Sup.name = "NZError";
						(*T107_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_32;
						(*T107_).Sup.Sup.parent = ((Exception*) NIM_NIL);
						raiseExceptionEx((Exception*)T107_, "NZError", "getTreeInflateDynamic", "nimz.nim", 577);
goto LA1_;
					}
LA101_: ;
				}
				goto LA97_;
LA99_: ;
				{
					tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T109_;
					T109_ = NIM_NIL;
					T109_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
					(*T109_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
					(*T109_).Sup.Sup.name = "NZError";
					(*T109_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_34;
					(*T109_).Sup.Sup.parent = ((Exception*) NIM_NIL);
					raiseExceptionEx((Exception*)T109_, "NZError", "getTreeInflateDynamic", "nimz.nim", 579);
goto LA1_;
				}
LA97_: ;
				goto LA24;
			}
LA26_: ;
		} LA25: ;
	} LA24: ;
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T114_;
		if (!(bitlen_ll.p->data[((NI)256)] == ((NI)0))) goto LA112_;
		T114_ = NIM_NIL;
		T114_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T114_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T114_).Sup.Sup.name = "NZError";
		(*T114_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_36;
		(*T114_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T114_, "NZError", "getTreeInflateDynamic", "nimz.nim", 583);
goto LA1_;
	}
LA112_: ;
	HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414(tree_ll_p1, ((bitlen_ll).p) ? (bitlen_ll.p->data) : NIM_NIL, bitlen_ll.len, ((NI)15));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	HuffmanTree_makeFromLengths__pkgZnim807871Znimz_u414(tree_d_p2, ((bitlen_d).p) ? (bitlen_d.p->data) : NIM_NIL, bitlen_d.len, ((NI)15));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pkgZnim807871Znimz_u1326((&tree_cl));
		eqdestroy___pkgZnicoZbackendsZcommon_u3229(bitlen_cl);
		eqdestroy___pkgZnicoZbackendsZcommon_u3229(bitlen_d);
		eqdestroy___pkgZnicoZbackendsZcommon_u3229(bitlen_ll);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, inflateHuffmanBlock__pkgZnim807871Znimz_u1368)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0, NI blockType_p1) {
	tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA tree_ll;
	tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA tree_d;
	NI inlength;
	NI inbitlength;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&tree_ll), sizeof(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA));
	nimZeroMem((void*)(&tree_d), sizeof(tyObject_HuffmanTree__9acxbU60avVMzUyiympYdgA));
	inlength = (*nz_p0).bits.data.len;
	inbitlength = (NI)(inlength * ((NI)8));
	{
		if (!(blockType_p1 == ((NI)1))) goto LA4_;
		getTreeInflateFixed__pkgZnim807871Znimz_u1163((&tree_ll), (&tree_d));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA2_;
LA4_: ;
	{
		if (!(blockType_p1 == ((NI)2))) goto LA7_;
		getTreeInflateDynamic__pkgZnim807871Znimz_u1182((&(*nz_p0).bits), (&tree_ll), (&tree_d));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA2_;
LA7_: ;
LA2_: ;
	{
		while (1) {
			NI code_ll;
			code_ll = huffmanDecodeSymbol__pkgZnim807871Znimz_u1166((&(*nz_p0).bits), (&tree_ll), inbitlength);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				if (!(code_ll <= ((NI)255))) goto LA13_;
				nimAddCharV1((&(*nz_p0).data), ((NIM_CHAR) ((code_ll))));
			}
			goto LA11_;
LA13_: ;
			{
				NIM_BOOL T16_;
				NI length;
				NI numextrabits_l;
				NI T20_;
				NI code_d;
				NI distance;
				NI numextrabits_d;
				NI T38_;
				NI start;
				NI backward;
				T16_ = (NIM_BOOL)0;
				T16_ = (((NI)257) <= code_ll);
				if (!(T16_)) goto LA17_;
				T16_ = (code_ll <= ((NI)285));
LA17_: ;
				if (!T16_) goto LA18_;
				length = LENGTHBASE__pkgZnim807871Znimz_u7[((NI)(code_ll - ((NI)257)))- 0];
				numextrabits_l = LENGTHEXTRA__pkgZnim807871Znimz_u8[((NI)(code_ll - ((NI)257)))- 0];
				T20_ = (NI)0;
				T20_ = readBitsSafe__pkgZnim807871Znimz_u110((&(*nz_p0).bits), numextrabits_l);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				length += T20_;
				code_d = huffmanDecodeSymbol__pkgZnim807871Znimz_u1166((&(*nz_p0).bits), (&tree_d), inbitlength);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				{
					if (!(((NI)29) < code_d)) goto LA23_;
					{
						if (!(code_ll == ((NI)-1))) goto LA27_;
						{
							tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T33_;
							if (!(inbitlength < (*nz_p0).bits.bitpointer)) goto LA31_;
							T33_ = NIM_NIL;
							T33_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
							(*T33_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
							(*T33_).Sup.Sup.name = "NZError";
							(*T33_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_37;
							(*T33_).Sup.Sup.parent = ((Exception*) NIM_NIL);
							raiseExceptionEx((Exception*)T33_, "NZError", "inflateHuffmanBlock", "nimz.nim", 620);
goto LA1_;
						}
						goto LA29_;
LA31_: ;
						{
							tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T35_;
							T35_ = NIM_NIL;
							T35_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
							(*T35_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
							(*T35_).Sup.Sup.name = "NZError";
							(*T35_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_38;
							(*T35_).Sup.Sup.parent = ((Exception*) NIM_NIL);
							raiseExceptionEx((Exception*)T35_, "NZError", "inflateHuffmanBlock", "nimz.nim", 621);
goto LA1_;
						}
LA29_: ;
					}
					goto LA25_;
LA27_: ;
					{
						tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T37_;
						T37_ = NIM_NIL;
						T37_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
						(*T37_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
						(*T37_).Sup.Sup.name = "NZError";
						(*T37_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_40;
						(*T37_).Sup.Sup.parent = ((Exception*) NIM_NIL);
						raiseExceptionEx((Exception*)T37_, "NZError", "inflateHuffmanBlock", "nimz.nim", 623);
goto LA1_;
					}
LA25_: ;
					goto LA9;
				}
LA23_: ;
				distance = DISTANCEBASE__pkgZnim807871Znimz_u9[(code_d)- 0];
				numextrabits_d = DISTANCEEXTRA__pkgZnim807871Znimz_u10[(code_d)- 0];
				T38_ = (NI)0;
				T38_ = readBitsSafe__pkgZnim807871Znimz_u110((&(*nz_p0).bits), numextrabits_d);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				distance += T38_;
				start = (*nz_p0).data.len;
				{
					tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T43_;
					if (!(start < distance)) goto LA41_;
					T43_ = NIM_NIL;
					T43_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
					(*T43_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
					(*T43_).Sup.Sup.name = "NZError";
					(*T43_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_42;
					(*T43_).Sup.Sup.parent = ((Exception*) NIM_NIL);
					raiseExceptionEx((Exception*)T43_, "NZError", "inflateHuffmanBlock", "nimz.nim", 634);
goto LA1_;
				}
LA41_: ;
				backward = (NI)(start - distance);
				setLengthStrV2((&(*nz_p0).data), ((NI)(start + length)));
				{
					NI pos;
					NI colontmp_;
					NI res;
					pos = (NI)0;
					colontmp_ = (NI)0;
					colontmp_ = (NI)(length - ((NI)1));
					res = ((NI)0);
					{
						while (1) {
							if (!(res <= colontmp_)) goto LA46;
							pos = ((NI) (res));
							nimPrepareStrMutationV2((&(*nz_p0).data));
							(*nz_p0).data.p->data[(NI)(pos + start)] = (*nz_p0).data.p->data[backward];
							backward += ((NI)1);
							{
								if (!(start <= backward)) goto LA49_;
								backward = (NI)(start - distance);
							}
LA49_: ;
							res += ((NI)1);
						} LA46: ;
					}
				}
			}
			goto LA11_;
LA18_: ;
			{
				if (!(code_ll == ((NI)256))) goto LA52_;
				goto LA9;
			}
			goto LA11_;
LA52_: ;
			{
				{
					tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T59_;
					if (!(inbitlength < (*nz_p0).bits.bitpointer)) goto LA57_;
					T59_ = NIM_NIL;
					T59_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
					(*T59_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
					(*T59_).Sup.Sup.name = "NZError";
					(*T59_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_43;
					(*T59_).Sup.Sup.parent = ((Exception*) NIM_NIL);
					raiseExceptionEx((Exception*)T59_, "NZError", "inflateHuffmanBlock", "nimz.nim", 647);
goto LA1_;
				}
				goto LA55_;
LA57_: ;
				{
					tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T61_;
					T61_ = NIM_NIL;
					T61_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
					(*T61_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
					(*T61_).Sup.Sup.name = "NZError";
					(*T61_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_44;
					(*T61_).Sup.Sup.parent = ((Exception*) NIM_NIL);
					raiseExceptionEx((Exception*)T61_, "NZError", "inflateHuffmanBlock", "nimz.nim", 648);
goto LA1_;
				}
LA55_: ;
				goto LA9;
			}
LA11_: ;
		}
	} LA9: ;
	{
		LA1_:;
	}
	{
		eqdestroy___pkgZnim807871Znimz_u1326((&tree_d));
		eqdestroy___pkgZnim807871Znimz_u1326((&tree_ll));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nzInflate__pkgZnim807871Znimz_u1426)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0) {
	NIM_BOOL finalBlock;
	NI streamLen;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	finalBlock = NIM_FALSE;
	streamLen = (*nz_p0).bits.databitlen;
	{
		while (1) {
			NI T7_;
			NI blockType;
			NI T8_;
			NI T9_;
			if (!!(finalBlock)) goto LA2;
			{
				if (!(streamLen <= (NI)((*nz_p0).bits.bitpointer + ((NI)2)))) goto LA5_;
				goto LA1;
			}
LA5_: ;
			T7_ = (NI)0;
			T7_ = readBitFromStream__pkgZnim807871Znimz_u79((&(*nz_p0).bits));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			finalBlock = !((T7_ == ((NI)0)));
			T8_ = (NI)0;
			T8_ = readBitFromStream__pkgZnim807871Znimz_u79((&(*nz_p0).bits));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T9_ = (NI)0;
			T9_ = readBitFromStream__pkgZnim807871Znimz_u79((&(*nz_p0).bits));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			blockType = (NI)(T8_ + (NI)(((NI)2) * T9_));
			{
				tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T14_;
				if (!(blockType == ((NI)3))) goto LA12_;
				T14_ = NIM_NIL;
				T14_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
				(*T14_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
				(*T14_).Sup.Sup.name = "NZError";
				(*T14_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_10;
				(*T14_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				raiseExceptionEx((Exception*)T14_, "NZError", "nzInflate", "nimz.nim", 662);
goto BeforeRet_;
			}
			goto LA10_;
LA12_: ;
			{
				if (!(blockType == ((NI)0))) goto LA16_;
				inflateNoCompression__pkgZnim807871Znimz_u1139(nz_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			goto LA10_;
LA16_: ;
			{
				inflateHuffmanBlock__pkgZnim807871Znimz_u1368(nz_p0, blockType);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA10_: ;
		} LA2: ;
	} LA1: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, nzAdler32__pkgZnim807871Znimz_u2549)(NU32 adler_p0, NimStringV2 data_p1) {
	NU32 result;
	NU32 s1;
	NU32 s2;
	NI len;
	NI i;
	s1 = (NU32)(adler_p0 & ((NU32)65535));
	s2 = (NU32)((NU32)((NU32)(adler_p0) >> (NU32)(((NI)16))) & ((NU32)65535));
	len = data_p1.len;
	i = ((NI)0);
	{
		while (1) {
			NI amount;
			if (!(((NI)0) < len)) goto LA2;
			amount = ((len <= ((NI)5550)) ? len : ((NI)5550));
			len -= amount;
			{
				while (1) {
					if (!(((NI)0) < amount)) goto LA4;
					s1 += ((NU32) ((NI)(((NU8)(data_p1.p->data[i])) | ((NI)0))));
					s2 += s1;
					amount -= ((NI)1);
					i += ((NI)1);
				} LA4: ;
			}
			s1 = (NU32)((NU32)(s1) % (NU32)(((NU32)65521)));
			s2 = (NU32)((NU32)(s2) % (NU32)(((NU32)65521)));
		} LA2: ;
	}
	result = (NU32)((NU32)((NU32)(s2) << (NU32)(((NU32)16))) | s1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nzGetResult__pkgZnim807871Znimz_u2541)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0) {
	NimStringV2 result;
{	result.len = 0; result.p = NIM_NIL;
	{
		if (!((*nz_p0).mode == ((tyEnum_nzStreamMode__ebRRaj8yuuWem9aynE7njsg)1))) goto LA3_;
		eqcopy___system_u2690((&result), (*nz_p0).data);
		goto BeforeRet_;
	}
LA3_: ;
	eqcopy___system_u2690((&result), (*nz_p0).bits.data);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, zlib_decompress__pkgZnim807871Znimz_u2665)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* nz_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NI insize;
	NI CMF;
	NI FLG;
	NU32 checksum;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	insize = (*nz_p0).bits.data.len;
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T6_;
		if (!(insize < ((NI)2))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T6_).Sup.Sup.name = "NZError";
		(*T6_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_4;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "NZError", "zlib_decompress", "nimz.nim", 1313);
goto LA1_;
	}
LA4_: ;
	CMF = readByte__pkgZnim807871Znimz_u1121((&(*nz_p0).bits));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	FLG = readByte__pkgZnim807871Znimz_u1121((&(*nz_p0).bits));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T11_;
		if (!!(((NI)((NI)((NI)(CMF * ((NI)256)) + FLG) % ((NI)31)) == ((NI)0)))) goto LA9_;
		T11_ = NIM_NIL;
		T11_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
		(*T11_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
		(*T11_).Sup.Sup.name = "NZError";
		(*T11_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_8;
		(*T11_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T11_, "NZError", "zlib_decompress", "nimz.nim", 1320);
goto LA1_;
	}
LA9_: ;
	colontmpD_ = substr__system_u8826((*nz_p0).bits.data, (NI)(insize - ((NI)4)), (NI)(insize - ((NI)1)));
	checksum = readInt32__pkgZnim807871Znimz_u2623(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	setLengthStrV2((&(*nz_p0).bits.data), ((NI)(insize - ((NI)4))));
	(*nz_p0).bits.databitlen = (NI)((NI)(insize - ((NI)4)) * ((NI)8));
	nzInflate__pkgZnim807871Znimz_u1426(nz_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NU32 adler32;
		if (!!((*nz_p0).ignoreAdler32)) goto LA14_;
		adler32 = nzAdler32__pkgZnim807871Znimz_u2549(((NU32)1), (*nz_p0).data);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA* T20_;
			if (!!((checksum == adler32))) goto LA18_;
			T20_ = NIM_NIL;
			T20_ = (tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA*) nimNewObj(sizeof(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA), NIM_ALIGNOF(tyObject_NZError__gV1iP4tiOac2X8tXkzX9c9bA));
			(*T20_).Sup.Sup.Sup.m_type = (&NTIv2__gV1iP4tiOac2X8tXkzX9c9bA_);
			(*T20_).Sup.Sup.name = "NZError";
			(*T20_).Sup.Sup.message = TM__n9cknNhkm8Fa9boCSB3rtZeA_46;
			(*T20_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T20_, "NZError", "zlib_decompress", "nimz.nim", 1346);
goto LA1_;
		}
LA18_: ;
	}
LA14_: ;
	result = nzGetResult__pkgZnim807871Znimz_u2541(nz_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((NI32)((*cell).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u2448)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* dest_p0) {
	if ((*dest_p0).bits.data.p && !((*dest_p0).bits.data.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).bits.data.p);
}
	if ((*dest_p0).data.p && !((*dest_p0).data.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).data.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnim807871Znimz_u2480)(tyObject_nzStreamcolonObjectType___Enq9aWdn80y9aU9ad39bxObIrA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnim807871Znimz_u2448(dest_p0);
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
