/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snico-0.4.10-f4d0514d40cc9aeaa3f02e3654986ff28d1038ec@snico@scontroller.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snico-0.4.10-f4d0514d40cc9aeaa3f02e3654986ff28d1038ec@snico@scontroller.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__Wf8pb9aU0WdM83selH6Zpuw tyTuple__Wf8pb9aU0WdM83selH6Zpuw;
typedef struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug tySequence__PclZllI1Ry7MX4uStk4Jug;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content tySequence__PclZllI1Ry7MX4uStk4Jug_Content;
typedef struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q;
typedef NU8 tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__Wf8pb9aU0WdM83selH6Zpuw {
	NF Field0;
	NF Field1;
	NI Field2;
};
typedef tyTuple__Wf8pb9aU0WdM83selH6Zpuw tyArray__NJOswEblr10qEBmk9am1gFg[6];
typedef NI tyArray__0gDP19airgUjPdMoI3rX27g[16];
struct tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ {
	tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ kind;
	NimStringV2 name;
	void* sdlController;
	NI id;
	tyArray__NJOswEblr10qEBmk9am1gFg axes;
	tyArray__0gDP19airgUjPdMoI3rX27g buttons;
	NF deadzone;
	NIM_BOOL invertX;
	NIM_BOOL invertY;
	NIM_BOOL useRightStick;
};
struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug {
  NI len; tySequence__PclZllI1Ry7MX4uStk4Jug_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__PclZllI1Ry7MX4uStk4Jug trace;
	Exception* up;
};
typedef NimStringV2 tyArray__yt5VDPNtUGx9cBkOVakHwdQ[6];
typedef NU8 tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw;
typedef NU8 tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg;
struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content { NI cap; tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZcontroller_u86)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ*, new__pkgZnicoZcontroller_u56)(void);
N_CDECL(void*, SDL_GameControllerOpen)(int joystick_index_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_CDECL(NCSTRING, SDL_GameControllerName)(void* gamecontroller_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pkgZnicoZcontroller_u5)(tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ e_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimIncRef)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NF, axis__pkgZnicoZcontroller_u311)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0, tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg axis_p1);
extern TNimTypeV2 NTIv2__XEycrCsme5C8CVWAYEcdBQ_;
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__MRtAw1n0oukYMfechIasDg_2 = { 31 | NIM_STRLIT_FLAG, "error opening game controller: " };
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_3 = {31, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_2};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__MRtAw1n0oukYMfechIasDg_4 = { 8 | NIM_STRLIT_FLAG, "KEYBOARD" };
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_5 = {8, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__MRtAw1n0oukYMfechIasDg_6 = { 23 | NIM_STRLIT_FLAG, "added game controller: " };
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_7 = {23, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__MRtAw1n0oukYMfechIasDg_8 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_9 = {2, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_8};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__MRtAw1n0oukYMfechIasDg_10 = { 8 | NIM_STRLIT_FLAG, "Keyboard" };
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_11 = {8, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_10};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__MRtAw1n0oukYMfechIasDg_12 = { 7 | NIM_STRLIT_FLAG, "Gamepad" };
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_13 = {7, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_12};
static const NimStringV2 TM__MRtAw1n0oukYMfechIasDg_14 = {2, (NimStrPayload*)&TM__MRtAw1n0oukYMfechIasDg_8};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZcontroller_u86)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* dest_p0) {
	if ((*dest_p0).name.p && !((*dest_p0).name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name.p);
}
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((NI32)((*cell).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZcontroller_u68)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnicoZcontroller_u86(dest_p0);
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZcontroller_u65)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(src_p1.len + ((NI)1))));
		(*dest_p0).len += src_p1.len;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pkgZnicoZcontroller_u5)(tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ)0):
	{
		result = TM__MRtAw1n0oukYMfechIasDg_11;
	}
	break;
	case ((tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ)1):
	{
		result = TM__MRtAw1n0oukYMfechIasDg_13;
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ*, newNicoController__pkgZnicoZcontroller_u53)(int id_p0) {
	tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyArray__yt5VDPNtUGx9cBkOVakHwdQ T18_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	result = new__pkgZnicoZcontroller_u56();
	(*result).id = ((NI) (id_p0));
	{
		NCSTRING T15_;
		NimStringV2 T16_;
		if (!(((NI32)-1) < id_p0)) goto LA4_;
		(*result).sdlController = SDL_GameControllerOpen(id_p0);
		{
			NimStringV2 colontmpD__3;
			Exception* T11_;
			NimStringV2 T12_;
			if (!((*result).sdlController == NIM_NIL)) goto LA8_;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			T11_ = NIM_NIL;
			T11_ = (Exception*) nimNewObj(sizeof(Exception), NIM_ALIGNOF(Exception));
			(*T11_).Sup.m_type = (&NTIv2__XEycrCsme5C8CVWAYEcdBQ_);
			(*T11_).name = "Exception";
			T12_.len = 0; T12_.p = NIM_NIL;
			colontmpD__3 = dollar___systemZdollars_u8(((NI) (id_p0)));
			if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
			T12_ = rawNewString(colontmpD__3.len + 31);
appendString((&T12_), TM__MRtAw1n0oukYMfechIasDg_3);
appendString((&T12_), colontmpD__3);
			(*T11_).message = T12_;
			(*T11_).parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T11_, "Exception", "newNicoController", "controller.nim", 53);
goto LA10_;
			{
				LA10_:;
			}
			{
				if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
LA8_: ;
		T15_ = (NCSTRING)0;
		T15_ = SDL_GameControllerName((*result).sdlController);
		T16_.len = 0; T16_.p = NIM_NIL;
		T16_ = cstrToNimstr(T15_);
		eqsink___system_u2696((&(*result).name), T16_);
		(*result).kind = ((tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ)1);
		(*result).deadzone = 0.5;
	}
	goto LA2_;
LA4_: ;
	{
		(*result).kind = ((tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ)0);
		eqsink___system_u2696((&(*result).name), TM__MRtAw1n0oukYMfechIasDg_5);
	}
LA2_: ;
	T18_[0] = TM__MRtAw1n0oukYMfechIasDg_7;
	colontmpD_ = dollar___systemZdollars_u8(((NI) (id_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T18_[1] = colontmpD_;
	T18_[2] = TM__MRtAw1n0oukYMfechIasDg_9;
	colontmpD__2 = dollar___pkgZnicoZcontroller_u5((*result).kind);
	T18_[3] = colontmpD__2;
	T18_[4] = TM__MRtAw1n0oukYMfechIasDg_14;
	T18_[5] = (*result).name;
	echoBinSafe(T18_, 6);
	{
		LA1_:;
	}
	{
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	(*((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T1_))).rc += ((NI)16);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ*, eqdup___pkgZnicoZcontroller_u74)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* src_p0) {
	tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZcontroller_u77)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ** dest_p0, tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnicoZcontroller_u86((*dest_p0));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, setButtonState__pkgZnicoZcontroller_u420)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0, tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw button_p1, NIM_BOOL down_p2) {
	NI colontmpD_;
	NI colontmpD__2;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	{
		if (!(((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)15) < button_p1)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!down_p2) goto LA7_;
		colontmpD_ = ((NI)1);
		(*self_p0).buttons[(button_p1)- 0] = colontmpD_;
	}
	goto LA5_;
LA7_: ;
	{
		colontmpD__2 = ((NI)-2);
		(*self_p0).buttons[(button_p1)- 0] = colontmpD__2;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setAxisValue__pkgZnicoZcontroller_u432)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0, tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg axis_p1, NF value_p2) {
{	{
		if (!(((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)5) < axis_p1)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		NIM_BOOL T11_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T8_ = (axis_p1 == ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)0));
		if (!(T8_)) goto LA9_;
		T8_ = (*self_p0).invertX;
LA9_: ;
		T7_ = T8_;
		if (T7_) goto LA10_;
		T11_ = (NIM_BOOL)0;
		T11_ = (axis_p1 == ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)1));
		if (!(T11_)) goto LA12_;
		T11_ = (*self_p0).invertY;
LA12_: ;
		T7_ = T11_;
LA10_: ;
		if (!T7_) goto LA13_;
		(*self_p0).axes[(axis_p1)- 0].Field0 = -(value_p2);
	}
	goto LA5_;
LA13_: ;
	{
		(*self_p0).axes[(axis_p1)- 0].Field0 = value_p2;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, update__pkgZnicoZcontroller_u182)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0) {
	{
		tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw i;
		NI res;
		i = (tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)0;
		res = ((NI)0);
		{
			while (1) {
				if (!(res <= ((NI)15))) goto LA3;
				i = ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw) (res));
				{
					if (!((*self_p0).kind == ((tyEnum_NicoControllerKind__5THGgzvcmaTrlb1pD5eKbQ)1))) goto LA6_;
					{
						if (!(i == ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)9))) goto LA10_;
						{
							if (!((*self_p0).deadzone < (*self_p0).axes[(((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)4))- 0].Field0)) goto LA14_;
							(*self_p0).buttons[(i)- 0] += ((NI)1);
						}
						goto LA12_;
LA14_: ;
						{
							(*self_p0).buttons[(i)- 0] = ((NI)0);
						}
LA12_: ;
					}
					goto LA8_;
LA10_: ;
					{
						if (!(i == ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)12))) goto LA18_;
						{
							if (!((*self_p0).deadzone < (*self_p0).axes[(((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)5))- 0].Field0)) goto LA22_;
							(*self_p0).buttons[(i)- 0] += ((NI)1);
						}
						goto LA20_;
LA22_: ;
						{
							(*self_p0).buttons[(i)- 0] = ((NI)0);
						}
LA20_: ;
					}
					goto LA8_;
LA18_: ;
LA8_: ;
				}
LA6_: ;
				{
					if (!((*self_p0).buttons[(i)- 0] == ((NI)-1))) goto LA27_;
					(*self_p0).buttons[(i)- 0] = ((NI)0);
				}
				goto LA25_;
LA27_: ;
				{
					if (!((*self_p0).buttons[(i)- 0] == ((NI)-2))) goto LA30_;
					(*self_p0).buttons[(i)- 0] = ((NI)-1);
				}
				goto LA25_;
LA30_: ;
LA25_: ;
				{
					if (!(((NI)1) <= (*self_p0).buttons[(i)- 0])) goto LA34_;
					(*self_p0).buttons[(i)- 0] += ((NI)1);
				}
LA34_: ;
				res += ((NI)1);
			} LA3: ;
		}
	}
	{
		tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg i_2;
		NI res_2;
		i_2 = (tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)0;
		res_2 = ((NI)0);
		{
			while (1) {
				if (!(res_2 <= ((NI)5))) goto LA38;
				i_2 = ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg) (res_2));
				{
					NIM_BOOL T41_;
					T41_ = (NIM_BOOL)0;
					T41_ = ((*self_p0).axes[(i_2)- 0].Field1 < -((*self_p0).deadzone));
					if (!(T41_)) goto LA42_;
					T41_ = ((*self_p0).axes[(i_2)- 0].Field0 < -((*self_p0).deadzone));
LA42_: ;
					if (!T41_) goto LA43_;
					(*self_p0).axes[(i_2)- 0].Field2 += ((NI)1);
				}
				goto LA39_;
LA43_: ;
				{
					NIM_BOOL T46_;
					T46_ = (NIM_BOOL)0;
					T46_ = ((*self_p0).deadzone < (*self_p0).axes[(i_2)- 0].Field1);
					if (!(T46_)) goto LA47_;
					T46_ = ((*self_p0).deadzone < (*self_p0).axes[(i_2)- 0].Field0);
LA47_: ;
					if (!T46_) goto LA48_;
					(*self_p0).axes[(i_2)- 0].Field2 += ((NI)1);
				}
				goto LA39_;
LA48_: ;
				{
					(*self_p0).axes[(i_2)- 0].Field2 = ((NI)0);
				}
LA39_: ;
				res_2 += ((NI)1);
			} LA38: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, postUpdate__pkgZnicoZcontroller_u296)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0) {
	{
		tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg i;
		NI res;
		i = (tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)0;
		res = ((NI)0);
		{
			while (1) {
				if (!(res <= ((NI)5))) goto LA3;
				i = ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg) (res));
				(*self_p0).axes[(i)- 0].Field1 = (*self_p0).axes[(i)- 0].Field0;
				res += ((NI)1);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(NF, axis__pkgZnicoZcontroller_u311)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0, tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg axis_p1) {
	NF result;
{	result = (*self_p0).axes[(axis_p1)- 0].Field0;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, btn__pkgZnicoZcontroller_u326)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0, tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw button_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T5_;
		NF T7_;
		if (!(button_p1 == ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)0))) goto LA3_;
		T5_ = (NIM_BOOL)0;
		T5_ = (((NI)0) < (*self_p0).buttons[(button_p1)- 0]);
		if (T5_) goto LA6_;
		T7_ = (NF)0;
		T7_ = axis__pkgZnicoZcontroller_u311(self_p0, ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T5_ = (T7_ < -((*self_p0).deadzone));
LA6_: ;
		result = T5_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T11_;
		NF T13_;
		if (!(button_p1 == ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)1))) goto LA9_;
		T11_ = (NIM_BOOL)0;
		T11_ = (((NI)0) < (*self_p0).buttons[(button_p1)- 0]);
		if (T11_) goto LA12_;
		T13_ = (NF)0;
		T13_ = axis__pkgZnicoZcontroller_u311(self_p0, ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T11_ = ((*self_p0).deadzone < T13_);
LA12_: ;
		result = T11_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		NIM_BOOL T17_;
		NF T19_;
		if (!(button_p1 == ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)2))) goto LA15_;
		T17_ = (NIM_BOOL)0;
		T17_ = (((NI)0) < (*self_p0).buttons[(button_p1)- 0]);
		if (T17_) goto LA18_;
		T19_ = (NF)0;
		T19_ = axis__pkgZnicoZcontroller_u311(self_p0, ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T17_ = (T19_ < -((*self_p0).deadzone));
LA18_: ;
		result = T17_;
		goto BeforeRet_;
	}
	goto LA1_;
LA15_: ;
	{
		NIM_BOOL T23_;
		NF T25_;
		if (!(button_p1 == ((tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw)3))) goto LA21_;
		T23_ = (NIM_BOOL)0;
		T23_ = (((NI)0) < (*self_p0).buttons[(button_p1)- 0]);
		if (T23_) goto LA24_;
		T25_ = (NF)0;
		T25_ = axis__pkgZnicoZcontroller_u311(self_p0, ((tyEnum_NicoAxis__eF4bd0oBMoJ1BAI9a9b4pOwg)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T23_ = ((*self_p0).deadzone < T25_);
LA24_: ;
		result = T23_;
		goto BeforeRet_;
	}
	goto LA1_;
LA21_: ;
LA1_: ;
	result = (((NI)0) < (*self_p0).buttons[(button_p1)- 0]);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, btnup__pkgZnicoZcontroller_u390)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* self_p0, tyEnum_NicoButton__DuWECYQZDfo5yecT9cSNFVw button_p1) {
	NIM_BOOL result;
{	result = ((*self_p0).buttons[(button_p1)- 0] == ((NI)-1));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
