/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@spure@sparseutils.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@spure@sparseutils.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ;
typedef struct tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug tySequence__PclZllI1Ry7MX4uStk4Jug;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content tySequence__PclZllI1Ry7MX4uStk4Jug_Content;
typedef struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug {
  NI len; tySequence__PclZllI1Ry7MX4uStk4Jug_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__PclZllI1Ry7MX4uStk4Jug trace;
	Exception* up;
};
struct tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA {
	Exception Sup;
};
struct tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ {
	tyObject_CatchableError__170PUSd9bpOf09cSZOeaNOaA Sup;
};
struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content { NI cap; tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* number_p1);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* number_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_u327)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* b_p1);
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_u325)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern TNimTypeV2 NTIv2__tkID4So8lTV9byDQqIe8LtQ_;
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__vI9aZNKIcImom6dDyKXW1ZA_2 = { 37 | NIM_STRLIT_FLAG, "Parsed integer outside of valid range" };
static const NimStringV2 TM__vI9aZNKIcImom6dDyKXW1ZA_3 = {37, (NimStrPayload*)&TM__vI9aZNKIcImom6dDyKXW1ZA_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_u325)(void) {
	tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ* T1_;
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ*) nimNewObj(sizeof(tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ), NIM_ALIGNOF(tyObject_ValueError__tkID4So8lTV9byDQqIe8LtQ));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__tkID4So8lTV9byDQqIe8LtQ_);
	(*T1_).Sup.Sup.name = "ValueError";
	(*T1_).Sup.Sup.message = TM__vI9aZNKIcImom6dDyKXW1ZA_3;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "integerOutOfRangeError", "parseutils.nim", 429);
goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_u327)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* b_p1) {
	NI result;
	NI64 sign;
	NI i;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	sign = IL64(-1);
	i = ((NI)0);
	{
		if (!(i < s_p0Len_0)) goto LA3_;
		{
			if (!((NU8)(s_p0[i]) == (NU8)(43))) goto LA7_;
			i += ((NI)1);
		}
		goto LA5_;
LA7_: ;
		{
			if (!((NU8)(s_p0[i]) == (NU8)(45))) goto LA10_;
			i += ((NI)1);
			sign = IL64(1);
		}
		goto LA5_;
LA10_: ;
LA5_: ;
	}
LA3_: ;
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = (i < s_p0Len_0);
		if (!(T14_)) goto LA15_;
		T14_ = (((NU8)(s_p0[i])) >= ((NU8)(48)) && ((NU8)(s_p0[i])) <= ((NU8)(57)));
LA15_: ;
		if (!T14_) goto LA16_;
		(*b_p1) = IL64(0);
		{
			while (1) {
				NIM_BOOL T20_;
				NI c;
				T20_ = (NIM_BOOL)0;
				T20_ = (i < s_p0Len_0);
				if (!(T20_)) goto LA21_;
				T20_ = (((NU8)(s_p0[i])) >= ((NU8)(48)) && ((NU8)(s_p0[i])) <= ((NU8)(57)));
LA21_: ;
				if (!T20_) goto LA19;
				c = (NI)(((NU8)(s_p0[i])) - ((NI)48));
				{
					if (!((NI64)((NI64)((IL64(-9223372036854775807) - IL64(1)) + ((NI64) (c))) / IL64(10)) <= (*b_p1))) goto LA24_;
					(*b_p1) = (NI64)((NI64)((*b_p1) * IL64(10)) - ((NI64) (c)));
				}
				goto LA22_;
LA24_: ;
				{
					integerOutOfRangeError__pureZparseutils_u325();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA22_: ;
				i += ((NI)1);
				{
					while (1) {
						NIM_BOOL T29_;
						T29_ = (NIM_BOOL)0;
						T29_ = (i < s_p0Len_0);
						if (!(T29_)) goto LA30_;
						T29_ = ((NU8)(s_p0[i]) == (NU8)(95));
LA30_: ;
						if (!T29_) goto LA28;
						i += ((NI)1);
					} LA28: ;
				}
			} LA19: ;
		}
		{
			NIM_BOOL T33_;
			T33_ = (NIM_BOOL)0;
			T33_ = (sign == IL64(-1));
			if (!(T33_)) goto LA34_;
			T33_ = ((*b_p1) == (IL64(-9223372036854775807) - IL64(1)));
LA34_: ;
			if (!T33_) goto LA35_;
			integerOutOfRangeError__pureZparseutils_u325();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA31_;
LA35_: ;
		{
			(*b_p1) = (NI64)((*b_p1) * sign);
			result = i;
		}
LA31_: ;
	}
	goto LA12_;
LA16_: ;
	{
		result = ((NI)0);
	}
LA12_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* number_p1) {
	NI result;
	NI64 res;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	res = IL64(0);
	result = rawParseInt__pureZparseutils_u327(s_p0, s_p0Len_0, (&res));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!!((result == ((NI)0)))) goto LA3_;
		(*number_p1) = res;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* number_p1) {
	NI result;
	NI64 res;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	res = IL64(0);
	result = npuParseBiggestInt(s_p0, s_p0Len_0, (&res));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (res < IL64(-2147483648));
		if (T3_) goto LA4_;
		T3_ = (IL64(2147483647) < res);
LA4_: ;
		if (!T3_) goto LA5_;
		integerOutOfRangeError__pureZparseutils_u325();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	{
		if (!!((result == ((NI)0)))) goto LA9_;
		(*number_p1) = ((NI) (res));
	}
LA9_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u928)(NimStringV2 s_p0, NI* number_p1, NI start_p2) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = npuParseInt((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(start_p2)) : NIM_NIL), ((s_p0.len-1))-(start_p2)+1, number_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
