/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@sstd@sassertions.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.choosenim@stoolchains@snim-2.2.2@slib@sstd@sassertions.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g;
typedef struct tyObject_Defect__4Qjw1ymvv6qxb82XbdyQ5Q tyObject_Defect__4Qjw1ymvv6qxb82XbdyQ5Q;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug tySequence__PclZllI1Ry7MX4uStk4Jug;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content tySequence__PclZllI1Ry7MX4uStk4Jug_Content;
typedef struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug {
  NI len; tySequence__PclZllI1Ry7MX4uStk4Jug_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__PclZllI1Ry7MX4uStk4Jug trace;
	Exception* up;
};
struct tyObject_Defect__4Qjw1ymvv6qxb82XbdyQ5Q {
	Exception Sup;
};
struct tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g {
	tyObject_Defect__4Qjw1ymvv6qxb82XbdyQ5Q Sup;
};
struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content { NI cap; tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0);
static N_INLINE(void, sysFatal__stdZassertions_u28)(NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2687)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4708)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2693)(NimStringV2 src_p0);
extern TNimTypeV2 NTIv2__G0nbn05SIYfBos1SrkAT6g_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4490;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4490);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4708();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
static N_INLINE(void, sysFatal__stdZassertions_u28)(NimStringV2 message_p1) {
	tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
	nimfr_("sysFatal", "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system/fatal.nim");
{nimErr_ = nimErrorFlag();
	T2_ = NIM_NIL;
	T2_ = (tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g*) nimNewObj(sizeof(tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g), NIM_ALIGNOF(tyObject_AssertionDefect__G0nbn05SIYfBos1SrkAT6g));
	(*T2_).Sup.Sup.Sup.m_type = (&NTIv2__G0nbn05SIYfBos1SrkAT6g_);
	(*T2_).Sup.Sup.name = "AssertionDefect";
	nimlf_(53, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system/fatal.nim");	blitTmp = message_p1;
	nimlf_(1696, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system.nim");	eqwasMoved___system_u2687((&message_p1));
	(*T2_).Sup.Sup.message = blitTmp;
	nimlf_(53, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system/fatal.nim");	raiseExceptionEx((Exception*)T2_, "AssertionDefect", "sysFatal", "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system/fatal.nim", 53);
goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(396, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system.nim");		if (message_p1.p && !(message_p1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(message_p1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("raiseAssert", "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/std/assertions.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(36, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/std/assertions.nim");	nimlf_(1696, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/system.nim");	colontmpD_ = eqdup___system_u2693(msg_p0);
	nimlf_(36, "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/std/assertions.nim");	sysFatal__stdZassertions_u28(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
	nimfr_("failedAssertImpl", "/home/gregis/.choosenim/toolchains/nim-2.2.2/lib/std/assertions.nim");
{nimErr_ = nimErrorFlag();
	nimln_(41);	raiseAssert__stdZassertions_u26(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
