/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snico-0.4.10-f4d0514d40cc9aeaa3f02e3654986ff28d1038ec@snico@sbackends@scommon.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@m..@s..@s..@s.nimble@spkgs2@snico-0.4.10-f4d0514d40cc9aeaa3f02e3654986ff28d1038ec@snico@sbackends@scommon.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg;
typedef struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw tySequence__29c7ihdQ3dPeS9crD6M3kKQw;
typedef struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content;
typedef struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA tySequence__GyXTUZbNFl9a0ulDnQFpFoA;
typedef struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content;
typedef struct tySequence__EtvC1a2T849cB0SNWHj6Fbg tySequence__EtvC1a2T849cB0SNWHj6Fbg;
typedef struct tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content;
typedef struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg tySequence__eXQ7qBth9b8fN9aDUGBmEWLg;
typedef struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content;
typedef struct tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw;
typedef struct tySequence__QfewH7ZCzlg03Itl2jsx5w tySequence__QfewH7ZCzlg03Itl2jsx5w;
typedef struct tySequence__QfewH7ZCzlg03Itl2jsx5w_Content tySequence__QfewH7ZCzlg03Itl2jsx5w_Content;
typedef struct tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ;
typedef struct tySequence__friFxHbsLN0MVvin0IyEFg tySequence__friFxHbsLN0MVvin0IyEFg;
typedef struct tySequence__friFxHbsLN0MVvin0IyEFg_Content tySequence__friFxHbsLN0MVvin0IyEFg_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tySequence__pcXSChh0J6OCdCDPpBK9b1g tySequence__pcXSChh0J6OCdCDPpBK9b1g;
typedef struct tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content;
typedef struct tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg;
typedef struct tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg;
typedef struct tySequence__EwWnHvzGVmDuLlfmw6Igdg tySequence__EwWnHvzGVmDuLlfmw6Igdg;
typedef struct tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content;
typedef struct tyTuple__npOdd6OOX5uthJz7z22r9ag tyTuple__npOdd6OOX5uthJz7z22r9ag;
typedef struct tyTuple__hSHiEU6uEtL7soi1F4tKCg tyTuple__hSHiEU6uEtL7soi1F4tKCg;
typedef struct tyObject_Event__PhexTflZOX2N20Vr39cGsHg tyObject_Event__PhexTflZOX2N20Vr39cGsHg;
typedef struct tyTuple__FtZxsWeKlOo83uVL9c4OOmg tyTuple__FtZxsWeKlOo83uVL9c4OOmg;
typedef struct tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA;
typedef struct tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig;
typedef struct tyObject_NimRawSeq__9b6RdVy2lPuLTXrjFWjwuPQ tyObject_NimRawSeq__9b6RdVy2lPuLTXrjFWjwuPQ;
typedef struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg;
typedef struct tySequence__wgMvnlQViw7eTDXNUYd1uQ tySequence__wgMvnlQViw7eTDXNUYd1uQ;
typedef struct tySequence__wgMvnlQViw7eTDXNUYd1uQ_Content tySequence__wgMvnlQViw7eTDXNUYd1uQ_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__Orgg2tA9c9cbNS8O19aPtx6fw tySequence__Orgg2tA9c9cbNS8O19aPtx6fw;
typedef struct tySequence__Orgg2tA9c9cbNS8O19aPtx6fw_Content tySequence__Orgg2tA9c9cbNS8O19aPtx6fw_Content;
typedef struct tyObject_Table__9aIvEwU2Cxa1n9bdzP2lXknw tyObject_Table__9aIvEwU2Cxa1n9bdzP2lXknw;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug tySequence__PclZllI1Ry7MX4uStk4Jug;
typedef struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content tySequence__PclZllI1Ry7MX4uStk4Jug_Content;
typedef struct tyObject_Touch__W7l2d79afJabNHgASXk0Cqw tyObject_Touch__W7l2d79afJabNHgASXk0Cqw;
typedef struct tyTuple__A9bbISTrJh1vfJUGVCQM7pA tyTuple__A9bbISTrJh1vfJUGVCQM7pA;
typedef struct tyTuple__X9cSs7W9bNQqctODYBYs00Dg tyTuple__X9cSs7W9bNQqctODYBYs00Dg;
typedef struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q;
struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw {
  NI len; tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content* p;
};
struct tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg {
	tySequence__29c7ihdQ3dPeS9crD6M3kKQw data;
	NI counter;
};
struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA {
  NI len; tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tySequence__EtvC1a2T849cB0SNWHj6Fbg {
  NI len; tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content* p;
};
struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg {
  NI len; tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content* p;
};
struct tySequence__QfewH7ZCzlg03Itl2jsx5w {
  NI len; tySequence__QfewH7ZCzlg03Itl2jsx5w_Content* p;
};
typedef tySequence__QfewH7ZCzlg03Itl2jsx5w tyArray__4vilY9btTc3ckSe1VekvIyQ[16];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* controller_p0, void* ClE_0);
void* ClE_0;
} tyProc__9cFudSqKwo7KIwGlL9bTobiA;
struct tySequence__friFxHbsLN0MVvin0IyEFg {
  NI len; tySequence__friFxHbsLN0MVvin0IyEFg_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* tyArray__WGdFp1x1TRhEll6Qsgf9cLQ[16];
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ {
	tySequence__qwqHTkRvwhrRyENtudHQ7g data;
	NI w;
	NI h;
	NIM_BOOL hex;
	NI hexOffset;
	NI tw;
	NI th;
};
typedef tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ tyArray__uzRNaNRWdPJRp9b3rzfDPTw[16];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NF32 dt_p0, void* ClE_0);
void* ClE_0;
} tyProc__y9aUXu4JGz72YDIZVWUrK5w;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NimStringV2 text_p0, void* ClE_0);
void* ClE_0;
} tyProc__Hx0b1P9bD01T9bF9aUnykFuyA;
struct tySequence__pcXSChh0J6OCdCDPpBK9b1g {
  NI len; tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content* p;
};
typedef tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* tyArray__r4BvwNWZwrhBzTdqZDVtfw[16];
struct tySequence__EwWnHvzGVmDuLlfmw6Igdg {
  NI len; tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content* p;
};
struct tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg {
	tySequence__EwWnHvzGVmDuLlfmw6Igdg data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
struct tyTuple__hSHiEU6uEtL7soi1F4tKCg {
	NU8 Field0;
	NU8 Field1;
	NU8 Field2;
};
typedef tyTuple__hSHiEU6uEtL7soi1F4tKCg tyArray__dmDmTUzwcRf4TYNb3Z383A[256];
struct tyTuple__npOdd6OOX5uthJz7z22r9ag {
	NI Field0;
	tyArray__dmDmTUzwcRf4TYNb3Z383A Field1;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NI sym_p0, NU16 mods_p1, NI scancode_p2, NIM_BOOL down_p3, void* ClE_0);
void* ClE_0;
} tyProc__SR0j0ClEYDvwlJHrgLh3cQ;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (tyObject_Event__PhexTflZOX2N20Vr39cGsHg* e_p0, void* ClE_0);
void* ClE_0;
} tyProc__WgqeCw2WGxAI9bmI3lHRKog;
typedef NU8 tyEnum_StencilMode__Z5mtRazbs9bHFC9clx6mOjww;
typedef NU8 tyEnum_StencilBlend__9bI9bGpXIhdEoV89aCfnxkzSQ;
typedef NI32 tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A;
typedef NU8 tyEnum_DitherMode__qddd9bcPRohUdqi2yBml8IQ;
typedef NI tyArray__AM6k89cr9c1T2mNMufYfM0Rg[256];
typedef NIM_BOOL tyArray__JLIwlu3xtaWK9coqUZvph4Q[256];
struct tyTuple__FtZxsWeKlOo83uVL9c4OOmg {
	NI Field0;
	NI Field1;
	NI Field2;
	NI Field3;
};
typedef NIM_BOOL tyArray__xSxqoPo7Fj4uIDcWiYyWDg[3];
typedef NI tyArray__Bd4h7Ocx9bGTvrKzPIWNlHw[3];
struct tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA {
	NimStringV2 name;
	tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig start;
	NI64 time;
	NI count;
	tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA* parent;
	tySequence__EwWnHvzGVmDuLlfmw6Igdg children;
};
struct tyObject_NimRawSeq__9b6RdVy2lPuLTXrjFWjwuPQ {
	NI len;
	void* p;
};
struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg {
	NI rc;
	NI rootIdx;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI x_p0, NI y_p1, void* ClE_0);
void* ClE_0;
} tyProc__yZbvgbtLeGIhzIA9bifjdPw;
struct tySequence__wgMvnlQViw7eTDXNUYd1uQ {
  NI len; tySequence__wgMvnlQViw7eTDXNUYd1uQ_Content* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw {
	tySequence__wgMvnlQViw7eTDXNUYd1uQ palette;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data;
	NI channels;
	NI w;
	NI h;
	NI tw;
	NI th;
	NimStringV2 filename;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ spriteFlags;
};
struct tySequence__Orgg2tA9c9cbNS8O19aPtx6fw {
  NI len; tySequence__Orgg2tA9c9cbNS8O19aPtx6fw_Content* p;
};
struct tyObject_Table__9aIvEwU2Cxa1n9bdzP2lXknw {
	tySequence__Orgg2tA9c9cbNS8O19aPtx6fw data;
	NI counter;
};
struct tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg {
	tyObject_Table__9aIvEwU2Cxa1n9bdzP2lXknw rects;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data;
	NI w;
	NI h;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_EventKind__JxOY15B8aYUlZq6hKuO3VA;
typedef NI32 tyEnum_Keycode__3ENka4Td3JjGlKkKWwkaRw;
struct tyObject_Event__PhexTflZOX2N20Vr39cGsHg {
	tyEnum_EventKind__JxOY15B8aYUlZq6hKuO3VA kind;
	NU8 button;
	NI x;
	NI y;
	NF32 xrel;
	NF32 yrel;
	tyEnum_Keycode__3ENka4Td3JjGlKkKWwkaRw keycode;
	tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A scancode;
	NU16 mods;
	NU8 clicks;
	NI repeat;
	NI ywheel;
	NimStringV2 text;
	NU8 which;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug {
  NI len; tySequence__PclZllI1Ry7MX4uStk4Jug_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__PclZllI1Ry7MX4uStk4Jug trace;
	Exception* up;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tyEnum_TouchState__qs77bc9bzmEAAXZGKPDZsgg;
struct tyObject_Touch__W7l2d79afJabNHgASXk0Cqw {
	NI id;
	NI x;
	NI y;
	NF32 sx;
	NF32 sy;
	NF32 xrel;
	NF32 yrel;
	NF32 xrelraw;
	NF32 yrelraw;
	tyEnum_TouchState__qs77bc9bzmEAAXZGKPDZsgg state;
};
struct tyTuple__A9bbISTrJh1vfJUGVCQM7pA {
	NI Field0;
	tyEnum_Keycode__3ENka4Td3JjGlKkKWwkaRw Field1;
	NU32 Field2;
};
struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content { NI cap; tyTuple__A9bbISTrJh1vfJUGVCQM7pA data[SEQ_DECL_SIZE]; };
struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content { NI cap; tyObject_Touch__W7l2d79afJabNHgASXk0Cqw data[SEQ_DECL_SIZE]; };
struct tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content { NI cap; tyProc__SR0j0ClEYDvwlJHrgLh3cQ data[SEQ_DECL_SIZE]; };
struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content { NI cap; tyProc__WgqeCw2WGxAI9bmI3lHRKog data[SEQ_DECL_SIZE]; };
struct tySequence__QfewH7ZCzlg03Itl2jsx5w_Content { NI cap; tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A data[SEQ_DECL_SIZE]; };
struct tySequence__friFxHbsLN0MVvin0IyEFg_Content { NI cap; tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content { NI cap; tyProc__yZbvgbtLeGIhzIA9bifjdPw data[SEQ_DECL_SIZE]; };
struct tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content { NI cap; tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA data[SEQ_DECL_SIZE]; };
struct tySequence__wgMvnlQViw7eTDXNUYd1uQ_Content { NI cap; tyTuple__hSHiEU6uEtL7soi1F4tKCg data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyTuple__X9cSs7W9bNQqctODYBYs00Dg {
	NI Field0;
	NI32 Field1;
	tyTuple__FtZxsWeKlOo83uVL9c4OOmg Field2;
};
struct tySequence__Orgg2tA9c9cbNS8O19aPtx6fw_Content { NI cap; tyTuple__X9cSs7W9bNQqctODYBYs00Dg data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__PclZllI1Ry7MX4uStk4Jug_Content { NI cap; tyObject_StackTraceEntry__DppJCFaZRvent8fPJeLs4Q data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg, initTable__pkgZnicoZbackendsZcommon_u93)(NI initialSize_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u187)(tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
static N_INLINE(NF, slash___system_u1693)(NI x_p0, NI y_p1);
static N_INLINE(NF, toFloat__system_u1681)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg, initRingBuffer__pkgZnicoZbackendsZcommon_u1725)(NI length_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1852)(tySequence__EwWnHvzGVmDuLlfmw6Igdg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1921)(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3229)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pkgZnicoZbackendsZcommon_u3249)(tySequence__qwqHTkRvwhrRyENtudHQ7g* s_p0, NI newlen_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3018)(tySequence__friFxHbsLN0MVvin0IyEFg dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZcontroller_u86)(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
N_LIB_PRIVATE N_NIMCALL(NF32, lerp__pkgZnicoZbackendsZsdl2_u5853)(NF32 a_p0, NF32 b_p1, NF32 t_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1125)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1143)(tySequence__wgMvnlQViw7eTDXNUYd1uQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2595)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw*, new__pkgZnicoZbackendsZcommon_u1095)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u2604)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__pkgZnicoZbackendsZcommon_u1280)(NI len_p0);
static N_INLINE(void, nimIncRef)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3629)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3647)(tySequence__Orgg2tA9c9cbNS8O19aPtx6fw dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3528)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, mapRGB__pkgZnicoZbackendsZcommon_u1438)(NU8 r_p0, NU8 g_p1, NU8 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, mapRGBA__pkgZnicoZbackendsZcommon_u1569)(NU8 r_p0, NU8 g_p1, NU8 b_p2, NU8 a_p3);
static N_INLINE(NU8, max__pkgZnicoZbackendsZcommon_u812)(NU8 x_p0, NU8 y_p1);
static N_INLINE(NU8, min__pkgZnicoZbackendsZcommon_u822)(NU8 x_p0, NU8 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2751)(tySequence__QfewH7ZCzlg03Itl2jsx5w dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static NIM_CONST tyProc__HzVCwACFYM9cx9aV62PdjtuA TM__YTEtjZksCHMwTR9aj14QpVQ_2 = {NIM_NIL,NIM_NIL};
extern TNimTypeV2 NTIv2__XEycrCsme5C8CVWAYEcdBQ_;
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__YTEtjZksCHMwTR9aj14QpVQ_3 = { 38 | NIM_STRLIT_FLAG, "Converting non RGBA surface to indexed" };
static const NimStringV2 TM__YTEtjZksCHMwTR9aj14QpVQ_4 = {38, (NimStrPayload*)&TM__YTEtjZksCHMwTR9aj14QpVQ_3};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__YTEtjZksCHMwTR9aj14QpVQ_5 = { 10 | NIM_STRLIT_FLAG, "channels: " };
static const NimStringV2 TM__YTEtjZksCHMwTR9aj14QpVQ_6 = {10, (NimStrPayload*)&TM__YTEtjZksCHMwTR9aj14QpVQ_5};
N_LIB_PRIVATE tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg keysDown__pkgZnicoZbackendsZcommon_u244;
N_LIB_PRIVATE tySequence__GyXTUZbNFl9a0ulDnQFpFoA touches__pkgZnicoZbackendsZcommon_u862;
N_LIB_PRIVATE tyProc__HzVCwACFYM9cx9aV62PdjtuA audioTickCallback__pkgZnicoZbackendsZcommon_u870;
N_LIB_PRIVATE tySequence__EtvC1a2T849cB0SNWHj6Fbg keyListeners__pkgZnicoZbackendsZcommon_u879;
N_LIB_PRIVATE tySequence__eXQ7qBth9b8fN9aDUGBmEWLg eventListeners__pkgZnicoZbackendsZcommon_u884;
N_LIB_PRIVATE tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* swCanvas__pkgZnicoZbackendsZcommon_u888;
N_LIB_PRIVATE tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* stencilBuffer__pkgZnicoZbackendsZcommon_u889;
N_LIB_PRIVATE tyArray__4vilY9btTc3ckSe1VekvIyQ keymap__pkgZnicoZbackendsZcommon_u989;
N_LIB_PRIVATE tyProc__9cFudSqKwo7KIwGlL9bTobiA controllerAddedFunc__pkgZnicoZbackendsZcommon_u992;
N_LIB_PRIVATE tyProc__9cFudSqKwo7KIwGlL9bTobiA controllerRemovedFunc__pkgZnicoZbackendsZcommon_u995;
N_LIB_PRIVATE tySequence__friFxHbsLN0MVvin0IyEFg controllers__pkgZnicoZbackendsZcommon_u996;
N_LIB_PRIVATE NimStringV2 basePath__pkgZnicoZbackendsZcommon_u1020;
N_LIB_PRIVATE NimStringV2 assetPath__pkgZnicoZbackendsZcommon_u1021;
N_LIB_PRIVATE NimStringV2 writePath__pkgZnicoZbackendsZcommon_u1022;
N_LIB_PRIVATE tyArray__WGdFp1x1TRhEll6Qsgf9cLQ spritesheets__pkgZnicoZbackendsZcommon_u1024;
N_LIB_PRIVATE tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* spritesheet__pkgZnicoZbackendsZcommon_u1025;
N_LIB_PRIVATE tyArray__uzRNaNRWdPJRp9b3rzfDPTw tilemaps__pkgZnicoZbackendsZcommon_u1026;
N_LIB_PRIVATE tyProc__HzVCwACFYM9cx9aV62PdjtuA initFunc__pkgZnicoZbackendsZcommon_u1029;
N_LIB_PRIVATE tyProc__y9aUXu4JGz72YDIZVWUrK5w updateFunc__pkgZnicoZbackendsZcommon_u1033;
N_LIB_PRIVATE tyProc__HzVCwACFYM9cx9aV62PdjtuA drawFunc__pkgZnicoZbackendsZcommon_u1035;
N_LIB_PRIVATE tyProc__Hx0b1P9bD01T9bF9aUnykFuyA textFunc__pkgZnicoZbackendsZcommon_u1038;
N_LIB_PRIVATE tySequence__pcXSChh0J6OCdCDPpBK9b1g resizeFuncs__pkgZnicoZbackendsZcommon_u1039;
N_LIB_PRIVATE tyArray__r4BvwNWZwrhBzTdqZDVtfw fonts__pkgZnicoZbackendsZcommon_u1040;
N_LIB_PRIVATE tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* currentFont__pkgZnicoZbackendsZcommon_u1041;
N_LIB_PRIVATE tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg profileHistory__pkgZnicoZbackendsZcommon_u1942;
N_LIB_PRIVATE NI gifScale__pkgZnicoZbackendsZcommon_u16 = ((NI)2);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
N_LIB_PRIVATE NIM_BOOL aKeyWasPressed__pkgZnicoZbackendsZcommon_u245;
N_LIB_PRIVATE NIM_BOOL aKeyWasReleased__pkgZnicoZbackendsZcommon_u246;
N_LIB_PRIVATE tyTuple__npOdd6OOX5uthJz7z22r9ag currentPalette__pkgZnicoZbackendsZcommon_u861;
N_LIB_PRIVATE NIM_BOOL touchMouseEmulation__pkgZnicoZbackendsZcommon_u863 = NIM_FALSE;
N_LIB_PRIVATE NF32 masterVolume__pkgZnicoZbackendsZcommon_u864 = 1.0f;
N_LIB_PRIVATE NF32 sfxVolume__pkgZnicoZbackendsZcommon_u865 = 1.0f;
N_LIB_PRIVATE NF32 musicVolume__pkgZnicoZbackendsZcommon_u866 = 1.0f;
N_LIB_PRIVATE NF32 sampleRate__pkgZnicoZbackendsZcommon_u867 = 44100.0f;
N_LIB_PRIVATE NF32 invSampleRate__pkgZnicoZbackendsZcommon_u868;
N_LIB_PRIVATE NI currentBpm__pkgZnicoZbackendsZcommon_u871 = ((NI)128);
N_LIB_PRIVATE NI currentTpb__pkgZnicoZbackendsZcommon_u872 = ((NI)4);
N_LIB_PRIVATE NIM_BOOL initialized__pkgZnicoZbackendsZcommon_u873;
N_LIB_PRIVATE NIM_BOOL running__pkgZnicoZbackendsZcommon_u874;
N_LIB_PRIVATE NI loading__pkgZnicoZbackendsZcommon_u885;
N_LIB_PRIVATE NI cursorX__pkgZnicoZbackendsZcommon_u886 = ((NI)0);
N_LIB_PRIVATE NI cursorY__pkgZnicoZbackendsZcommon_u887 = ((NI)0);
N_LIB_PRIVATE tyEnum_StencilMode__Z5mtRazbs9bHFC9clx6mOjww stencilMode__pkgZnicoZbackendsZcommon_u911 = ((tyEnum_StencilMode__Z5mtRazbs9bHFC9clx6mOjww)1);
N_LIB_PRIVATE NIM_BOOL stencilWrite__pkgZnicoZbackendsZcommon_u912 = NIM_FALSE;
N_LIB_PRIVATE NIM_BOOL stencilWriteFail__pkgZnicoZbackendsZcommon_u913 = NIM_FALSE;
N_LIB_PRIVATE NIM_BOOL stencilOnly__pkgZnicoZbackendsZcommon_u914 = NIM_FALSE;
N_LIB_PRIVATE NU8 stencilRef__pkgZnicoZbackendsZcommon_u915 = ((NU8)0);
N_LIB_PRIVATE tyEnum_StencilBlend__9bI9bGpXIhdEoV89aCfnxkzSQ stencilBlend__pkgZnicoZbackendsZcommon_u916 = ((tyEnum_StencilBlend__9bI9bGpXIhdEoV89aCfnxkzSQ)0);
N_LIB_PRIVATE NI targetScreenWidth__pkgZnicoZbackendsZcommon_u917 = ((NI)128);
N_LIB_PRIVATE NI targetScreenHeight__pkgZnicoZbackendsZcommon_u918 = ((NI)128);
N_LIB_PRIVATE NIM_BOOL fixedScreenSize__pkgZnicoZbackendsZcommon_u919 = NIM_TRUE;
N_LIB_PRIVATE NIM_BOOL integerScreenScale__pkgZnicoZbackendsZcommon_u920 = NIM_FALSE;
N_LIB_PRIVATE NI screenWidth__pkgZnicoZbackendsZcommon_u921 = ((NI)128);
N_LIB_PRIVATE NI screenHeight__pkgZnicoZbackendsZcommon_u922 = ((NI)128);
N_LIB_PRIVATE NI screenPaddingX__pkgZnicoZbackendsZcommon_u923 = ((NI)0);
N_LIB_PRIVATE NI screenPaddingY__pkgZnicoZbackendsZcommon_u924 = ((NI)0);
N_LIB_PRIVATE NIM_BOOL focused__pkgZnicoZbackendsZcommon_u997 = NIM_TRUE;
N_LIB_PRIVATE NI recordSeconds__pkgZnicoZbackendsZcommon_u998 = ((NI)30);
N_LIB_PRIVATE NIM_BOOL fullSpeedGif__pkgZnicoZbackendsZcommon_u999 = NIM_TRUE;
N_LIB_PRIVATE NI mixerChannels__pkgZnicoZbackendsZcommon_u1000 = ((NI)0);
N_LIB_PRIVATE NU16 gDitherPattern__pkgZnicoZbackendsZcommon_u1009 = ((NU16)65535);
N_LIB_PRIVATE tyEnum_DitherMode__qddd9bcPRohUdqi2yBml8IQ gDitherMode__pkgZnicoZbackendsZcommon_u1010;
N_LIB_PRIVATE NI gDitherADitherA__pkgZnicoZbackendsZcommon_u1011 = ((NI)149);
N_LIB_PRIVATE NI gDitherADitherB__pkgZnicoZbackendsZcommon_u1012 = ((NI)1234);
N_LIB_PRIVATE NI gDitherADitherC__pkgZnicoZbackendsZcommon_u1013 = ((NI)511);
N_LIB_PRIVATE NF32 gDitherADitherInput__pkgZnicoZbackendsZcommon_u1014 = 1.0f;
N_LIB_PRIVATE NI gDitherOffsetX__pkgZnicoZbackendsZcommon_u1015 = ((NI)0);
N_LIB_PRIVATE NI gDitherOffsetY__pkgZnicoZbackendsZcommon_u1016 = ((NI)0);
N_LIB_PRIVATE NI frameRate__pkgZnicoZbackendsZcommon_u1017 = ((NI)60);
N_LIB_PRIVATE NF timeStep__pkgZnicoZbackendsZcommon_u1018;
N_LIB_PRIVATE NI frameMult__pkgZnicoZbackendsZcommon_u1019 = ((NI)1);
N_LIB_PRIVATE NF screenScale__pkgZnicoZbackendsZcommon_u1023 = 4.0;
N_LIB_PRIVATE tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ* currentTilemap__pkgZnicoZbackendsZcommon_u1027;
N_LIB_PRIVATE NIM_BOOL initFuncCalled__pkgZnicoZbackendsZcommon_u1030 = NIM_FALSE;
N_LIB_PRIVATE NI currentFontId__pkgZnicoZbackendsZcommon_u1042;
N_LIB_PRIVATE NI frame__pkgZnicoZbackendsZcommon_u1043 = ((NI)0);
N_LIB_PRIVATE NI32 cameraX__pkgZnicoZbackendsZcommon_u1044 = ((NI32)0);
N_LIB_PRIVATE NI32 cameraY__pkgZnicoZbackendsZcommon_u1045 = ((NI32)0);
N_LIB_PRIVATE tyArray__AM6k89cr9c1T2mNMufYfM0Rg paletteMapDraw__pkgZnicoZbackendsZcommon_u1046;
N_LIB_PRIVATE tyArray__AM6k89cr9c1T2mNMufYfM0Rg paletteMapDisplay__pkgZnicoZbackendsZcommon_u1047;
N_LIB_PRIVATE tyArray__JLIwlu3xtaWK9coqUZvph4Q paletteTransparent__pkgZnicoZbackendsZcommon_u1048;
N_LIB_PRIVATE NI i__pkgZnicoZbackendsZcommon_u1053;
N_LIB_PRIVATE NI currentColor__pkgZnicoZbackendsZcommon_u1054 = ((NI)0);
N_LIB_PRIVATE NIM_BOOL keepRunning__pkgZnicoZbackendsZcommon_u1055 = NIM_TRUE;
N_LIB_PRIVATE NIM_BOOL muteAudio__pkgZnicoZbackendsZcommon_u1056 = NIM_FALSE;
N_LIB_PRIVATE NI currentMusicId__pkgZnicoZbackendsZcommon_u1057 = ((NI)-1);
N_LIB_PRIVATE NI clipMinX__pkgZnicoZbackendsZcommon_u1058;
N_LIB_PRIVATE NI clipMaxX__pkgZnicoZbackendsZcommon_u1059;
N_LIB_PRIVATE NI clipMinY__pkgZnicoZbackendsZcommon_u1060;
N_LIB_PRIVATE NI clipMaxY__pkgZnicoZbackendsZcommon_u1061;
N_LIB_PRIVATE tyTuple__FtZxsWeKlOo83uVL9c4OOmg clippingRect__pkgZnicoZbackendsZcommon_u1062;
N_LIB_PRIVATE NIM_BOOL mouseDetected__pkgZnicoZbackendsZcommon_u1063;
N_LIB_PRIVATE NI mouseX__pkgZnicoZbackendsZcommon_u1064;
N_LIB_PRIVATE NI mouseY__pkgZnicoZbackendsZcommon_u1065;
N_LIB_PRIVATE NI mouseRawX__pkgZnicoZbackendsZcommon_u1066;
N_LIB_PRIVATE NI mouseRawY__pkgZnicoZbackendsZcommon_u1067;
N_LIB_PRIVATE NF32 mouseRelX__pkgZnicoZbackendsZcommon_u1068;
N_LIB_PRIVATE NF32 mouseRelY__pkgZnicoZbackendsZcommon_u1069;
N_LIB_PRIVATE NI lastMouseX__pkgZnicoZbackendsZcommon_u1070;
N_LIB_PRIVATE NI lastMouseY__pkgZnicoZbackendsZcommon_u1071;
N_LIB_PRIVATE NI lastMouseRawX__pkgZnicoZbackendsZcommon_u1072;
N_LIB_PRIVATE NI lastMouseRawY__pkgZnicoZbackendsZcommon_u1073;
N_LIB_PRIVATE tyArray__xSxqoPo7Fj4uIDcWiYyWDg mouseButtonsDown__pkgZnicoZbackendsZcommon_u1074;
N_LIB_PRIVATE tyArray__Bd4h7Ocx9bGTvrKzPIWNlHw mouseButtons__pkgZnicoZbackendsZcommon_u1075;
N_LIB_PRIVATE NI mouseWheelState__pkgZnicoZbackendsZcommon_u1076;
N_LIB_PRIVATE NIM_BOOL profileCollect__pkgZnicoZbackendsZcommon_u1710 = NIM_TRUE;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NF, toFloat__system_u1681)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
static N_INLINE(NF, slash___system_u1693)(NI x_p0, NI y_p1) {
	NF result;
	NF T1_;
	NF T2_;
	T1_ = (NF)0;
	T1_ = toFloat__system_u1681(x_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1681(y_p1);
	result = ((NF)(T1_) / (NF)(T2_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1852)(tySequence__EwWnHvzGVmDuLlfmw6Igdg dest_p0) {
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].name.p && !(dest_p0.p->data[colontmp_].name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].name.p);
}
			eqdestroy___pkgZnicoZbackendsZcommon_u1852(dest_p0.p->data[colontmp_].children);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA));
}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1828)(tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	if ((*dest_p0).name.p && !((*dest_p0).name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name.p);
}
	eqdestroy___pkgZnicoZbackendsZcommon_u1852((*dest_p0).children);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3229)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NI));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZcommon_u3238)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___pkgZnicoZbackendsZcommon_u3229((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZbackendsZcommon_u3226)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, eqdup___pkgZnicoZbackendsZcommon_u3235)(tySequence__qwqHTkRvwhrRyENtudHQ7g src_p0) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__pkgZnicoZbackendsZcommon_u3249((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			result.p->data[colontmp_] = src_p0.p->data[colontmp_];
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__9b6RdVy2lPuLTXrjFWjwuPQ*) (x_p0))).p == (*((tyObject_NimRawSeq__9b6RdVy2lPuLTXrjFWjwuPQ*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZnicoZbackendsZcommon_u3232)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pkgZnicoZbackendsZcommon_u3249((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((NI32)((*cell).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3018)(tySequence__friFxHbsLN0MVvin0IyEFg dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___pkgZnicoZcontroller_u86(dest_p0.p->data[colontmp_]);
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZcommon_u3027)(tySequence__friFxHbsLN0MVvin0IyEFg* dest_p0, tySequence__friFxHbsLN0MVvin0IyEFg src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___pkgZnicoZbackendsZcommon_u3018((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* h;
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	h = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T1_));
	(*h).rc += ((NI)16);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pkgZnicoZbackendsZcommon_u3513)(tyProc__yZbvgbtLeGIhzIA9bifjdPw src_p0, NIM_BOOL cyclic_p1, tyProc__yZbvgbtLeGIhzIA9bifjdPw* Result) {
	void* colontmp_;
	nimZeroMem((void*)Result, sizeof(tyProc__yZbvgbtLeGIhzIA9bifjdPw));
	colontmp_ = (*Result).ClE_0;
	(*Result).ClE_0 = src_p0.ClE_0;
	(*Result).ClP_0 = src_p0.ClP_0;
	{
		if (!src_p0.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p0.ClE_0, cyclic_p1);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NF32, note__pkgZnicoZbackendsZcommon_u718)(NI n_p0) {
	NF32 result;
	NF T1_;
{	T1_ = (NF)0;
	T1_ = pow(2.0, ((NF)(((NF)(((NF) (((NF32) (n_p0))))) - (NF)(69.0))) / (NF)(12.0)));
	result = ((NF32) (((NF)(T1_) * (NF)(440.0))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF32, lerp__pkgZnicoZbackendsZsdl2_u5853)(NF32 a_p0, NF32 b_p1, NF32 t_p2) {
	NF32 result;
{	result = ((NF32)(a_p0) + (NF32)(((NF32)(((NF32)(b_p1) - (NF32)(a_p0))) * (NF32)(t_p2))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF32, interpolatedLookup__pkgZnicoZbackendsZsdl2_u6004)(NF32* a_p0, NI a_p0Len_0, NF32 s_p1) {
	NF32 result;
	NF alpha;
	NI sample;
	NI nextSample;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF32)0;
	alpha = fmod(((NF) (s_p1)), 1.0);
	sample = (NI)(((NI) (s_p1)) % a_p0Len_0);
	nextSample = (NI)((NI)(sample + ((NI)1)) % a_p0Len_0);
	result = lerp__pkgZnicoZbackendsZsdl2_u5853(a_p0[sample], a_p0[nextSample], ((NF32) (alpha)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__hSHiEU6uEtL7soi1F4tKCg, RGB__pkgZnicoZbackendsZcommon_u1678)(NI32 r_p0, NI32 g_p1, NI32 b_p2) {
	tyTuple__hSHiEU6uEtL7soi1F4tKCg result;
	NU8 colontmp_;
	NU8 colontmp__2;
	NU8 colontmp__3;
{	nimZeroMem((void*)(&result), sizeof(tyTuple__hSHiEU6uEtL7soi1F4tKCg));
	colontmp_ = ((NU8) (r_p0));
	colontmp__2 = ((NU8) (g_p1));
	colontmp__3 = ((NU8) (b_p2));
	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	result.Field2 = colontmp__3;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1143)(tySequence__wgMvnlQViw7eTDXNUYd1uQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__hSHiEU6uEtL7soi1F4tKCg));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1125)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* dest_p0) {
	eqdestroy___pkgZnicoZbackendsZcommon_u1143((*dest_p0).palette);
	eqdestroy___pureZtimes_u2595((*dest_p0).data);
	if ((*dest_p0).filename.p && !((*dest_p0).filename.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).filename.p);
}
	eqdestroy___pureZtimes_u2595((*dest_p0).spriteFlags);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZcommon_u1116)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw** dest_p0, tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnicoZbackendsZcommon_u1125((*dest_p0));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1107)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnicoZbackendsZcommon_u1125(dest_p0);
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZbackendsZcommon_u1104)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw*, newSurface__pkgZnicoZbackendsZcommon_u1091)(NI w_p0, NI h_p1) {
	tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T1_;
	result = new__pkgZnicoZbackendsZcommon_u1095();
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = newSeq__pkgZnicoZbackendsZcommon_u1280(((NI)(w_p0 * h_p1)));
	eqsink___pureZtimes_u2604((&(*result).data), T1_);
	(*result).channels = ((NI)1);
	(*result).w = w_p0;
	(*result).h = h_p1;
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	(*((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T1_))).rc += ((NI)16);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZnicoZbackendsZcommon_u1110)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw** dest_p0, tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pkgZnicoZbackendsZcommon_u1125((*dest_p0));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3629)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* dest_p0) {
	eqdestroy___pkgZnicoZbackendsZcommon_u3647((*dest_p0).rects.data);
	eqdestroy___pureZtimes_u2595((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZcommon_u3789)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg** dest_p0, tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnicoZbackendsZcommon_u3629((*dest_p0));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3780)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZnicoZbackendsZcommon_u3629(dest_p0);
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZbackendsZcommon_u3777)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZbackendsZcommon_u3840)(tyTuple__FtZxsWeKlOo83uVL9c4OOmg* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1 = 0;
	(*dest_p0).Field2 = 0;
	(*dest_p0).Field3 = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZnicoZbackendsZcommon_u3783)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg** dest_p0, tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pkgZnicoZbackendsZcommon_u3629((*dest_p0));
		nimRawDispose((*dest_p0), ((NI)4));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
		rememberCycle__system_u3528(result, cell, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZnicoZbackendsZcommon_u3378)(tyProc__y9aUXu4JGz72YDIZVWUrK5w* dest_p0, tyProc__y9aUXu4JGz72YDIZVWUrK5w src_p1, NIM_BOOL cyclic_p2) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	{
		if (!src_p1.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p1.ClE_0, cyclic_p2);
	}
LA3_: ;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u3412)(tyObject_Event__PhexTflZOX2N20Vr39cGsHg* dest_p0) {
	if ((*dest_p0).text.p && !((*dest_p0).text.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).text.p);
}
}
N_LIB_PRIVATE N_NIMCALL(NI, mapRGB__pkgZnicoZbackendsZcommon_u1438)(NU8 r_p0, NU8 g_p1, NU8 b_p2) {
	NI result;
	NI bestIndex;
	NI smallestDiff;
{	{
		NI i;
		tyTuple__hSHiEU6uEtL7soi1F4tKCg v;
		NI i_2;
		i = (NI)0;
		nimZeroMem((void*)(&v), sizeof(tyTuple__hSHiEU6uEtL7soi1F4tKCg));
		i_2 = ((NI)0);
		{
			while (1) {
				i = i_2;
				v = currentPalette__pkgZnicoZbackendsZcommon_u861.Field1[(i_2)- 0];
				{
					NIM_BOOL T6_;
					NIM_BOOL T7_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NIM_BOOL)0;
					T7_ = (v.Field0 == r_p0);
					if (!(T7_)) goto LA8_;
					T7_ = (v.Field1 == g_p1);
LA8_: ;
					T6_ = T7_;
					if (!(T6_)) goto LA9_;
					T6_ = (v.Field2 == b_p2);
LA9_: ;
					if (!T6_) goto LA10_;
					result = i;
					goto BeforeRet_;
				}
LA10_: ;
				{
					if (!(((NI)255) <= i_2)) goto LA14_;
					goto LA2;
				}
LA14_: ;
				i_2 += ((NI)1);
			}
		} LA2: ;
	}
	bestIndex = ((NI)0);
	smallestDiff = ((NI)99999);
	{
		NI i_3;
		tyTuple__hSHiEU6uEtL7soi1F4tKCg v_2;
		NI i_4;
		i_3 = (NI)0;
		nimZeroMem((void*)(&v_2), sizeof(tyTuple__hSHiEU6uEtL7soi1F4tKCg));
		i_4 = ((NI)0);
		{
			while (1) {
				NI rdiff;
				NI gdiff;
				NI bdiff;
				NI diff;
				i_3 = i_4;
				v_2 = currentPalette__pkgZnicoZbackendsZcommon_u861.Field1[(i_4)- 0];
				rdiff = ((NI)(((NI) (v_2.Field0)) - ((NI) (r_p0))) > 0? ((NI)(((NI) (v_2.Field0)) - ((NI) (r_p0)))) : -((NI)(((NI) (v_2.Field0)) - ((NI) (r_p0)))));
				gdiff = ((NI)(((NI) (v_2.Field1)) - ((NI) (g_p1))) > 0? ((NI)(((NI) (v_2.Field1)) - ((NI) (g_p1)))) : -((NI)(((NI) (v_2.Field1)) - ((NI) (g_p1)))));
				bdiff = ((NI)(((NI) (v_2.Field2)) - ((NI) (b_p2))) > 0? ((NI)(((NI) (v_2.Field2)) - ((NI) (b_p2)))) : -((NI)(((NI) (v_2.Field2)) - ((NI) (b_p2)))));
				diff = (NI)((NI)(rdiff + gdiff) + bdiff);
				{
					if (!(diff < smallestDiff)) goto LA21_;
					smallestDiff = diff;
					bestIndex = i_3;
				}
LA21_: ;
				{
					if (!(((NI)255) <= i_4)) goto LA25_;
					goto LA17;
				}
LA25_: ;
				i_4 += ((NI)1);
			}
		} LA17: ;
	}
	result = bestIndex;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mapRGBA__pkgZnicoZbackendsZcommon_u1569)(NU8 r_p0, NU8 g_p1, NU8 b_p2, NU8 a_p3) {
	NI result;
	NI bestIndex;
	NI smallestDiff;
{	{
		NI i;
		tyTuple__hSHiEU6uEtL7soi1F4tKCg v;
		NI i_2;
		i = (NI)0;
		nimZeroMem((void*)(&v), sizeof(tyTuple__hSHiEU6uEtL7soi1F4tKCg));
		i_2 = ((NI)0);
		{
			while (1) {
				i = i_2;
				v = currentPalette__pkgZnicoZbackendsZcommon_u861.Field1[(i_2)- 0];
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = (a_p3 == ((NU8)0));
					if (!(T6_)) goto LA7_;
					T6_ = (i == ((NI)0));
LA7_: ;
					if (!T6_) goto LA8_;
					result = i;
					goto BeforeRet_;
				}
				goto LA4_;
LA8_: ;
				{
					NIM_BOOL T11_;
					NIM_BOOL T12_;
					NIM_BOOL T13_;
					T11_ = (NIM_BOOL)0;
					T12_ = (NIM_BOOL)0;
					T13_ = (NIM_BOOL)0;
					T13_ = !((i == ((NI)0)));
					if (!(T13_)) goto LA14_;
					T13_ = (v.Field0 == r_p0);
LA14_: ;
					T12_ = T13_;
					if (!(T12_)) goto LA15_;
					T12_ = (v.Field1 == g_p1);
LA15_: ;
					T11_ = T12_;
					if (!(T11_)) goto LA16_;
					T11_ = (v.Field2 == b_p2);
LA16_: ;
					if (!T11_) goto LA17_;
					result = i;
					goto BeforeRet_;
				}
				goto LA4_;
LA17_: ;
LA4_: ;
				{
					if (!(((NI)255) <= i_2)) goto LA21_;
					goto LA2;
				}
LA21_: ;
				i_2 += ((NI)1);
			}
		} LA2: ;
	}
	bestIndex = ((NI)0);
	smallestDiff = ((NI)99999);
	{
		NI i_3;
		tyTuple__hSHiEU6uEtL7soi1F4tKCg v_2;
		NI i_4;
		i_3 = (NI)0;
		nimZeroMem((void*)(&v_2), sizeof(tyTuple__hSHiEU6uEtL7soi1F4tKCg));
		i_4 = ((NI)0);
		{
			while (1) {
				NI rdiff;
				NI gdiff;
				NI bdiff;
				NI diff;
				i_3 = i_4;
				v_2 = currentPalette__pkgZnicoZbackendsZcommon_u861.Field1[(i_4)- 0];
				rdiff = ((NI)(((NI) (v_2.Field0)) - ((NI) (r_p0))) > 0? ((NI)(((NI) (v_2.Field0)) - ((NI) (r_p0)))) : -((NI)(((NI) (v_2.Field0)) - ((NI) (r_p0)))));
				gdiff = ((NI)(((NI) (v_2.Field1)) - ((NI) (g_p1))) > 0? ((NI)(((NI) (v_2.Field1)) - ((NI) (g_p1)))) : -((NI)(((NI) (v_2.Field1)) - ((NI) (g_p1)))));
				bdiff = ((NI)(((NI) (v_2.Field2)) - ((NI) (b_p2))) > 0? ((NI)(((NI) (v_2.Field2)) - ((NI) (b_p2)))) : -((NI)(((NI) (v_2.Field2)) - ((NI) (b_p2)))));
				diff = (NI)((NI)(rdiff + gdiff) + bdiff);
				{
					if (!(diff < smallestDiff)) goto LA28_;
					smallestDiff = diff;
					bestIndex = i_3;
				}
LA28_: ;
				{
					if (!(((NI)255) <= i_4)) goto LA32_;
					goto LA24;
				}
LA32_: ;
				i_4 += ((NI)1);
			}
		} LA24: ;
	}
	result = bestIndex;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw*, convertToIndexed__pkgZnicoZbackendsZcommon_u1597)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* surface_p0) {
	tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* result;
	NimStringV2 colontmpD_;
	tyArray__Re75IspeoxXy2oCZHwcRrA T9_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		Exception* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = (((NI)4) < (*surface_p0).channels);
		if (T4_) goto LA5_;
		T4_ = ((*surface_p0).channels < ((NI)3));
LA5_: ;
		if (!T4_) goto LA6_;
		T8_ = NIM_NIL;
		T8_ = (Exception*) nimNewObj(sizeof(Exception), NIM_ALIGNOF(Exception));
		(*T8_).Sup.m_type = (&NTIv2__XEycrCsme5C8CVWAYEcdBQ_);
		(*T8_).name = "Exception";
		(*T8_).message = TM__YTEtjZksCHMwTR9aj14QpVQ_4;
		(*T8_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T8_, "Exception", "convertToIndexed", "common.nim", 571);
goto LA1_;
	}
LA6_: ;
	T9_[0] = TM__YTEtjZksCHMwTR9aj14QpVQ_6;
	colontmpD_ = dollar___systemZdollars_u8((*surface_p0).channels);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[1] = colontmpD_;
	echoBinSafe(T9_, 2);
	result = new__pkgZnicoZbackendsZcommon_u1095();
	T10_.len = 0; T10_.p = NIM_NIL;
	T10_ = newSeq__pkgZnicoZbackendsZcommon_u1280(((NI)((*surface_p0).w * (*surface_p0).h)));
	eqsink___pureZtimes_u2604((&(*result).data), T10_);
	(*result).w = (*surface_p0).w;
	(*result).h = (*surface_p0).h;
	(*result).channels = ((NI)1);
	{
		if (!((*surface_p0).channels == ((NI)3))) goto LA13_;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (NI)((*surface_p0).w * (*surface_p0).h);
			i_2 = ((NI)0);
			{
				while (1) {
					NI T18_;
					if (!(i_2 < colontmp_)) goto LA17;
					i = i_2;
					T18_ = (NI)0;
					T18_ = mapRGB__pkgZnicoZbackendsZcommon_u1438((*surface_p0).data.p->data[(NI)((NI)(i * (*surface_p0).channels) + ((NI)0))], (*surface_p0).data.p->data[(NI)((NI)(i * (*surface_p0).channels) + ((NI)1))], (*surface_p0).data.p->data[(NI)((NI)(i * (*surface_p0).channels) + ((NI)2))]);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					(*result).data.p->data[i] = ((NU8) (T18_));
					i_2 += ((NI)1);
				} LA17: ;
			}
		}
	}
	goto LA11_;
LA13_: ;
	{
		if (!((*surface_p0).channels == ((NI)4))) goto LA20_;
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = (NI)((*surface_p0).w * (*surface_p0).h);
			i_4 = ((NI)0);
			{
				while (1) {
					NI T25_;
					if (!(i_4 < colontmp__2)) goto LA24;
					i_3 = i_4;
					T25_ = (NI)0;
					T25_ = mapRGBA__pkgZnicoZbackendsZcommon_u1569((*surface_p0).data.p->data[(NI)((NI)(i_3 * (*surface_p0).channels) + ((NI)0))], (*surface_p0).data.p->data[(NI)((NI)(i_3 * (*surface_p0).channels) + ((NI)1))], (*surface_p0).data.p->data[(NI)((NI)(i_3 * (*surface_p0).channels) + ((NI)2))], (*surface_p0).data.p->data[(NI)((NI)(i_3 * (*surface_p0).channels) + ((NI)3))]);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					(*result).data.p->data[i_3] = ((NU8) (T25_));
					i_4 += ((NI)1);
				} LA24: ;
			}
		}
	}
	goto LA11_;
LA20_: ;
LA11_: ;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZnicoZbackendsZcommon_u1152)(tySequence__wgMvnlQViw7eTDXNUYd1uQ* dest_p0, tySequence__wgMvnlQViw7eTDXNUYd1uQ src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___pkgZnicoZbackendsZcommon_u1143((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, convertToRGBA__pkgZnicoZbackendsZcommon_u1400)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* src_p0, void* abgrPixels_p1, int dpitch_p2, int w_p3, int h_p4) {
	NU8* abgrPixels_2;
	abgrPixels_2 = ((NU8*) (abgrPixels_p1));
	{
		NI32 y;
		NI32 colontmp_;
		NI32 res;
		y = (NI32)0;
		colontmp_ = (NI32)0;
		colontmp_ = (NI32)(h_p4 - ((NI32)1));
		res = ((NI32)0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				y = res;
				{
					NI32 x;
					NI32 colontmp__2;
					NI32 res_2;
					x = (NI32)0;
					colontmp__2 = (NI32)0;
					colontmp__2 = (NI32)(w_p3 - ((NI32)1));
					res_2 = ((NI32)0);
					{
						while (1) {
							tyTuple__hSHiEU6uEtL7soi1F4tKCg c;
							if (!(res_2 <= colontmp__2)) goto LA6;
							x = res_2;
							c = currentPalette__pkgZnicoZbackendsZcommon_u861.Field1[(paletteMapDisplay__pkgZnicoZbackendsZcommon_u1047[(((NI) ((*src_p0).data.p->data[(NI32)((NI32)(y * ((NI32) ((*src_p0).w))) + x)])))- 0])- 0];
							abgrPixels_2[((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))))- 0] = c.Field0;
							abgrPixels_2[((NI32)((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))) + ((NI32)1)))- 0] = c.Field1;
							abgrPixels_2[((NI32)((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))) + ((NI32)2)))- 0] = c.Field2;
							abgrPixels_2[((NI32)((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))) + ((NI32)3)))- 0] = ((NU8)255);
							res_2 += ((NI)1);
						} LA6: ;
					}
				}
				res += ((NI)1);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZnicoZbackendsZsdl2_u1629)(tyObject_Touch__W7l2d79afJabNHgASXk0Cqw* dest_p0) {
	(*dest_p0).id = 0;
	(*dest_p0).x = 0;
	(*dest_p0).y = 0;
	(*dest_p0).sx = 0;
	(*dest_p0).sy = 0;
	(*dest_p0).xrel = 0;
	(*dest_p0).yrel = 0;
	(*dest_p0).xrelraw = 0;
	(*dest_p0).yrelraw = 0;
	(*dest_p0).state = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, convertToABGR__pkgZnicoZbackendsZcommon_u1324)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* src_p0, void* rgbaPixels_p1, int dpitch_p2, int w_p3, int h_p4) {
	NU8* rgbaPixels_2;
	rgbaPixels_2 = ((NU8*) (rgbaPixels_p1));
	{
		NI32 y;
		NI32 colontmp_;
		NI32 res;
		y = (NI32)0;
		colontmp_ = (NI32)0;
		colontmp_ = (NI32)(h_p4 - ((NI32)1));
		res = ((NI32)0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				y = res;
				{
					NI32 x;
					NI32 colontmp__2;
					NI32 res_2;
					x = (NI32)0;
					colontmp__2 = (NI32)0;
					colontmp__2 = (NI32)(w_p3 - ((NI32)1));
					res_2 = ((NI32)0);
					{
						while (1) {
							tyTuple__hSHiEU6uEtL7soi1F4tKCg c;
							if (!(res_2 <= colontmp__2)) goto LA6;
							x = res_2;
							c = currentPalette__pkgZnicoZbackendsZcommon_u861.Field1[(paletteMapDisplay__pkgZnicoZbackendsZcommon_u1047[(((NI) ((*src_p0).data.p->data[(NI32)((NI32)(y * ((NI32) ((*src_p0).w))) + x)])))- 0])- 0];
							rgbaPixels_2[((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))))- 0] = ((NU8)255);
							rgbaPixels_2[((NI32)((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))) + ((NI32)1)))- 0] = c.Field2;
							rgbaPixels_2[((NI32)((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))) + ((NI32)2)))- 0] = c.Field1;
							rgbaPixels_2[((NI32)((NI32)((NI32)(y * dpitch_p2) + (NI32)(x * ((NI32)4))) + ((NI32)3)))- 0] = c.Field0;
							res_2 += ((NI)1);
						} LA6: ;
					}
				}
				res += ((NI)1);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(NU8, get__pkgZnicoZbackendsZcommon_u827)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* s_p0, NI x_p1, NI y_p2) {
	NU8 result;
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (x_p1 < ((NI)0));
		if (T5_) goto LA6_;
		T5_ = (y_p2 < ((NI)0));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = ((*s_p0).w <= x_p1);
LA7_: ;
		T3_ = T4_;
		if (T3_) goto LA8_;
		T3_ = ((*s_p0).h <= y_p2);
LA8_: ;
		if (!T3_) goto LA9_;
		result = ((NU8)0);
		goto BeforeRet_;
	}
LA9_: ;
	result = (*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)];
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, set__pkgZnicoZbackendsZcommon_u783)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* s_p0, NI x_p1, NI y_p2, NU8 v_p3) {
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (x_p1 < ((NI)0));
		if (T5_) goto LA6_;
		T5_ = (y_p2 < ((NI)0));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = ((*s_p0).w <= x_p1);
LA7_: ;
		T3_ = T4_;
		if (T3_) goto LA8_;
		T3_ = ((*s_p0).h <= y_p2);
LA8_: ;
		if (!T3_) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	(*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)] = v_p3;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pkgZnicoZbackendsZcommon_u797)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* s_p0, NI x_p1, NI y_p2, NU8 v_p3) {
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (x_p1 < ((NI)0));
		if (T5_) goto LA6_;
		T5_ = (y_p2 < ((NI)0));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = ((*s_p0).w <= x_p1);
LA7_: ;
		T3_ = T4_;
		if (T3_) goto LA8_;
		T3_ = ((*s_p0).h <= y_p2);
LA8_: ;
		if (!T3_) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	(*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)] = ((NU8) ((((NI)(((NI) ((*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)])) + ((NI) (v_p3))) <= ((NI)255)) ? (NI)(((NI) ((*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)])) + ((NI) (v_p3))) : ((NI)255))));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, subtract__pkgZnicoZbackendsZcommon_u802)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* s_p0, NI x_p1, NI y_p2, NU8 v_p3) {
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (x_p1 < ((NI)0));
		if (T5_) goto LA6_;
		T5_ = (y_p2 < ((NI)0));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = ((*s_p0).w <= x_p1);
LA7_: ;
		T3_ = T4_;
		if (T3_) goto LA8_;
		T3_ = ((*s_p0).h <= y_p2);
LA8_: ;
		if (!T3_) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	(*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)] = ((NU8) ((((NI)(((NI) ((*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)])) - ((NI) (v_p3))) >= ((NI)0)) ? (NI)(((NI) ((*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)])) - ((NI) (v_p3))) : ((NI)0))));
	}BeforeRet_: ;
}
static N_INLINE(NU8, max__pkgZnicoZbackendsZcommon_u812)(NU8 x_p0, NU8 y_p1) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!((NU8)(y_p1) <= (NU8)(x_p0))) goto LA3_;
		colontmpD_ = x_p0;
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = y_p1;
		result = colontmpD__2;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, blendMax__pkgZnicoZbackendsZcommon_u807)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* s_p0, NI x_p1, NI y_p2, NU8 v_p3) {
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (x_p1 < ((NI)0));
		if (T5_) goto LA6_;
		T5_ = (y_p2 < ((NI)0));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = ((*s_p0).w <= x_p1);
LA7_: ;
		T3_ = T4_;
		if (T3_) goto LA8_;
		T3_ = ((*s_p0).h <= y_p2);
LA8_: ;
		if (!T3_) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	(*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)] = max__pkgZnicoZbackendsZcommon_u812((*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)], v_p3);
	}BeforeRet_: ;
}
static N_INLINE(NU8, min__pkgZnicoZbackendsZcommon_u822)(NU8 x_p0, NU8 y_p1) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!((NU8)(x_p0) <= (NU8)(y_p1))) goto LA3_;
		colontmpD_ = x_p0;
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = y_p1;
		result = colontmpD__2;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, blendMin__pkgZnicoZbackendsZcommon_u817)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* s_p0, NI x_p1, NI y_p2, NU8 v_p3) {
{	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (x_p1 < ((NI)0));
		if (T5_) goto LA6_;
		T5_ = (y_p2 < ((NI)0));
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = ((*s_p0).w <= x_p1);
LA7_: ;
		T3_ = T4_;
		if (T3_) goto LA8_;
		T3_ = ((*s_p0).h <= y_p2);
LA8_: ;
		if (!T3_) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	(*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)] = min__pkgZnicoZbackendsZcommon_u822((*s_p0).data.p->data[(NI)((NI)(y_p2 * (*s_p0).w) + x_p1)], v_p3);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3609)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg** dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			if (!(colontmp_ < ((NI)16))) goto LA2;
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = nimDecRefIsLast(dest_p0[(colontmp_)- 0]);
				if (!T5_) goto LA6_;
				eqdestroy___pkgZnicoZbackendsZcommon_u3629(dest_p0[(colontmp_)- 0]);
				nimRawDispose(dest_p0[(colontmp_)- 0], ((NI)4));
			}
LA6_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3439)(tySequence__pcXSChh0J6OCdCDPpBK9b1g dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicDyn(dest_p0.p->data[colontmp_].ClE_0);
				if (!T6_) goto LA7_;
				nimDestroyAndDispose(dest_p0.p->data[colontmp_].ClE_0);
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyProc__yZbvgbtLeGIhzIA9bifjdPw));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3407)(tyProc__Hx0b1P9bD01T9bF9aUnykFuyA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3375)(tyProc__y9aUXu4JGz72YDIZVWUrK5w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3209)(tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ* dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			if (!(colontmp_ < ((NI)16))) goto LA2;
			eqdestroy___pkgZnicoZbackendsZcommon_u3229(dest_p0[(colontmp_)- 0].data);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3167)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw** dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			if (!(colontmp_ < ((NI)16))) goto LA2;
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = nimDecRefIsLast(dest_p0[(colontmp_)- 0]);
				if (!T5_) goto LA6_;
				eqdestroy___pkgZnicoZbackendsZcommon_u1125(dest_p0[(colontmp_)- 0]);
				nimRawDispose(dest_p0[(colontmp_)- 0], ((NI)4));
			}
LA6_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2986)(tyProc__9cFudSqKwo7KIwGlL9bTobiA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2949)(tySequence__QfewH7ZCzlg03Itl2jsx5w* dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			if (!(colontmp_ < ((NI)16))) goto LA2;
			eqdestroy___pkgZnicoZbackendsZcommon_u2751(dest_p0[(colontmp_)- 0]);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2173)(tySequence__GyXTUZbNFl9a0ulDnQFpFoA dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_Touch__W7l2d79afJabNHgASXk0Cqw));
}
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsbackendsatscommondotnim_Init000)(void) {
{
	tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg T1_;
	tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg T10_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg));
	T1_ = initTable__pkgZnicoZbackendsZcommon_u93(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pkgZnicoZbackendsZcommon_u187(&T1_); goto BeforeRet_;}
	keysDown__pkgZnicoZbackendsZcommon_u244 = T1_;
	invSampleRate__pkgZnicoZbackendsZcommon_u868 = ((NF32)(1.0f) / (NF32)(sampleRate__pkgZnicoZbackendsZcommon_u867));
	audioTickCallback__pkgZnicoZbackendsZcommon_u870.ClE_0 = TM__YTEtjZksCHMwTR9aj14QpVQ_2.ClE_0;
	audioTickCallback__pkgZnicoZbackendsZcommon_u870.ClP_0 = TM__YTEtjZksCHMwTR9aj14QpVQ_2.ClP_0;
	keyListeners__pkgZnicoZbackendsZcommon_u879.len = 0; keyListeners__pkgZnicoZbackendsZcommon_u879.p = (tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content*) newSeqPayload(0, sizeof(tyProc__SR0j0ClEYDvwlJHrgLh3cQ), NIM_ALIGNOF(tyProc__SR0j0ClEYDvwlJHrgLh3cQ));
	eventListeners__pkgZnicoZbackendsZcommon_u884.len = 0; eventListeners__pkgZnicoZbackendsZcommon_u884.p = (tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content*) newSeqPayload(0, sizeof(tyProc__WgqeCw2WGxAI9bmI3lHRKog), NIM_ALIGNOF(tyProc__WgqeCw2WGxAI9bmI3lHRKog));
	keymap__pkgZnicoZbackendsZcommon_u989[0].len = 2; keymap__pkgZnicoZbackendsZcommon_u989[0].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(2, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[0].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)80);
	keymap__pkgZnicoZbackendsZcommon_u989[0].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)4);
	keymap__pkgZnicoZbackendsZcommon_u989[1].len = 2; keymap__pkgZnicoZbackendsZcommon_u989[1].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(2, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[1].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)79);
	keymap__pkgZnicoZbackendsZcommon_u989[1].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)7);
	keymap__pkgZnicoZbackendsZcommon_u989[2].len = 2; keymap__pkgZnicoZbackendsZcommon_u989[2].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(2, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[2].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)82);
	keymap__pkgZnicoZbackendsZcommon_u989[2].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)26);
	keymap__pkgZnicoZbackendsZcommon_u989[3].len = 2; keymap__pkgZnicoZbackendsZcommon_u989[3].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(2, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[3].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)81);
	keymap__pkgZnicoZbackendsZcommon_u989[3].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)22);
	keymap__pkgZnicoZbackendsZcommon_u989[4].len = 3; keymap__pkgZnicoZbackendsZcommon_u989[4].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(3, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[4].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)29);
	keymap__pkgZnicoZbackendsZcommon_u989[4].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)28);
	keymap__pkgZnicoZbackendsZcommon_u989[4].p->data[2] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)44);
	keymap__pkgZnicoZbackendsZcommon_u989[5].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[5].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[5].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)27);
	keymap__pkgZnicoZbackendsZcommon_u989[6].len = 2; keymap__pkgZnicoZbackendsZcommon_u989[6].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(2, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[6].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)225);
	keymap__pkgZnicoZbackendsZcommon_u989[6].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)229);
	keymap__pkgZnicoZbackendsZcommon_u989[7].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[7].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[7].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)6);
	keymap__pkgZnicoZbackendsZcommon_u989[8].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[8].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[8].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)9);
	keymap__pkgZnicoZbackendsZcommon_u989[9].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[9].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[9].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)10);
	keymap__pkgZnicoZbackendsZcommon_u989[10].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[10].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[10].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)11);
	keymap__pkgZnicoZbackendsZcommon_u989[11].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[11].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[11].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)25);
	keymap__pkgZnicoZbackendsZcommon_u989[12].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[12].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[12].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)5);
	keymap__pkgZnicoZbackendsZcommon_u989[13].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[13].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[13].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)17);
	keymap__pkgZnicoZbackendsZcommon_u989[14].len = 1; keymap__pkgZnicoZbackendsZcommon_u989[14].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(1, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[14].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)40);
	keymap__pkgZnicoZbackendsZcommon_u989[15].len = 2; keymap__pkgZnicoZbackendsZcommon_u989[15].p = (tySequence__QfewH7ZCzlg03Itl2jsx5w_Content*) newSeqPayload(2, sizeof(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A), NIM_ALIGNOF(tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A));
	keymap__pkgZnicoZbackendsZcommon_u989[15].p->data[0] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)41);
	keymap__pkgZnicoZbackendsZcommon_u989[15].p->data[1] = ((tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A)42);
	timeStep__pkgZnicoZbackendsZcommon_u1018 = slash___system_u1693(((NI)1), frameRate__pkgZnicoZbackendsZcommon_u1017);
	{
		NI i;
		i = ((NI)0);
		{
			while (1) {
				NIM_BOOL colontmpD_;
				NIM_BOOL colontmpD__2;
				if (!(i < ((NI)256))) goto LA4;
				colontmpD_ = (NIM_BOOL)0;
				colontmpD__2 = (NIM_BOOL)0;
				i__pkgZnicoZbackendsZcommon_u1053 = i;
				paletteMapDraw__pkgZnicoZbackendsZcommon_u1046[(i__pkgZnicoZbackendsZcommon_u1053)- 0] = i__pkgZnicoZbackendsZcommon_u1053;
				paletteMapDisplay__pkgZnicoZbackendsZcommon_u1047[(i__pkgZnicoZbackendsZcommon_u1053)- 0] = i__pkgZnicoZbackendsZcommon_u1053;
				{
					if (!(i__pkgZnicoZbackendsZcommon_u1053 == ((NI)0))) goto LA7_;
					colontmpD_ = NIM_TRUE;
					paletteTransparent__pkgZnicoZbackendsZcommon_u1048[(i__pkgZnicoZbackendsZcommon_u1053)- 0] = colontmpD_;
				}
				goto LA5_;
LA7_: ;
				{
					colontmpD__2 = NIM_FALSE;
					paletteTransparent__pkgZnicoZbackendsZcommon_u1048[(i__pkgZnicoZbackendsZcommon_u1053)- 0] = colontmpD__2;
				}
LA5_: ;
				i += ((NI)1);
			} LA4: ;
		}
	}
	nimZeroMem((void*)(&T10_), sizeof(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg));
	T10_ = initRingBuffer__pkgZnicoZbackendsZcommon_u1725(((NI)256));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pkgZnicoZbackendsZcommon_u1921(&T10_); goto BeforeRet_;}
	profileHistory__pkgZnicoZbackendsZcommon_u1942 = T10_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

