/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@mcombat.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@mcombat.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw;
typedef struct tyTuple__bRyhXH2W6bAwxmsy78A9c3g tyTuple__bRyhXH2W6bAwxmsy78A9c3g;
typedef struct tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g;
typedef struct tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w;
typedef struct tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA;
typedef struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ;
typedef struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
struct tyTuple__bRyhXH2W6bAwxmsy78A9c3g {
	NF32 Field0;
	NF32 Field1;
	NF32 Field2;
	NF32 Field3;
};
typedef NU8 tyEnum_State__BXhE0v2wjSR5Sst324uAcw;
typedef NF32 tyArray__4YxcnnI8do9a6vmNKtzdSKw[2];
typedef NU8 tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg;
struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ {
  NI len; tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content* p;
};
struct tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw {
	tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* heart;
	tyEnum_State__BXhE0v2wjSR5Sst324uAcw state;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw position;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw hand_pos;
	NI sprite_slot;
	NI frame;
	NF32 step;
	tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg facing;
	NF32 speed;
	NF32 dash_speed;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* hurtbox;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* hitbox;
	tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ hitboxes;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g {
	NI width;
	NI height;
	NI frame;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ offset;
};
struct tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ offset;
	NI width;
	NI height;
};
struct tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w {
	NI x;
	NI y;
	NF32 bpm;
	NI frame;
	NF32 dt;
	NIM_BOOL stop_damage;
};
struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content { NI cap; tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyTuple__bRyhXH2W6bAwxmsy78A9c3g, get_hitbox__combat_u3)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0, NI frame_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NF32, toPfloat__pkgZnico_u7291)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(tyTuple__bRyhXH2W6bAwxmsy78A9c3g, get_hurtbox__combat_u258)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, detect_hit__combat_u284)(NF32 area1_p0, NF32 area2_p1);
N_LIB_PRIVATE N_NIMCALL(void, damage__combat_u288)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0, NF32 damage_p1);
static N_INLINE(void, minuseq___pkgZnico_u1418)(NF32* x_p0, NF32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, death__combat_u282)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NF32, toPfloat__pkgZnico_u7291)(NI x_p0) {
	NF32 result;
{	result = ((NF32) (x_p0));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__bRyhXH2W6bAwxmsy78A9c3g, get_hitbox__combat_u3)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0, NI frame_p1) {
	tyTuple__bRyhXH2W6bAwxmsy78A9c3g result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__bRyhXH2W6bAwxmsy78A9c3g));
	{
		tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g** hitbox;
		NI i;
		NI L;
		NI T2_;
		hitbox = (tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g**)0;
		i = ((NI)0);
		T2_ = (*character_p0).hitboxes.len;
		L = T2_;
		{
			while (1) {
				NF32 x;
				NF32 T5_;
				NF32 y;
				NF32 T6_;
				NI w;
				NI h;
				if (!(i < L)) goto LA4;
				hitbox = &(*character_p0).hitboxes.p->data[i];
				T5_ = (NF32)0;
				T5_ = toPfloat__pkgZnico_u7291((*(*hitbox)).offset.Field0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				x = ((NF32)((*character_p0).position[(((NI)0))- 0]) + (NF32)(T5_));
				T6_ = (NF32)0;
				T6_ = toPfloat__pkgZnico_u7291((*(*hitbox)).offset.Field1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				y = ((NF32)((*character_p0).position[(((NI)1))- 0]) + (NF32)(T6_));
				w = (*(*hitbox)).width;
				h = (*(*hitbox)).height;
				{
					NF32 colontmp_;
					NF32 colontmp__2;
					NF32 colontmp__3;
					NF32 T11_;
					NF32 colontmp__4;
					NF32 T12_;
					if (!((*(*hitbox)).frame == (*character_p0).frame)) goto LA9_;
					colontmp_ = x;
					colontmp__2 = y;
					T11_ = (NF32)0;
					T11_ = toPfloat__pkgZnico_u7291(w);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					colontmp__3 = ((NF32)(x) + (NF32)(T11_));
					T12_ = (NF32)0;
					T12_ = toPfloat__pkgZnico_u7291(h);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					colontmp__4 = ((NF32)(y) + (NF32)(T12_));
					result.Field0 = colontmp_;
					result.Field1 = colontmp__2;
					result.Field2 = colontmp__3;
					result.Field3 = colontmp__4;
					goto BeforeRet_;
				}
LA9_: ;
				i += ((NI)1);
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__bRyhXH2W6bAwxmsy78A9c3g, get_hurtbox__combat_u258)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0) {
	tyTuple__bRyhXH2W6bAwxmsy78A9c3g result;
	NF32 x;
	NF32 T1_;
	NF32 y;
	NF32 T2_;
	NI w;
	NI h;
	NF32 colontmp_;
	NF32 colontmp__2;
	NF32 colontmp__3;
	NF32 T3_;
	NF32 colontmp__4;
	NF32 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__bRyhXH2W6bAwxmsy78A9c3g));
	T1_ = (NF32)0;
	T1_ = toPfloat__pkgZnico_u7291((*(*character_p0).hurtbox).offset.Field0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	x = ((NF32)((*character_p0).position[(((NI)0))- 0]) + (NF32)(T1_));
	T2_ = (NF32)0;
	T2_ = toPfloat__pkgZnico_u7291((*(*character_p0).hurtbox).offset.Field1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	y = ((NF32)((*character_p0).position[(((NI)1))- 0]) + (NF32)(T2_));
	w = (*(*character_p0).hurtbox).width;
	h = (*(*character_p0).hurtbox).height;
	colontmp_ = x;
	colontmp__2 = y;
	T3_ = (NF32)0;
	T3_ = toPfloat__pkgZnico_u7291(w);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmp__3 = ((NF32)(x) + (NF32)(T3_));
	T4_ = (NF32)0;
	T4_ = toPfloat__pkgZnico_u7291(h);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmp__4 = ((NF32)(y) + (NF32)(T4_));
	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	result.Field2 = colontmp__3;
	result.Field3 = colontmp__4;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, detect_hit__combat_u284)(NF32 area1_p0, NF32 area2_p1) {
	NIM_BOOL result;
{	{
		if (!(((NF) (area2_p1)) == 0.0)) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(area2_p1 <= area1_p0)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA5_;
LA7_: ;
	{
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, minuseq___pkgZnico_u1418)(NF32* x_p0, NF32 y_p1) {
	(*x_p0) = ((NF32)((*x_p0)) - (NF32)(y_p1));
}
N_LIB_PRIVATE N_NIMCALL(void, damage__combat_u288)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0, NF32 damage_p1) {
	{
		if (!((*(*character_p0).heart).stop_damage == NIM_FALSE)) goto LA3_;
		minuseq___pkgZnico_u1418((&(*(*character_p0).heart).bpm), damage_p1);
		(*(*character_p0).heart).stop_damage = NIM_TRUE;
		(*character_p0).state = ((tyEnum_State__BXhE0v2wjSR5Sst324uAcw)9);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, death__combat_u282)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0) {
	(*character_p0).state = ((tyEnum_State__BXhE0v2wjSR5Sst324uAcw)10);
}
N_LIB_PRIVATE N_NIMCALL(void, combat__combat_u295)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character1_p0, tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character2_p1) {
	tyTuple__bRyhXH2W6bAwxmsy78A9c3g c1_hitbox;
	tyTuple__bRyhXH2W6bAwxmsy78A9c3g c2_hitbox;
	tyTuple__bRyhXH2W6bAwxmsy78A9c3g c1_hurtbox;
	tyTuple__bRyhXH2W6bAwxmsy78A9c3g c2_hurtbox;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	c1_hitbox = get_hitbox__combat_u3(character1_p0, (*character1_p0).frame);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	c2_hitbox = get_hitbox__combat_u3(character2_p1, (*character2_p1).frame);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	c1_hurtbox = get_hurtbox__combat_u258(character1_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	c2_hurtbox = get_hurtbox__combat_u258(character2_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = detect_hit__combat_u284(c1_hurtbox.Field2, c2_hitbox.Field0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		damage__combat_u288(character1_p0, 30.0f);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = detect_hit__combat_u284(c1_hitbox.Field2, c2_hurtbox.Field0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T8_) goto LA9_;
		damage__combat_u288(character2_p1, 30.0f);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	{
		if (!((*(*character1_p0).heart).bpm <= 0.0f)) goto LA13_;
		death__combat_u282(character1_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA13_: ;
	{
		if (!((*(*character2_p1).heart).bpm <= 0.0f)) goto LA17_;
		death__combat_u282(character2_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA17_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, heartbeat__combat_u273)(tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* heart_p0) {
	NF seconds_per_beat;
	NI frames;
	NF32 duration;
	NF32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	seconds_per_beat = ((NF)(60.0) / (NF)(((NF) ((*heart_p0).bpm))));
	frames = ((NI)2);
	T1_ = (NF32)0;
	T1_ = toPfloat__pkgZnico_u7291(frames);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	duration = ((NF32)(((NF32) (seconds_per_beat))) / (NF32)(T1_));
	{
		if (!(frames <= (*heart_p0).frame)) goto LA4_;
		(*heart_p0).frame = ((NI)0);
	}
LA4_: ;
	{
		if (!(seconds_per_beat <= ((NF) ((*heart_p0).dt)))) goto LA8_;
		minuseq___pkgZnico_u1418((&(*heart_p0).dt), ((NF32) (seconds_per_beat)));
	}
LA8_: ;
	(*heart_p0).frame = ((NI) (((NF32)((*heart_p0).dt) / (NF32)(duration))));
	}BeforeRet_: ;
}
