/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@menemy.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@menemy.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw;
typedef struct tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA;
typedef struct tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw;
typedef struct tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg;
typedef struct tySequence__ODAiMr50iWPGXmGFyO9au0w tySequence__ODAiMr50iWPGXmGFyO9au0w;
typedef struct tySequence__ODAiMr50iWPGXmGFyO9au0w_Content tySequence__ODAiMr50iWPGXmGFyO9au0w_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w;
typedef struct tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA;
typedef struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ;
typedef struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content;
typedef struct tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA;
typedef struct tyObject_HSlice__DO5p5S32LbatC4OszWRAIA tyObject_HSlice__DO5p5S32LbatC4OszWRAIA;
typedef struct tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g;
typedef struct tySequence__kl2zhG9abb3gLSE3TcJk5ZQ tySequence__kl2zhG9abb3gLSE3TcJk5ZQ;
typedef struct tySequence__kl2zhG9abb3gLSE3TcJk5ZQ_Content tySequence__kl2zhG9abb3gLSE3TcJk5ZQ_Content;
typedef struct tyTuple__GY9aNItjnkk9b0a9aSZVsTZLw tyTuple__GY9aNItjnkk9b0a9aSZVsTZLw;
typedef struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg;
typedef struct tyTuple__gfz23PD1jgX40Hus9aUuu0A tyTuple__gfz23PD1jgX40Hus9aUuu0A;
struct tySequence__ODAiMr50iWPGXmGFyO9au0w {
  NI len; tySequence__ODAiMr50iWPGXmGFyO9au0w_Content* p;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA {
	NF32 frame_counter;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ range;
	NF32 current_speed;
	NI lim;
	NI dash_timeout;
};
typedef NU8 tyEnum_State__BXhE0v2wjSR5Sst324uAcw;
typedef NF32 tyArray__4YxcnnI8do9a6vmNKtzdSKw[2];
typedef NU8 tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg;
struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ {
  NI len; tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content* p;
};
struct tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw {
	tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* heart;
	tyEnum_State__BXhE0v2wjSR5Sst324uAcw state;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw position;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw hand_pos;
	NI sprite_slot;
	NI frame;
	NF32 step;
	tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg facing;
	NF32 speed;
	NF32 dash_speed;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* hurtbox;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* hitbox;
	tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ hitboxes;
	NF32 distance_from_opp;
	tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA* projectile;
};
struct tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w {
	NI x;
	NI y;
	NF32 bpm;
	NI frame;
	NF32 dt;
	NIM_BOOL stop_damage;
};
struct tyObject_HSlice__DO5p5S32LbatC4OszWRAIA {
	NI a;
	NI b;
};
struct tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ offset;
	NI width;
	NI height;
};
struct tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA {
	NIM_BOOL enabled;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw position;
	NF32 speed;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* size;
	tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg direction;
};
struct tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g {
	NI width;
	NI height;
	NI frame;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ offset;
};
struct tySequence__kl2zhG9abb3gLSE3TcJk5ZQ {
  NI len; tySequence__kl2zhG9abb3gLSE3TcJk5ZQ_Content* p;
};
struct tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg {
	tySequence__kl2zhG9abb3gLSE3TcJk5ZQ stack;
	NI reset_frame;
	NI frame_elapsed;
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character;
	tySequence__ODAiMr50iWPGXmGFyO9au0w input_cands;
};
typedef NU8 tyEnum_AIBtn__B5W7MWqxKrA8cqndnYD8sA;
typedef NU8 tyEnum_BtnState__a6kTzZnnx7Ll6D9b59bwIyIQ;
struct tyTuple__GY9aNItjnkk9b0a9aSZVsTZLw {
	tyEnum_AIBtn__B5W7MWqxKrA8cqndnYD8sA Field0;
	NI Field1;
	tyEnum_BtnState__a6kTzZnnx7Ll6D9b59bwIyIQ Field2;
};
struct tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw {
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character;
	tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* def;
	tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* movement;
};
struct tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg {
	NI rc;
	NI rootIdx;
};
struct tyTuple__gfz23PD1jgX40Hus9aUuu0A {
	tyEnum_AIBtn__B5W7MWqxKrA8cqndnYD8sA Field0;
	NI Field1;
};
struct tySequence__ODAiMr50iWPGXmGFyO9au0w_Content { NI cap; tyTuple__gfz23PD1jgX40Hus9aUuu0A data[SEQ_DECL_SIZE]; };
struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content { NI cap; tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* data[SEQ_DECL_SIZE]; };
struct tySequence__kl2zhG9abb3gLSE3TcJk5ZQ_Content { NI cap; tyTuple__GY9aNItjnkk9b0a9aSZVsTZLw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*, archer__enemy_u34)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, vec2f__benkei_u12)(NI x_p0, NI y_p1, tyArray__4YxcnnI8do9a6vmNKtzdSKw Result);
N_LIB_PRIVATE N_NIMCALL(NI, rand__ai_u424)(tyObject_HSlice__DO5p5S32LbatC4OszWRAIA x_p0);
static N_INLINE(tyObject_HSlice__DO5p5S32LbatC4OszWRAIA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*, swordsman__enemy_u11)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*, eqdup___benkei_u264)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__ODAiMr50iWPGXmGFyO9au0w, eqdup___ai_u71)(tySequence__ODAiMr50iWPGXmGFyO9au0w src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___benkei_u255)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___ai_u703)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___movement_u171)(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___enemy_u154)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___enemy_u157)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___enemy_u118)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___benkei_u171)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ai_u724)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___movement_u192)(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ai_u706)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___benkei_u258)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___movement_u174)(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* dest_p0);
static NIM_CONST tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ TM__xk9aCDKjdqQNMvESlNmtV8Q_2 = {((NI)0),
((NI)3)}
;
static NIM_CONST tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ TM__xk9aCDKjdqQNMvESlNmtV8Q_3 = {((NI)10),
((NI)16)}
;
static NIM_CONST tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ TM__xk9aCDKjdqQNMvESlNmtV8Q_4 = {((NI)20),
((NI)16)}
;
static NIM_CONST tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ TM__xk9aCDKjdqQNMvESlNmtV8Q_5 = {((NI)-1),
((NI)16)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
extern tySequence__ODAiMr50iWPGXmGFyO9au0w approach__ai_u48;
static N_INLINE(tyObject_HSlice__DO5p5S32LbatC4OszWRAIA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__DO5p5S32LbatC4OszWRAIA result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*, archer__enemy_u34)(void) {
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* result;
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* T1_;
	tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* T2_;
	tyObject_HSlice__DO5p5S32LbatC4OszWRAIA T3_;
	NI T4_;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* T5_;
	tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA* T6_;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* T7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*) nimNewObj(sizeof(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw), NIM_ALIGNOF(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw));
	T2_ = NIM_NIL;
	T2_ = (tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w*) nimNewObj(sizeof(tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w), NIM_ALIGNOF(tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w));
	(*T2_).bpm = 110.0f;
	(*T2_).frame = ((NI)0);
	(*T2_).dt = 0.0f;
	(*T2_).stop_damage = NIM_FALSE;
	(*T1_).heart = T2_;
	(*T1_).facing = ((tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg)1);
	(*T1_).state = ((tyEnum_State__BXhE0v2wjSR5Sst324uAcw)0);
	T3_ = dotdot___stdZstrbasics_u48(((NI)0), ((NI)10));
	T4_ = (NI)0;
	T4_ = rand__ai_u424(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	vec2f__benkei_u12((NI)(((NI)100) + T4_), ((NI)66), (*T1_).position);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_).sprite_slot = ((NI)1);
	(*T1_).frame = ((NI)0);
	(*T1_).step = 0.0f;
	(*T1_).speed = 100.0f;
	(*T1_).dash_speed = 400.0f;
	T5_ = NIM_NIL;
	T5_ = (tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA*) nimNewObjUninit(sizeof(tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA), NIM_ALIGNOF(tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA));
	(*T5_).offset = TM__xk9aCDKjdqQNMvESlNmtV8Q_3;
	(*T5_).width = ((NI)10);
	(*T5_).height = ((NI)15);
	(*T1_).hurtbox = T5_;
	T6_ = NIM_NIL;
	T6_ = (tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA*) nimNewObjUninit(sizeof(tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA), NIM_ALIGNOF(tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA));
	(*T6_).enabled = NIM_TRUE;
	(*T6_).speed = 2.0f;
	vec2f__benkei_u12(((NI)0), ((NI)0), (*T6_).position);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = NIM_NIL;
	T7_ = (tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA*) nimNewObj(sizeof(tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA), NIM_ALIGNOF(tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA));
	(*T7_).width = ((NI)16);
	(*T7_).height = ((NI)16);
	(*T6_).size = T7_;
	(*T6_).direction = ((tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg)1);
	(*T1_).projectile = T6_;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*, swordsman__enemy_u11)(void) {
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* result;
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* T1_;
	tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* T2_;
	tyObject_HSlice__DO5p5S32LbatC4OszWRAIA T3_;
	NI T4_;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* T5_;
	tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* T6_;
	tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* T7_;
	tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* T8_;
	tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw*) nimNewObj(sizeof(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw), NIM_ALIGNOF(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw));
	T2_ = NIM_NIL;
	T2_ = (tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w*) nimNewObj(sizeof(tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w), NIM_ALIGNOF(tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w));
	(*T2_).bpm = 110.0f;
	(*T2_).frame = ((NI)0);
	(*T2_).dt = 0.0f;
	(*T2_).stop_damage = NIM_FALSE;
	(*T1_).heart = T2_;
	(*T1_).facing = ((tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg)1);
	(*T1_).state = ((tyEnum_State__BXhE0v2wjSR5Sst324uAcw)0);
	T3_ = dotdot___stdZstrbasics_u48(((NI)0), ((NI)10));
	T4_ = (NI)0;
	T4_ = rand__ai_u424(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	vec2f__benkei_u12((NI)(((NI)100) + T4_), ((NI)66), (*T1_).position);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_).sprite_slot = ((NI)2);
	(*T1_).frame = ((NI)0);
	(*T1_).step = 0.0f;
	(*T1_).speed = 200.0f;
	(*T1_).dash_speed = 400.0f;
	T5_ = NIM_NIL;
	T5_ = (tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA*) nimNewObjUninit(sizeof(tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA), NIM_ALIGNOF(tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA));
	(*T5_).offset = TM__xk9aCDKjdqQNMvESlNmtV8Q_3;
	(*T5_).width = ((NI)10);
	(*T5_).height = ((NI)15);
	(*T1_).hurtbox = T5_;
	(*T1_).hitboxes.len = 4; (*T1_).hitboxes.p = (tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content*) newSeqPayload(4, sizeof(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g*), NIM_ALIGNOF(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g*));
	T6_ = NIM_NIL;
	T6_ = (tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g*) nimNewObjUninit(sizeof(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g), NIM_ALIGNOF(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g));
	(*T6_).frame = ((NI)42);
	(*T6_).width = ((NI)13);
	(*T6_).height = ((NI)16);
	(*T6_).offset = TM__xk9aCDKjdqQNMvESlNmtV8Q_4;
	(*T1_).hitboxes.p->data[0] = T6_;
	T7_ = NIM_NIL;
	T7_ = (tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g*) nimNewObjUninit(sizeof(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g), NIM_ALIGNOF(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g));
	(*T7_).frame = ((NI)43);
	(*T7_).width = ((NI)13);
	(*T7_).height = ((NI)16);
	(*T7_).offset = TM__xk9aCDKjdqQNMvESlNmtV8Q_4;
	(*T1_).hitboxes.p->data[1] = T7_;
	T8_ = NIM_NIL;
	T8_ = (tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g*) nimNewObjUninit(sizeof(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g), NIM_ALIGNOF(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g));
	(*T8_).frame = ((NI)48);
	(*T8_).width = ((NI)13);
	(*T8_).height = ((NI)16);
	(*T8_).offset = TM__xk9aCDKjdqQNMvESlNmtV8Q_5;
	(*T1_).hitboxes.p->data[2] = T8_;
	T9_ = NIM_NIL;
	T9_ = (tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g*) nimNewObjUninit(sizeof(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g), NIM_ALIGNOF(tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g));
	(*T9_).frame = ((NI)49);
	(*T9_).width = ((NI)13);
	(*T9_).height = ((NI)16);
	(*T9_).offset = TM__xk9aCDKjdqQNMvESlNmtV8Q_5;
	(*T1_).hitboxes.p->data[3] = T9_;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___enemy_u154)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__gnJExvuIhzi79cQetGScWGg*) (T5_));
		{
			if (!((NI)((NI32)((*cell).rc) >> (NU32)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___enemy_u118)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).character);
		if (!T3_) goto LA4_;
		eqdestroy___benkei_u171((*dest_p0).character);
		nimRawDispose((*dest_p0).character, ((NI)4));
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).def);
		if (!T8_) goto LA9_;
		eqdestroy___ai_u724((*dest_p0).def);
		nimRawDispose((*dest_p0).def, ((NI)4));
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLast((*dest_p0).movement);
		if (!T13_) goto LA14_;
		eqdestroy___movement_u192((*dest_p0).movement);
		nimRawDispose((*dest_p0).movement, ((NI)4));
	}
LA14_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___enemy_u157)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___enemy_u118(dest_p0);
		nimRawDispose(dest_p0, ((NI)4));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*, add_enemy__enemy_u83)(NI spr_slot_p0) {
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* result;
	tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* e_movement;
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* enemy;
	tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* btndef;
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* colontmpD_;
	tySequence__ODAiMr50iWPGXmGFyO9au0w colontmpD__2;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* wrapped;
	tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* T2_;
	tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* T5_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T6_;
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* blitTmp;
	tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* blitTmp_2;
	tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* blitTmp_3;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	e_movement = NIM_NIL;
	enemy = NIM_NIL;
	btndef = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	wrapped = NIM_NIL;
	T2_ = NIM_NIL;
	T2_ = (tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA*) nimNewObjUninit(sizeof(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA), NIM_ALIGNOF(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA));
	(*T2_).frame_counter = 5.0f;
	(*T2_).range = TM__xk9aCDKjdqQNMvESlNmtV8Q_2;
	(*T2_).current_speed = 0.0f;
	(*T2_).lim = ((NI)1);
	(*T2_).dash_timeout = ((NI)0);
	e_movement = T2_;
	switch (spr_slot_p0) {
	case ((NI)1):
	{
		enemy = archer__enemy_u34();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	break;
	default:
	{
		enemy = swordsman__enemy_u11();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	break;
	}
	T5_ = NIM_NIL;
	T5_ = (tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg*) nimNewObjUninit(sizeof(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg), NIM_ALIGNOF(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg));
	(*T5_).stack.len = 0; (*T5_).stack.p = (tySequence__kl2zhG9abb3gLSE3TcJk5ZQ_Content*) newSeqPayload(0, sizeof(tyTuple__GY9aNItjnkk9b0a9aSZVsTZLw), NIM_ALIGNOF(tyTuple__GY9aNItjnkk9b0a9aSZVsTZLw));
	(*T5_).reset_frame = ((NI)5);
	(*T5_).frame_elapsed = ((NI)0);
	colontmpD_ = eqdup___benkei_u264(enemy);
	(*T5_).character = colontmpD_;
	colontmpD__2 = eqdup___ai_u71(approach__ai_u48);
	(*T5_).input_cands = colontmpD__2;
	btndef = T5_;
	T6_ = NIM_NIL;
	T6_ = (tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*) nimNewObjUninit(sizeof(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw), NIM_ALIGNOF(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw));
	blitTmp = enemy;
	eqwasMoved___benkei_u255(&enemy);
	(*T6_).character = blitTmp;
	blitTmp_2 = btndef;
	eqwasMoved___ai_u703(&btndef);
	(*T6_).def = blitTmp_2;
	blitTmp_3 = e_movement;
	eqwasMoved___movement_u171(&e_movement);
	(*T6_).movement = blitTmp_3;
	wrapped = T6_;
	result = wrapped;
	eqwasMoved___enemy_u154(&wrapped);
	eqdestroy___enemy_u157(wrapped);
	eqdestroy___ai_u706(btndef);
	eqdestroy___benkei_u258(enemy);
	eqdestroy___movement_u174(e_movement);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___enemy_u157(wrapped);
		eqdestroy___ai_u706(btndef);
		eqdestroy___benkei_u258(enemy);
		eqdestroy___movement_u174(e_movement);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
