/* Generated by Nim Compiler v2.2.2 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -pthread -flto -O3   -I/home/gregis/.choosenim/toolchains/nim-2.2.2/lib -I/home/gregis/Projects/OneLastBeat/src -o /home/gregis/Projects/OneLastBeat/tmp/@mmain.nim.c.o /home/gregis/Projects/OneLastBeat/tmp/@mmain.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__g8gk0QJZcC9aEKLq8wBUQNA tySequence__g8gk0QJZcC9aEKLq8wBUQNA;
typedef struct tySequence__g8gk0QJZcC9aEKLq8wBUQNA_Content tySequence__g8gk0QJZcC9aEKLq8wBUQNA_Content;
typedef struct tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ;
typedef struct tySequence__6eW0sN9cwnKC4gxJcPFupZQ tySequence__6eW0sN9cwnKC4gxJcPFupZQ;
typedef struct tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content;
typedef struct tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__npOdd6OOX5uthJz7z22r9ag tyTuple__npOdd6OOX5uthJz7z22r9ag;
typedef struct tyTuple__hSHiEU6uEtL7soi1F4tKCg tyTuple__hSHiEU6uEtL7soi1F4tKCg;
typedef struct tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw;
typedef struct tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg;
typedef struct tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA;
typedef struct tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w;
typedef struct tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA;
typedef struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ;
typedef struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content;
typedef struct tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA;
typedef struct tySequence__ODAiMr50iWPGXmGFyO9au0w tySequence__ODAiMr50iWPGXmGFyO9au0w;
typedef struct tySequence__ODAiMr50iWPGXmGFyO9au0w_Content tySequence__ODAiMr50iWPGXmGFyO9au0w_Content;
typedef struct tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw;
typedef struct tyObject_Channel__in24RcHDml3U5CQrgcGk5g tyObject_Channel__in24RcHDml3U5CQrgcGk5g;
typedef struct tyObject_SfxBuffercolonObjectType___lwjhdE2hrylQh0EU9aI9butg tyObject_SfxBuffercolonObjectType___lwjhdE2hrylQh0EU9aI9butg;
typedef struct tyObject_VorbisObj__5PzYikC9ahSxNpWoA19aAkYg tyObject_VorbisObj__5PzYikC9ahSxNpWoA19aAkYg;
typedef struct tyTuple__ktGn6XuQgErLkL9bJoC2G3A tyTuple__ktGn6XuQgErLkL9bJoC2G3A;
typedef struct tyTuple__YZGftELtXgCScyeZyJvrRw tyTuple__YZGftELtXgCScyeZyJvrRw;
typedef struct tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A;
typedef struct tySequence__4l0J2KoADAIc79csLV36IwA tySequence__4l0J2KoADAIc79csLV36IwA;
typedef struct tySequence__4l0J2KoADAIc79csLV36IwA_Content tySequence__4l0J2KoADAIc79csLV36IwA_Content;
typedef struct tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g;
typedef struct tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg;
typedef struct tySequence__EwWnHvzGVmDuLlfmw6Igdg tySequence__EwWnHvzGVmDuLlfmw6Igdg;
typedef struct tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content;
typedef struct tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg;
typedef struct tySequence__pcXSChh0J6OCdCDPpBK9b1g tySequence__pcXSChh0J6OCdCDPpBK9b1g;
typedef struct tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content;
typedef struct tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tySequence__friFxHbsLN0MVvin0IyEFg tySequence__friFxHbsLN0MVvin0IyEFg;
typedef struct tySequence__friFxHbsLN0MVvin0IyEFg_Content tySequence__friFxHbsLN0MVvin0IyEFg_Content;
typedef struct tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ;
typedef struct tySequence__QfewH7ZCzlg03Itl2jsx5w tySequence__QfewH7ZCzlg03Itl2jsx5w;
typedef struct tySequence__QfewH7ZCzlg03Itl2jsx5w_Content tySequence__QfewH7ZCzlg03Itl2jsx5w_Content;
typedef struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg tySequence__eXQ7qBth9b8fN9aDUGBmEWLg;
typedef struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content;
typedef struct tySequence__EtvC1a2T849cB0SNWHj6Fbg tySequence__EtvC1a2T849cB0SNWHj6Fbg;
typedef struct tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content;
typedef struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA tySequence__GyXTUZbNFl9a0ulDnQFpFoA;
typedef struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content;
typedef struct tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg;
typedef struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw tySequence__29c7ihdQ3dPeS9crD6M3kKQw;
typedef struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content;
typedef struct tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g;
typedef struct tyTuple__gfz23PD1jgX40Hus9aUuu0A tyTuple__gfz23PD1jgX40Hus9aUuu0A;
typedef struct tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA;
typedef struct tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig;
typedef struct tyObject_Event__PhexTflZOX2N20Vr39cGsHg tyObject_Event__PhexTflZOX2N20Vr39cGsHg;
typedef struct tyObject_Touch__W7l2d79afJabNHgASXk0Cqw tyObject_Touch__W7l2d79afJabNHgASXk0Cqw;
typedef struct tyTuple__A9bbISTrJh1vfJUGVCQM7pA tyTuple__A9bbISTrJh1vfJUGVCQM7pA;
struct tySequence__g8gk0QJZcC9aEKLq8wBUQNA {
  NI len; tySequence__g8gk0QJZcC9aEKLq8wBUQNA_Content* p;
};
struct tySequence__6eW0sN9cwnKC4gxJcPFupZQ {
  NI len; tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content* p;
};
struct tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ {
	NIM_BOOL enable_pre_stage;
	NIM_BOOL enable_stage;
	tySequence__6eW0sN9cwnKC4gxJcPFupZQ enemies;
	NI stage_num;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NF32 dt_p0, void* ClE_0);
void* ClE_0;
} tyProc__y9aUXu4JGz72YDIZVWUrK5w;
struct tyTuple__hSHiEU6uEtL7soi1F4tKCg {
	NU8 Field0;
	NU8 Field1;
	NU8 Field2;
};
typedef tyTuple__hSHiEU6uEtL7soi1F4tKCg tyArray__dmDmTUzwcRf4TYNb3Z383A[256];
struct tyTuple__npOdd6OOX5uthJz7z22r9ag {
	NI Field0;
	tyArray__dmDmTUzwcRf4TYNb3Z383A Field1;
};
typedef N_CLOSURE_PTR(void, TM__WyNS01ucugkrGheXSbzXhw_27) (void* ClE_0);
struct tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw {
	tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character;
	tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* def;
	tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* movement;
};
typedef NU8 tyEnum_State__BXhE0v2wjSR5Sst324uAcw;
typedef NF32 tyArray__4YxcnnI8do9a6vmNKtzdSKw[2];
typedef NU8 tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg;
struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ {
  NI len; tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content* p;
};
struct tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw {
	tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* heart;
	tyEnum_State__BXhE0v2wjSR5Sst324uAcw state;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw position;
	tyArray__4YxcnnI8do9a6vmNKtzdSKw hand_pos;
	NI sprite_slot;
	NI frame;
	NF32 step;
	tyEnum_Direction__JFoCXewRFqVfZPPeM6aDFg facing;
	NF32 speed;
	NF32 dash_speed;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* hurtbox;
	tyObject_CollisionBoxcolonObjectType___hijtiu9bkCo9clB9cPME9cclmA* hitbox;
	tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ hitboxes;
	NF32 distance_from_opp;
	tyObject_ProjectilecolonObjectType___s9cbJvRfjd9cFWzwbL6539b9aA* projectile;
};
typedef N_CLOSURE_PTR(void, TM__WyNS01ucugkrGheXSbzXhw_28) (NF32 dt_p0, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__WyNS01ucugkrGheXSbzXhw_29) (void* ClE_0);
struct tySequence__ODAiMr50iWPGXmGFyO9au0w {
  NI len; tySequence__ODAiMr50iWPGXmGFyO9au0w_Content* p;
};
typedef NU8 tyEnum_ChannelKind__awj6Vh1QQR9aUNCKmlUPn3g;
typedef struct {
N_NIMCALL_PTR(NF32, ClP_0) (NF32 input_p0, void* ClE_0);
void* ClE_0;
} tyProc__Gpfb5rC9cmDwspzoCJcvT9cg;
typedef NF32 tyArray__AH8zxXMFV9aJOtXCzmguz0Q[4096];
typedef tyArray__AH8zxXMFV9aJOtXCzmguz0Q tyArray__MLIYHgc9b3aVhhy7Dt9bea6g[2];
typedef NU8 tyEnum_SynthShape__HfZjiipv6DYNKF9bpYMrUQg;
struct tyTuple__YZGftELtXgCScyeZyJvrRw {
	NU8 Field0;
	NU8 Field1;
	tyEnum_SynthShape__HfZjiipv6DYNKF9bpYMrUQg Field2;
};
typedef tyTuple__YZGftELtXgCScyeZyJvrRw tyArray__8fYrKWsiK9cNFYjzjxgot2w[32];
struct tyTuple__ktGn6XuQgErLkL9bJoC2G3A {
	NU8 Field0;
	tyArray__8fYrKWsiK9cNFYjzjxgot2w Field1;
	NU8 Field2;
	NU8 Field3;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
struct tyObject_Channel__in24RcHDml3U5CQrgcGk5g {
	tyEnum_ChannelKind__awj6Vh1QQR9aUNCKmlUPn3g kind;
	tyObject_SfxBuffercolonObjectType___lwjhdE2hrylQh0EU9aI9butg* buffer;
	tyProc__Gpfb5rC9cmDwspzoCJcvT9cg callback;
	NIM_BOOL callbackStereo;
	tyObject_VorbisObj__5PzYikC9ahSxNpWoA19aAkYg* musicFile;
	NI musicIndex;
	NI musicBuffer;
	NIM_BOOL musicStereo;
	NF32 musicSampleRate;
	tyArray__MLIYHgc9b3aVhhy7Dt9bea6g musicBuffers;
	NI loop;
	NF32 phase;
	NF32 freq;
	NF32 basefreq;
	NF32 targetFreq;
	NF32 width;
	NF32 pan;
	tyEnum_SynthShape__HfZjiipv6DYNKF9bpYMrUQg shape;
	NF32 gain;
	tyTuple__ktGn6XuQgErLkL9bJoC2G3A synthData;
	NI synthDataIndex;
	NI init;
	NI env;
	NF32 envValue;
	NI envPhase;
	NI length;
	NI vibspeed;
	NI vibamount;
	NI glide;
	NI pchange;
	NIM_BOOL trigger;
	NU32 lfsr;
	NU32 lfsr2;
	NI nextClick;
	NF32 outvalue;
	NF32 priority;
	tyArray__vEOa9c5qaE9ajWxR5R4zwfQg wavData;
	tyObject_RingBuffer__VjI5utre3g6RZJqTM3xgJg outputBuffer;
};
typedef tyObject_Channel__in24RcHDml3U5CQrgcGk5g tyArray__9ct6ChkkKOZOxiC0M4Gk5Ww[16];
typedef NimStringV2 tyArray__TLUjAhnMfzBtYkb49czB0KA[64];
typedef tyObject_SfxBuffercolonObjectType___lwjhdE2hrylQh0EU9aI9butg* tyArray__rI9cN53rlLps39bq8FMId9b2Q[64];
struct tySequence__4l0J2KoADAIc79csLV36IwA {
  NI len; tySequence__4l0J2KoADAIc79csLV36IwA_Content* p;
};
struct tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A {
	tySequence__4l0J2KoADAIc79csLV36IwA data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
struct tySequence__EwWnHvzGVmDuLlfmw6Igdg {
  NI len; tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content* p;
};
struct tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg {
	tySequence__EwWnHvzGVmDuLlfmw6Igdg data;
	NI head;
	NI tail;
	NI size;
	NI length;
};
typedef tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* tyArray__r4BvwNWZwrhBzTdqZDVtfw[16];
struct tySequence__pcXSChh0J6OCdCDPpBK9b1g {
  NI len; tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content* p;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NimStringV2 text_p0, void* ClE_0);
void* ClE_0;
} tyProc__Hx0b1P9bD01T9bF9aUnykFuyA;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ {
	tySequence__qwqHTkRvwhrRyENtudHQ7g data;
	NI w;
	NI h;
	NIM_BOOL hex;
	NI hexOffset;
	NI tw;
	NI th;
};
typedef tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ tyArray__uzRNaNRWdPJRp9b3rzfDPTw[16];
typedef tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* tyArray__WGdFp1x1TRhEll6Qsgf9cLQ[16];
struct tySequence__friFxHbsLN0MVvin0IyEFg {
  NI len; tySequence__friFxHbsLN0MVvin0IyEFg_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* controller_p0, void* ClE_0);
void* ClE_0;
} tyProc__9cFudSqKwo7KIwGlL9bTobiA;
struct tySequence__QfewH7ZCzlg03Itl2jsx5w {
  NI len; tySequence__QfewH7ZCzlg03Itl2jsx5w_Content* p;
};
typedef tySequence__QfewH7ZCzlg03Itl2jsx5w tyArray__4vilY9btTc3ckSe1VekvIyQ[16];
struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg {
  NI len; tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content* p;
};
struct tySequence__EtvC1a2T849cB0SNWHj6Fbg {
  NI len; tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content* p;
};
struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA {
  NI len; tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content* p;
};
struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw {
  NI len; tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content* p;
};
struct tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg {
	tySequence__29c7ihdQ3dPeS9crD6M3kKQw data;
	NI counter;
};
struct tySequence__g8gk0QJZcC9aEKLq8wBUQNA_Content { NI cap; tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* data[SEQ_DECL_SIZE]; };
struct tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content { NI cap; tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* data[SEQ_DECL_SIZE]; };
struct tySequence__mSbx4ac9awsG2xzbj9b9aZvYQ_Content { NI cap; tyObject_HitboxcolonObjectType___zzXrvetNM0doggw4uVgt4g* data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_AIBtn__B5W7MWqxKrA8cqndnYD8sA;
struct tyTuple__gfz23PD1jgX40Hus9aUuu0A {
	tyEnum_AIBtn__B5W7MWqxKrA8cqndnYD8sA Field0;
	NI Field1;
};
struct tySequence__ODAiMr50iWPGXmGFyO9au0w_Content { NI cap; tyTuple__gfz23PD1jgX40Hus9aUuu0A data[SEQ_DECL_SIZE]; };
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__4l0J2KoADAIc79csLV36IwA_Content { NI cap; tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* data[SEQ_DECL_SIZE]; };
struct tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA {
	NimStringV2 name;
	tyObject_Time__VLFpFOE9bsa4YuGkoFpm3Ig start;
	NI64 time;
	NI count;
	tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA* parent;
	tySequence__EwWnHvzGVmDuLlfmw6Igdg children;
};
struct tySequence__EwWnHvzGVmDuLlfmw6Igdg_Content { NI cap; tyObject_ProfilerNode__YvPczm9ckfTYIBGuRIuJTFA data[SEQ_DECL_SIZE]; };
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI x_p0, NI y_p1, void* ClE_0);
void* ClE_0;
} tyProc__yZbvgbtLeGIhzIA9bifjdPw;
struct tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content { NI cap; tyProc__yZbvgbtLeGIhzIA9bifjdPw data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tySequence__friFxHbsLN0MVvin0IyEFg_Content { NI cap; tyObject_NicoControllercolonObjectType___OpA7H9cHyiLWNuzgwH7k5ZQ* data[SEQ_DECL_SIZE]; };
typedef NI32 tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A;
struct tySequence__QfewH7ZCzlg03Itl2jsx5w_Content { NI cap; tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A data[SEQ_DECL_SIZE]; };
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (tyObject_Event__PhexTflZOX2N20Vr39cGsHg* e_p0, void* ClE_0);
void* ClE_0;
} tyProc__WgqeCw2WGxAI9bmI3lHRKog;
struct tySequence__eXQ7qBth9b8fN9aDUGBmEWLg_Content { NI cap; tyProc__WgqeCw2WGxAI9bmI3lHRKog data[SEQ_DECL_SIZE]; };
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NI sym_p0, NU16 mods_p1, NI scancode_p2, NIM_BOOL down_p3, void* ClE_0);
void* ClE_0;
} tyProc__SR0j0ClEYDvwlJHrgLh3cQ;
struct tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content { NI cap; tyProc__SR0j0ClEYDvwlJHrgLh3cQ data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_TouchState__qs77bc9bzmEAAXZGKPDZsgg;
struct tyObject_Touch__W7l2d79afJabNHgASXk0Cqw {
	NI id;
	NI x;
	NI y;
	NF32 sx;
	NF32 sy;
	NF32 xrel;
	NF32 yrel;
	NF32 xrelraw;
	NF32 yrelraw;
	tyEnum_TouchState__qs77bc9bzmEAAXZGKPDZsgg state;
};
struct tySequence__GyXTUZbNFl9a0ulDnQFpFoA_Content { NI cap; tyObject_Touch__W7l2d79afJabNHgASXk0Cqw data[SEQ_DECL_SIZE]; };
typedef NI32 tyEnum_Keycode__3ENka4Td3JjGlKkKWwkaRw;
struct tyTuple__A9bbISTrJh1vfJUGVCQM7pA {
	NI Field0;
	tyEnum_Keycode__3ENka4Td3JjGlKkKWwkaRw Field1;
	NU32 Field2;
};
struct tySequence__29c7ihdQ3dPeS9crD6M3kKQw_Content { NI cap; tyTuple__A9bbISTrJh1vfJUGVCQM7pA data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_EventKind__JxOY15B8aYUlZq6hKuO3VA;
struct tyObject_Event__PhexTflZOX2N20Vr39cGsHg {
	tyEnum_EventKind__JxOY15B8aYUlZq6hKuO3VA kind;
	NU8 button;
	NI x;
	NI y;
	NF32 xrel;
	NF32 yrel;
	tyEnum_Keycode__3ENka4Td3JjGlKkKWwkaRw keycode;
	tyEnum_Scancode__7AedL0UK3WQVpOBs9cmW51A scancode;
	NU16 mods;
	NU8 clicks;
	NI repeat;
	NI ywheel;
	NimStringV2 text;
	NU8 which;
};
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*, add_enemy__enemy_u83)(NI spr_slot_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___enemy_u157)(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___main_u246)(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ** dest_p0, tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, init__pkgZnico_u445)(NimStringV2 org_p0, NimStringV2 app_p1);
N_LIB_PRIVATE N_NIMCALL(void, createWindow__pkgZnico_u6910)(NimStringV2 title_p0, NI w_p1, NI h_p2, NI scale_p3, NIM_BOOL fullscreen_p4);
N_LIB_PRIVATE N_NIMCALL(void, run__pkgZnico_u7022)(tyProc__HzVCwACFYM9cx9aV62PdjtuA init_p0, tyProc__y9aUXu4JGz72YDIZVWUrK5w update_p1, tyProc__HzVCwACFYM9cx9aV62PdjtuA draw_p2);
N_LIB_PRIVATE N_NIMCALL(void, gameInit__main_u13)(void);
N_LIB_PRIVATE N_NIMCALL(void, loadFont__pkgZnico_u5022)(NI index_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(void, loadSpriteSheet__pkgZnico_u5931)(NI index_p0, NimStringV2 filename_p1, NI32 tileWidth_p2, NI32 tileHeight_p3);
N_LIB_PRIVATE N_NIMCALL(void, loadSfx__pkgZnicoZbackendsZsdl2_u6804)(NI index_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(void, loadMusic__pkgZnicoZbackendsZsdl2_u6826)(NI index_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(void, music__pkgZnicoZbackendsZsdl2_u7222)(NI channel_p0, NI index_p1, NI loop_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, loadPaletteFromGPL__pkgZnico_u63)(NimStringV2 filename_p0, tyTuple__npOdd6OOX5uthJz7z22r9ag* Result);
N_LIB_PRIVATE N_NIMCALL(void, setPalette__pkgZnico_u824)(tyTuple__npOdd6OOX5uthJz7z22r9ag* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, gameUpdate__main_u230)(NF32 dt_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, all_enemies_dead__main_u217)(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* current_stage_p0);
static N_INLINE(void, pluseq___pkgZnicoZbackendsZsdl2_u5859)(NF32* x_p0, NF32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, update_enemies__main_u38)(NF32 dt_p0);
N_LIB_PRIVATE N_NIMCALL(void, update_benkei__benkei_u28)(NF32 dt_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___benkei_u261)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw** dest_p0, tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___movement_u177)(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA** dest_p0, tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ai_u709)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg** dest_p0, tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, move_update__movement_u34)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0, NF32 dt_p1, tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* ms_p2);
N_LIB_PRIVATE N_NIMCALL(void, combat__combat_u87)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character1_p0, tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character2_p1);
N_LIB_PRIVATE N_NIMCALL(void, generate_inputs__ai_u401)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* btndef_p0);
N_LIB_PRIVATE N_NIMCALL(void, AI_update__ai_u759)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* btndef_p0);
N_LIB_PRIVATE N_NIMCALL(void, set_basic_ai__ai_u60)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* btndef_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ai_u706)(tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___movement_u174)(tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___benkei_u258)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, gameDraw__main_u288)(void);
N_LIB_PRIVATE N_NIMCALL(void, cls__pkgZnico_u1521)(NI c_p0);
N_LIB_PRIVATE N_NIMCALL(void, setColor__pkgZnico_u60)(NI colId_p0);
N_LIB_PRIVATE N_NIMCALL(void, hline__pkgZnico_u305)(NI32 x0_p0, NI32 y_p1, NI32 x1_p2);
N_LIB_PRIVATE N_NIMCALL(void, pre_stage__stage_u11)(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* stage_p0);
N_LIB_PRIVATE N_NIMCALL(void, draw_enemies__main_u212)(void);
N_LIB_PRIVATE N_NIMCALL(void, draw_character__character_u329)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0);
N_LIB_PRIVATE N_NIMCALL(void, draw_benkei__benkei_u27)(void);
N_LIB_PRIVATE N_NIMCALL(void, show_hitboxes__combat_u61)(tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* character_p0, NI frame_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___main_u243)(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___main_u292)(tySequence__g8gk0QJZcC9aEKLq8wBUQNA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ai_u65)(tySequence__ODAiMr50iWPGXmGFyO9au0w dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___benkei_u57)(tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1107)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7109)(tyObject_Channel__in24RcHDml3U5CQrgcGk5g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7752)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7710)(tyObject_SfxBuffercolonObjectType___lwjhdE2hrylQh0EU9aI9butg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u7556)(tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u928)(tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZsdl2_u6077)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u1921)(tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3780)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3609)(tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3439)(tySequence__pcXSChh0J6OCdCDPpBK9b1g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3407)(tyProc__Hx0b1P9bD01T9bF9aUnykFuyA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4048)(tyProc__HzVCwACFYM9cx9aV62PdjtuA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3375)(tyProc__y9aUXu4JGz72YDIZVWUrK5w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3209)(tyObject_Tilemap__Bigm4khh76LhlRIpzZDGTQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3167)(tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw** dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u3018)(tySequence__friFxHbsLN0MVvin0IyEFg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2986)(tyProc__9cFudSqKwo7KIwGlL9bTobiA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2949)(tySequence__QfewH7ZCzlg03Itl2jsx5w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2495)(tySequence__eXQ7qBth9b8fN9aDUGBmEWLg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2277)(tySequence__EtvC1a2T849cB0SNWHj6Fbg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u2173)(tySequence__GyXTUZbNFl9a0ulDnQFpFoA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnicoZbackendsZcommon_u187)(tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsbackendsatscommondotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot2dot2atslibatspureatsrandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsbackendsatssdl2dotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsfontdatadotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmbenkeidotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmaidotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__WyNS01ucugkrGheXSbzXhw_2 = { 5 | NIM_STRLIT_FLAG, "fsane" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_3 = {5, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_2};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__WyNS01ucugkrGheXSbzXhw_4 = { 11 | NIM_STRLIT_FLAG, "OneLastBeat" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_5 = {11, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_4};
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_6 = {11, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__WyNS01ucugkrGheXSbzXhw_7 = { 8 | NIM_STRLIT_FLAG, "font.png" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_8 = {8, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_7};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__WyNS01ucugkrGheXSbzXhw_9 = { 10 | NIM_STRLIT_FLAG, "benkei.png" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_10 = {10, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_9};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__WyNS01ucugkrGheXSbzXhw_11 = { 10 | NIM_STRLIT_FLAG, "archer.png" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_12 = {10, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_11};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__WyNS01ucugkrGheXSbzXhw_13 = { 9 | NIM_STRLIT_FLAG, "enemy.png" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_14 = {9, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_13};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__WyNS01ucugkrGheXSbzXhw_15 = { 9 | NIM_STRLIT_FLAG, "heart.png" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_16 = {9, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_15};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__WyNS01ucugkrGheXSbzXhw_17 = { 9 | NIM_STRLIT_FLAG, "arrow.png" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_18 = {9, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_17};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__WyNS01ucugkrGheXSbzXhw_19 = { 8 | NIM_STRLIT_FLAG, "hurt.ogg" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_20 = {8, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_19};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__WyNS01ucugkrGheXSbzXhw_21 = { 9 | NIM_STRLIT_FLAG, "death.ogg" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_22 = {9, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_21};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__WyNS01ucugkrGheXSbzXhw_23 = { 16 | NIM_STRLIT_FLAG, "retro_forest.ogg" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_24 = {16, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_23};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__WyNS01ucugkrGheXSbzXhw_25 = { 17 | NIM_STRLIT_FLAG, "ys-coffe-calm.gpl" };
static const NimStringV2 TM__WyNS01ucugkrGheXSbzXhw_26 = {17, (NimStrPayload*)&TM__WyNS01ucugkrGheXSbzXhw_25};
N_LIB_PRIVATE tySequence__g8gk0QJZcC9aEKLq8wBUQNA stage_set__main_u35;
N_LIB_PRIVATE tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* stage_handler__main_u37;
N_LIB_PRIVATE NIM_CONST NI w__main_u11 = ((NI)160);
N_LIB_PRIVATE NIM_CONST NI h__main_u12 = ((NI)144);
N_LIB_PRIVATE NI current_stage__main_u36 = ((NI)0);
N_LIB_PRIVATE NF32 stage_next_timer__main_u229 = 0.0f;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4433;
extern tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* benkei_char__benkei_u26;
extern tySequence__ODAiMr50iWPGXmGFyO9au0w slow_attack__ai_u59;
extern tySequence__ODAiMr50iWPGXmGFyO9au0w approach__ai_u48;
extern tyObject_HeartcolonObjectType___WXaf61UFtt012QW9cg6Ni8w* benkei_heart__benkei_u8;
extern tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* movements1__benkei_u7;
extern tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* defaultFontSurface__pkgZnicoZfontdata_u6;
extern tyArray__9ct6ChkkKOZOxiC0M4Gk5Ww audioChannels__pkgZnicoZbackendsZsdl2_u143;
extern tyArray__TLUjAhnMfzBtYkb49czB0KA musicFileLibrary__pkgZnicoZbackendsZsdl2_u141;
extern tyArray__rI9cN53rlLps39bq8FMId9b2Q sfxBufferLibrary__pkgZnicoZbackendsZsdl2_u140;
extern tyObject_RingBuffer__5AEViOu9cYv2OfTpleULS2A recordFrames__pkgZnicoZbackendsZsdl2_u139;
extern tyObject_OrderedTable__QZZLTXqGv3g9aySkRqkfj7g* config__pkgZnicoZbackendsZsdl2_u132;
extern tySequence__4Xyxy0Om14N6K1l5e9bUPSQ outputSamples__pkgZnicoZbackendsZsdl2_u119;
extern tySequence__4Xyxy0Om14N6K1l5e9bUPSQ inputSamples__pkgZnicoZbackendsZsdl2_u118;
extern tyObject_RingBuffer__l7yE5p3UVHZD3CzAKAwIrg profileHistory__pkgZnicoZbackendsZcommon_u1942;
extern tyObject_FontcolonObjectType___dvUW3VhhBrL4Rjx0WR5FFg* currentFont__pkgZnicoZbackendsZcommon_u1041;
extern tyArray__r4BvwNWZwrhBzTdqZDVtfw fonts__pkgZnicoZbackendsZcommon_u1040;
extern tySequence__pcXSChh0J6OCdCDPpBK9b1g resizeFuncs__pkgZnicoZbackendsZcommon_u1039;
extern tyProc__Hx0b1P9bD01T9bF9aUnykFuyA textFunc__pkgZnicoZbackendsZcommon_u1038;
extern tyProc__HzVCwACFYM9cx9aV62PdjtuA drawFunc__pkgZnicoZbackendsZcommon_u1035;
extern tyProc__y9aUXu4JGz72YDIZVWUrK5w updateFunc__pkgZnicoZbackendsZcommon_u1033;
extern tyProc__HzVCwACFYM9cx9aV62PdjtuA initFunc__pkgZnicoZbackendsZcommon_u1029;
extern tyArray__uzRNaNRWdPJRp9b3rzfDPTw tilemaps__pkgZnicoZbackendsZcommon_u1026;
extern tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* spritesheet__pkgZnicoZbackendsZcommon_u1025;
extern tyArray__WGdFp1x1TRhEll6Qsgf9cLQ spritesheets__pkgZnicoZbackendsZcommon_u1024;
extern NimStringV2 writePath__pkgZnicoZbackendsZcommon_u1022;
extern NimStringV2 assetPath__pkgZnicoZbackendsZcommon_u1021;
extern NimStringV2 basePath__pkgZnicoZbackendsZcommon_u1020;
extern tySequence__friFxHbsLN0MVvin0IyEFg controllers__pkgZnicoZbackendsZcommon_u996;
extern tyProc__9cFudSqKwo7KIwGlL9bTobiA controllerRemovedFunc__pkgZnicoZbackendsZcommon_u995;
extern tyProc__9cFudSqKwo7KIwGlL9bTobiA controllerAddedFunc__pkgZnicoZbackendsZcommon_u992;
extern tyArray__4vilY9btTc3ckSe1VekvIyQ keymap__pkgZnicoZbackendsZcommon_u989;
extern tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* stencilBuffer__pkgZnicoZbackendsZcommon_u889;
extern tyObject_SurfacecolonObjectType___0nV08lgWmmCQq9akWtUrWUw* swCanvas__pkgZnicoZbackendsZcommon_u888;
extern tySequence__eXQ7qBth9b8fN9aDUGBmEWLg eventListeners__pkgZnicoZbackendsZcommon_u884;
extern tySequence__EtvC1a2T849cB0SNWHj6Fbg keyListeners__pkgZnicoZbackendsZcommon_u879;
extern tyProc__HzVCwACFYM9cx9aV62PdjtuA audioTickCallback__pkgZnicoZbackendsZcommon_u870;
extern tySequence__GyXTUZbNFl9a0ulDnQFpFoA touches__pkgZnicoZbackendsZcommon_u862;
extern tyObject_Table__Ve9bn55DYmdh0AMXQm5C0gg keysDown__pkgZnicoZbackendsZcommon_u244;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4433);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, gameInit__main_u13)(void) {
	tyTuple__npOdd6OOX5uthJz7z22r9ag onebit;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	loadFont__pkgZnico_u5022(((NI)0), TM__WyNS01ucugkrGheXSbzXhw_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSpriteSheet__pkgZnico_u5931(((NI)0), TM__WyNS01ucugkrGheXSbzXhw_10, ((NI32)32), ((NI32)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSpriteSheet__pkgZnico_u5931(((NI)1), TM__WyNS01ucugkrGheXSbzXhw_12, ((NI32)32), ((NI32)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSpriteSheet__pkgZnico_u5931(((NI)2), TM__WyNS01ucugkrGheXSbzXhw_14, ((NI32)32), ((NI32)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSpriteSheet__pkgZnico_u5931(((NI)6), TM__WyNS01ucugkrGheXSbzXhw_16, ((NI32)16), ((NI32)16));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSpriteSheet__pkgZnico_u5931(((NI)7), TM__WyNS01ucugkrGheXSbzXhw_18, ((NI32)16), ((NI32)16));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSfx__pkgZnicoZbackendsZsdl2_u6804(((NI)3), TM__WyNS01ucugkrGheXSbzXhw_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadSfx__pkgZnicoZbackendsZsdl2_u6804(((NI)4), TM__WyNS01ucugkrGheXSbzXhw_22);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadMusic__pkgZnicoZbackendsZsdl2_u6826(((NI)0), TM__WyNS01ucugkrGheXSbzXhw_24);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	music__pkgZnicoZbackendsZsdl2_u7222(((NI)0), ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&onebit), sizeof(tyTuple__npOdd6OOX5uthJz7z22r9ag));
	loadPaletteFromGPL__pkgZnico_u63(TM__WyNS01ucugkrGheXSbzXhw_26, (&onebit));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setPalette__pkgZnico_u824((&onebit));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, all_enemies_dead__main_u217)(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* current_stage_p0) {
	NIM_BOOL result;
	NIM_BOOL isDead;
{	isDead = NIM_TRUE;
	{
		tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw** enemy;
		NI i;
		NI L;
		NI T2_;
		enemy = (tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw**)0;
		i = ((NI)0);
		T2_ = (*current_stage_p0).enemies.len;
		L = T2_;
		{
			while (1) {
				if (!(i < L)) goto LA4;
				enemy = &(*current_stage_p0).enemies.p->data[i];
				{
					if (!!(((*(*(*enemy)).character).state == ((tyEnum_State__BXhE0v2wjSR5Sst324uAcw)10)))) goto LA7_;
					isDead = NIM_FALSE;
				}
LA7_: ;
				i += ((NI)1);
			} LA4: ;
		}
	}
	result = isDead;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, pluseq___pkgZnicoZbackendsZsdl2_u5859)(NF32* x_p0, NF32 y_p1) {
	(*x_p0) = ((NF32)((*x_p0)) + (NF32)(y_p1));
}
N_LIB_PRIVATE N_NIMCALL(void, update_enemies__main_u38)(NF32 dt_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(*stage_handler__main_u37).enable_stage) goto LA3_;
		update_benkei__benkei_u28(dt_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw** wrapped;
			NI i;
			NI L;
			NI T6_;
			wrapped = (tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw**)0;
			i = ((NI)0);
			T6_ = (*stage_handler__main_u37).enemies.len;
			L = T6_;
			{
				while (1) {
					tyObject_CharactercolonObjectType___GNtIvodqMgdkSCDNOnirUw* c;
					tyObject_MovementOptscolonObjectType___yRFNkNKzibvjGjrstxfTsA* m;
					tyObject_BtnDefcolonObjectType___TpOn9bnlrKIa3Q55B57IQjg* btndef;
					if (!(i < L)) goto LA8;
					c = NIM_NIL;
					m = NIM_NIL;
					btndef = NIM_NIL;
					wrapped = &(*stage_handler__main_u37).enemies.p->data[i];
					eqcopy___benkei_u261(&c, (*(*wrapped)).character);
					eqcopy___movement_u177(&m, (*(*wrapped)).movement);
					eqcopy___ai_u709(&btndef, (*(*wrapped)).def);
					move_update__movement_u34(c, dt_p0, m);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					combat__combat_u87(benkei_char__benkei_u26, c);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					generate_inputs__ai_u401(btndef);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					AI_update__ai_u759(btndef);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					set_basic_ai__ai_u60(btndef);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i += ((NI)1);
					eqdestroy___ai_u706(btndef);
					eqdestroy___movement_u174(m);
					eqdestroy___benkei_u258(c);
				} LA8: ;
			}
		}
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, gameUpdate__main_u230)(NF32 dt_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = all_enemies_dead__main_u217(stage_handler__main_u37);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		pluseq___pkgZnicoZbackendsZsdl2_u5859((&stage_next_timer__main_u229), dt_p0);
		{
			if (!(1.0f <= stage_next_timer__main_u229)) goto LA8_;
			current_stage__main_u36 += ((NI)1);
			stage_next_timer__main_u229 = 0.0f;
		}
LA8_: ;
	}
LA4_: ;
	eqcopy___main_u246(&stage_handler__main_u37, stage_set__main_u35.p->data[current_stage__main_u36]);
	update_enemies__main_u38(dt_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, draw_enemies__main_u212)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(*stage_handler__main_u37).enable_stage) goto LA3_;
		{
			tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw** wrapped;
			NI i;
			NI L;
			NI T6_;
			wrapped = (tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw**)0;
			i = ((NI)0);
			T6_ = (*stage_handler__main_u37).enemies.len;
			L = T6_;
			{
				while (1) {
					if (!(i < L)) goto LA8;
					wrapped = &(*stage_handler__main_u37).enemies.p->data[i];
					draw_character__character_u329((*(*wrapped)).character);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i += ((NI)1);
				} LA8: ;
			}
		}
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, gameDraw__main_u288)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	cls__pkgZnico_u1521(((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setColor__pkgZnico_u60(((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	hline__pkgZnico_u305(((NI32)0), ((NI32)98), ((NI32)228));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	pre_stage__stage_u11(stage_handler__main_u37);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(*stage_handler__main_u37).enable_stage) goto LA3_;
		draw_enemies__main_u212();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		draw_benkei__benkei_u27();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	show_hitboxes__combat_u61((*(*stage_handler__main_u37).enemies.p->data[((NI)0)]).character, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsbackendsatscommondotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot2dot2atslibatspureatsrandomdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsbackendsatssdl2dotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicoatsfontdatadotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnicominus0dot4dot10minusf4d0514d40cc9aeaa3f02e3654986ff28d1038ecatsnicodotnim_Init000();
	atmbenkeidotnim_Init000();
	atmaidotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	(*inner)();
#else
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* T1_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T2_;
	tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* T3_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T4_;
	tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* T5_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T6_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T7_;
	tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ* T8_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T9_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T10_;
	tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw* T11_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T12_;
	tyProc__y9aUXu4JGz72YDIZVWUrK5w T13_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T14_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	stage_set__main_u35.len = 4; stage_set__main_u35.p = (tySequence__g8gk0QJZcC9aEKLq8wBUQNA_Content*) newSeqPayload(4, sizeof(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ*), NIM_ALIGNOF(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ*));
	T1_ = NIM_NIL;
	T1_ = (tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ*) nimNewObj(sizeof(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ), NIM_ALIGNOF(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ));
	(*T1_).stage_num = ((NI)1);
	(*T1_).enable_pre_stage = NIM_TRUE;
	(*T1_).enemies.len = 1; (*T1_).enemies.p = (tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content*) newSeqPayload(1, sizeof(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*), NIM_ALIGNOF(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*));
	T2_ = NIM_NIL;
	T2_ = add_enemy__enemy_u83(((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T2_); goto BeforeRet_;}
	(*T1_).enemies.p->data[0] = T2_;
	stage_set__main_u35.p->data[0] = T1_;
	T3_ = NIM_NIL;
	T3_ = (tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ*) nimNewObj(sizeof(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ), NIM_ALIGNOF(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ));
	(*T3_).stage_num = ((NI)2);
	(*T3_).enable_pre_stage = NIM_TRUE;
	(*T3_).enemies.len = 1; (*T3_).enemies.p = (tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content*) newSeqPayload(1, sizeof(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*), NIM_ALIGNOF(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*));
	T4_ = NIM_NIL;
	T4_ = add_enemy__enemy_u83(((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T4_); goto BeforeRet_;}
	(*T3_).enemies.p->data[0] = T4_;
	stage_set__main_u35.p->data[1] = T3_;
	T5_ = NIM_NIL;
	T5_ = (tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ*) nimNewObj(sizeof(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ), NIM_ALIGNOF(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ));
	(*T5_).stage_num = ((NI)3);
	(*T5_).enable_pre_stage = NIM_TRUE;
	(*T5_).enemies.len = 2; (*T5_).enemies.p = (tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content*) newSeqPayload(2, sizeof(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*), NIM_ALIGNOF(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*));
	T6_ = NIM_NIL;
	T6_ = add_enemy__enemy_u83(((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T6_); goto BeforeRet_;}
	(*T5_).enemies.p->data[0] = T6_;
	T7_ = NIM_NIL;
	T7_ = add_enemy__enemy_u83(((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T7_); goto BeforeRet_;}
	(*T5_).enemies.p->data[1] = T7_;
	stage_set__main_u35.p->data[2] = T5_;
	T8_ = NIM_NIL;
	T8_ = (tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ*) nimNewObj(sizeof(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ), NIM_ALIGNOF(tyObject_StageDefcolonObjectType___UcMaWIjGo9c5Bv0yG3660iQ));
	(*T8_).stage_num = ((NI)4);
	(*T8_).enable_pre_stage = NIM_TRUE;
	(*T8_).enemies.len = 3; (*T8_).enemies.p = (tySequence__6eW0sN9cwnKC4gxJcPFupZQ_Content*) newSeqPayload(3, sizeof(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*), NIM_ALIGNOF(tyObject_EnemyWrappedcolonObjectType___8yhvQa9cpB762Fw7uK9bMSCw*));
	T9_ = NIM_NIL;
	T9_ = add_enemy__enemy_u83(((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T9_); goto BeforeRet_;}
	(*T8_).enemies.p->data[0] = T9_;
	T10_ = NIM_NIL;
	T10_ = add_enemy__enemy_u83(((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T10_); goto BeforeRet_;}
	(*T8_).enemies.p->data[1] = T10_;
	T11_ = NIM_NIL;
	T11_ = add_enemy__enemy_u83(((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___enemy_u157(T11_); goto BeforeRet_;}
	(*T8_).enemies.p->data[2] = T11_;
	stage_set__main_u35.p->data[3] = T8_;
	eqcopy___main_u246(&stage_handler__main_u37, stage_set__main_u35.p->data[current_stage__main_u36]);
	init__pkgZnico_u445(TM__WyNS01ucugkrGheXSbzXhw_3, TM__WyNS01ucugkrGheXSbzXhw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	createWindow__pkgZnico_u6910(TM__WyNS01ucugkrGheXSbzXhw_6, w__main_u11, h__main_u12, ((NI)4), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T12_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T12_.ClP_0 = ((TM__WyNS01ucugkrGheXSbzXhw_27) (gameInit__main_u13)); T12_.ClE_0 = NIM_NIL;
	nimZeroMem((void*)(&T13_), sizeof(tyProc__y9aUXu4JGz72YDIZVWUrK5w));
	T13_.ClP_0 = ((TM__WyNS01ucugkrGheXSbzXhw_28) (gameUpdate__main_u230)); T13_.ClE_0 = NIM_NIL;
	nimZeroMem((void*)(&T14_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T14_.ClP_0 = ((TM__WyNS01ucugkrGheXSbzXhw_29) (gameDraw__main_u288)); T14_.ClE_0 = NIM_NIL;
	run__pkgZnico_u7022(T12_, T13_, T14_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___main_u243(stage_handler__main_u37);
	eqdestroy___main_u292(stage_set__main_u35);
	eqdestroy___ai_u65(slow_attack__ai_u59);
	eqdestroy___ai_u65(approach__ai_u48);
	eqdestroy___benkei_u258(benkei_char__benkei_u26);
	eqdestroy___benkei_u57(benkei_heart__benkei_u8);
	eqdestroy___movement_u174(movements1__benkei_u7);
	eqdestroy___pkgZnicoZbackendsZcommon_u1107(defaultFontSurface__pkgZnicoZfontdata_u6);
	eqdestroy___pkgZnicoZbackendsZsdl2_u7109(audioChannels__pkgZnicoZbackendsZsdl2_u143);
	eqdestroy___pkgZnicoZbackendsZsdl2_u7752(musicFileLibrary__pkgZnicoZbackendsZsdl2_u141);
	eqdestroy___pkgZnicoZbackendsZsdl2_u7710(sfxBufferLibrary__pkgZnicoZbackendsZsdl2_u140);
	eqdestroy___pkgZnicoZbackendsZsdl2_u7556((&recordFrames__pkgZnicoZbackendsZsdl2_u139));
	eqdestroy___pureZparsecfg_u928(config__pkgZnicoZbackendsZsdl2_u132);
	eqdestroy___pkgZnicoZbackendsZsdl2_u6077(outputSamples__pkgZnicoZbackendsZsdl2_u119);
	eqdestroy___pkgZnicoZbackendsZsdl2_u6077(inputSamples__pkgZnicoZbackendsZsdl2_u118);
	eqdestroy___pkgZnicoZbackendsZcommon_u1921((&profileHistory__pkgZnicoZbackendsZcommon_u1942));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pkgZnicoZbackendsZcommon_u3780(currentFont__pkgZnicoZbackendsZcommon_u1041);
	eqdestroy___pkgZnicoZbackendsZcommon_u3609(fonts__pkgZnicoZbackendsZcommon_u1040);
	eqdestroy___pkgZnicoZbackendsZcommon_u3439(resizeFuncs__pkgZnicoZbackendsZcommon_u1039);
	eqdestroy___pkgZnicoZbackendsZcommon_u3407((&textFunc__pkgZnicoZbackendsZcommon_u1038));
	eqdestroy___system_u4048((&drawFunc__pkgZnicoZbackendsZcommon_u1035));
	eqdestroy___pkgZnicoZbackendsZcommon_u3375((&updateFunc__pkgZnicoZbackendsZcommon_u1033));
	eqdestroy___system_u4048((&initFunc__pkgZnicoZbackendsZcommon_u1029));
	eqdestroy___pkgZnicoZbackendsZcommon_u3209(tilemaps__pkgZnicoZbackendsZcommon_u1026);
	eqdestroy___pkgZnicoZbackendsZcommon_u1107(spritesheet__pkgZnicoZbackendsZcommon_u1025);
	eqdestroy___pkgZnicoZbackendsZcommon_u3167(spritesheets__pkgZnicoZbackendsZcommon_u1024);
	if (writePath__pkgZnicoZbackendsZcommon_u1022.p && !(writePath__pkgZnicoZbackendsZcommon_u1022.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(writePath__pkgZnicoZbackendsZcommon_u1022.p);
}
	if (assetPath__pkgZnicoZbackendsZcommon_u1021.p && !(assetPath__pkgZnicoZbackendsZcommon_u1021.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(assetPath__pkgZnicoZbackendsZcommon_u1021.p);
}
	if (basePath__pkgZnicoZbackendsZcommon_u1020.p && !(basePath__pkgZnicoZbackendsZcommon_u1020.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(basePath__pkgZnicoZbackendsZcommon_u1020.p);
}
	eqdestroy___pkgZnicoZbackendsZcommon_u3018(controllers__pkgZnicoZbackendsZcommon_u996);
	eqdestroy___pkgZnicoZbackendsZcommon_u2986((&controllerRemovedFunc__pkgZnicoZbackendsZcommon_u995));
	eqdestroy___pkgZnicoZbackendsZcommon_u2986((&controllerAddedFunc__pkgZnicoZbackendsZcommon_u992));
	eqdestroy___pkgZnicoZbackendsZcommon_u2949(keymap__pkgZnicoZbackendsZcommon_u989);
	eqdestroy___pkgZnicoZbackendsZcommon_u1107(stencilBuffer__pkgZnicoZbackendsZcommon_u889);
	eqdestroy___pkgZnicoZbackendsZcommon_u1107(swCanvas__pkgZnicoZbackendsZcommon_u888);
	eqdestroy___pkgZnicoZbackendsZcommon_u2495(eventListeners__pkgZnicoZbackendsZcommon_u884);
	eqdestroy___pkgZnicoZbackendsZcommon_u2277(keyListeners__pkgZnicoZbackendsZcommon_u879);
	eqdestroy___system_u4048((&audioTickCallback__pkgZnicoZbackendsZcommon_u870));
	eqdestroy___pkgZnicoZbackendsZcommon_u2173(touches__pkgZnicoZbackendsZcommon_u862);
	eqdestroy___pkgZnicoZbackendsZcommon_u187((&keysDown__pkgZnicoZbackendsZcommon_u244));
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

